### ISSUE TITLE
migration notes

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1014]
Some items to address
- [x] fixup any links / references in user.js
- [x] license needs `Copyright (c) 2017 ghacksuserjs` edited
- [x] updater scripts will need to check for arkenfox, not ghacks
- [x] readme
- [x] rename scratchpad scripts
- [x] code cleanups - [three left](https://github.com/arkenfox/user.js/search?q=ghacks&type=code) including updater scripts
- [x] check the wiki (script names, references, links)
- [ ] travis? what happened to the green ticks on commits - they stopped 3 days before the migration. Note we still have `verified` notation

**Comment by earthlng** [comment]
I updated the updater.bat to let it recognise both ghacks and arkenfox user.js files.
If/when you update the "ghacks" strings in updater.bat just make sure to keep [line 104](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.bat#L104) intact!
That's the only place where "ghacks" is used as more than just static text (or a link).

Any other changes of ghacks references in any of the files should be done **after** the migration.

re: Releases - the current ones should all keep the ghacks name because they all contain "ghacks" files.
But I think we can remove some of the older "earthlng" pre-releases, maybe up to and including `earthlng user.js v68.0-beta` ?

**Comment by Thorin-Oakenpants** [comment]
Yup, wasn't going to action anything until after the migration. The only question is when do we do it. I'm super keen to pull the trigger right now, as many users will be visiting / checking things as they start using the ESR78 - i.e, it's a prime opportunity to break something and force them to look. The other argument to that is don't upset/break anything until after, so no ESR users are affected

👍 pull the trigger now
👎 wait til after the next release

**Comment by Thorin-Oakenpants** [comment]
> or assign me :)

sounds like a plan

**Comment by Ne3tCode** [comment]
https://github.com/arkenfox/user.js/wiki/4.1-Extensions/_compare/bfa7353%5E...bfa7353
Broken signs ✔ ❗️ ⚠️

**Comment by Thorin-Oakenpants** [comment]
thanks - fixed. I hope the other pages are OK. I just edited the entire wiki by cutting, search+replace in notepad and pasting back. I guess some of the symbols didn't like it

**Comment by Thorin-Oakenpants** [comment]
IDK about the last item

**Comment by lhindir** [comment]
I recently came back to this repo and saw it was renamed. It looks like you completely deleted not just the content in the original comment but all edit history in this issue. Can you explain what used to be here and why the repo was renamed? It's still possible to see "the old name" in the commit history anyway

**Comment by rusty-snake** [comment]
> why the repo was renamed?

> Nah, you can't ask why, sorry - well, you can, but I will not answer that question.

source: #1009
