### ISSUE TITLE
FYI: some emojis are monochrome (with RFP) [fixed in FF82+]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1033]
Not sure about anyone else, probably depends on a range of factors

previously (for years)
- disabled document fonts as per the user.js
- note: and I had a whitelist which is probably not relevant - it included the bundled emoji font from Mozilla
- Windows, en-US FF build, default font is Times New Roman
- emojis have been normal

Now
- am allowing document fonts as per the user.js, (no whitelist)
- some emojis are, well, to put it as nicely as I can... they are shit :)
- here's a pic of me using some emojis in github
- ![suck](https://user-images.githubusercontent.com/16656956/95286168-1e158780-0852-11eb-81d7-a50734699d78.png)
- here's a test: https://bug1371386.bmoattachments.org/attachment.cgi?id=8875842

I did some binary troubleshooting in a vanilla FF81 and the culprit was RFP (but not really). And I traced it all the way back to FF68 (not really) - my FF67+RFP = fine, FF68+noRFP = fine, FF68+RFP = shit emojis <-- vanilla profiles

But I also found that 82Beta, 82Dev and 83Nightly don't have this problem: so I did some digging - [1371386](https://bugzilla.mozilla.org/show_bug.cgi?id=1371386)

So it seems as if the underlying cause goes back as far as FF53, and NFI why RFP causes it to rear up, or exactly why blocking doc fonts fixed it with RFP on (for me, all those years). I have an idea why, but lets not go there :) Suffice to say that whatever I saw was a symptom and not the actual problem. So it's not RFP causing it, per se.

Anyone else seeing some of these monochrome old-timey Times New Roman emojis? It's only ones that exist in TNR otherwise it moves onto using Twemoji - on Win7 so I have an old-timey Times New Roman

**Comment by syncng** [comment]
My goodness, is this it? Is this my moment to shine? Finally, something I can actually help with (kinda)
I think that's the **_Segoe UI Symbol_** font.

For me, normally, if I have RFP on (although I have not tested it as extensively as you have), even if I modify `font.name-list.emoji` to only have Twemoji, Firefox will completely ignore the built-in Twemoji font (as far as I can tell) and just goes with the Segoe UI Emoji font, **or if you don't have that**, the more primitive Segoe UI Symbol font (which is what I think is happening to you).

In my personal case, I've never established a connection between this and `browser.display.use_document_fonts` though.

I'm also on Win10, not 7, so it might differ there as well.
**And** the new font coverage on RFP might also be fucking with things.
With so many nuances clustered together, it's gonna be hard to find where the actual problem is.

**Comment by Thorin-Oakenpants** [comment]
Thanks. I remember Segoe from previous reading. I didn't read that ticket, just latched onto the test. I'm not a font expert and have no idea how chars are decoded to which fonts or how fallback works or font address spaces or whatever.

It wasn't a problem in a vanilla FF ever for me (and probably almost everyone), ant the ticket was open for over 3 years. That RFP (before RFP even had anything to do with fonts) caused it to change in FF68 (for me) is nuts. But that's not the reason it was fixed - because the problem happened for users with no RFP. On top of that, blocking doc fonts fixed it with RFP -> weird - but yes, I do have `Segoe UI` and `Segoe UI Symbol Regular` - so maybe I lucked out in my config, and however all that font char stuff and unicode works, it is what it is.

The other thing is that I did have this problem once before, when I started using a whitelist: and I had to add `EmojiOne Mozilla` / `Twemoji` to the whitelist to fix it (but that was pre FF68, so probably not relevant).

I can test if the emoji is actually different - i.e my old config compare the font to the one I see in FF82 <-- that might indicate Segoe vs Twemoji. But at this point, I am so over fonts...

**Comment by Thorin-Oakenpants** [comment]
>And the new font coverage on RFP might also be fucking with things.

nah. I ruled that out with my tests

> Unfortunately, with so many nuances clustered together, it's gonna be hard to find where the actual problem is

There is no problem, because it has been fixed in the next release. I just wanted to FYI in case people were going ... WTF man!
