### ISSUE TITLE
CSPAN Video [solved: allow the specific third party cookie]

### ISSUE THREAD

**Issue by DebSec** [arkenfox/user.js#1039]
I updated to latest ESR user.js and now I'm unable to load or correctly view videos on https://www.c-span.org/

I created a new profile with vanilla  settings and the user.js and I get several erroneous errors with JW Player and Brightcove if I remember correctly.

I poked under the hood to no avail and I figured as your reading this someone knows the issue.

Please share the changes needed please.

If I'm wrong I apologize ahead of time if it is something I missed on my end somehow.

**Comment by Thorin-Oakenpants** [comment]
I haven't looked at your specific issue, but did you look at the `setup-web` tagged items? e.g.

```js
/* 1830: disable all DRM content (EME: Encryption Media Extension)
 * [SETUP-WEB] if you *need* EME, e.g. Netflix, Amazon Prime, Hulu, whatever
 * [SETTING] General>DRM Content>Play DRM-controlled content
 * [1] blah blah ***/
user_pref("media.eme.enabled", false);
```

Have you tried [troubleshooting](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting). I usually just do a binary method: apply `half` the user.js to a new profile, retest, based on results I either add another `quarter` and retest, or then reset the new profile and add a `quarter` and retest, etc

**Comment by DebSec** [comment]
I do not agree with DRM as if I purchase something I should be able to do what I want with it to a degree. Obviously reselling a book that is in PDF is a bad thing. I'm not sure I agree with disabling this area. You need a cable box or satellite box to decrypt those services and Apps for Roku and such are encrypted and proprietary.
I do not agree with there actions but do think I would want to protect my nest egg in some way also. I do not think this should be disabled as this is a basic function of a browser to be able to view videos.

Anyway. Just my opinion. The setting was not the fix I needed. Yes I tried the troubleshooter script but I received a error getting it to run. As I do not have time to troubleshoot in the manual way you suggest right now I will try it again at a later date. OpenH264 was also enabled for the plugin area. Thanks for the effort.

**Comment by Thorin-Oakenpants** [comment]
the problem is third party cookies

I just kept retesting in a new profile, adding large chunks of the user.js. When I hit the 2700's it stops working. At some stage (probably some autoplay media pref), it requires clicking in the video to start play (after the advert), but that doesn't break it.

Once it stopped being able to play, I flipped `2701` `network.cookie.cookieBehavior` to default (value 4 in FF81) in about:config, reloaded the page and it worked

![console-clues](https://user-images.githubusercontent.com/16656956/96043941-2d529180-0e5f-11eb-910f-506e7ebe1a2c.png)

Now I don't think the answer is to blanket allow all cookies, but maybe you're OK with that: given you can clear cookies etc on close, and/or control third parties tightly with uBO, and Firefox already blocks a heap of crap (and if you're using FPI then third parties don't really matter). It's your decision

If it was me: I just use a secondary browser: I have Nightly here for testing things. Or, and I'm not sure you can apply a third party exception (I've never tried): but in about:preferences#privacy where it says manage exceptions, you could try adding akamaid to always allow or something. Note: if using FPI (or dPFI), you would need to make sure it contained that in the syntax

**Comment by Thorin-Oakenpants** [comment]
OK this works. No need to allow all cookies

![exception](https://user-images.githubusercontent.com/16656956/96045290-49573280-0e61-11eb-9dc8-d353bbbb02ae.png)

If you're using FPI I think you need to add that (they changed a few things so it may fallback and accept a non-OA'ed one)

`https://cspan1nontve-lh.akamaidh.net^firstPartyDomain=https://cspan1nontve-lh.akamaidh.net`

Try them

**Comment by Thorin-Oakenpants** [comment]
re-open if you need to

**Comment by DebSec** [comment]
Thank you for the efforts. I did what you said and tracked down the issue. It is Enhanced Tracking Protection.
Sort of a bone head move on my end. I had to add the exception of turning off enhanced tracking protection for the website using the shield and adding to the exclusion list.

You probably touched on it above. I did find out that the issue was in this area also.
* [SETTING] Privacy & Security>Enhanced Tracking Protection>Custom>Cookies ***/
It was like this before for me in ESR using strict with everything checked off but something changed I think under the hood.

Again thanks and stay safe.

**Comment by Thorin-Oakenpants** [comment]
ESR. Probably. Lots of things happen in between releases. So you're still able to block all third party cookies by default then? ANd all you did was use the blue ETP shield in the urlbar and disable ETP for that site? note: I ditched the test profile I had for you, but you could probably have just tweaked the ETP site exception rather than disabled it)

Anyway: good to know you're all set to watch the riveting dumpster fire of US politics

**Comment by DebSec** [comment]
Exactly. Jumped from last years ESR on Buster Debian to all this new fangled stuff. 
I had lots of changes in the theme I used also.
All I ended up having to do was click turn off tracking protection for the website on the shield icon in the url bar.
Third party cookies blocked as before.
The main page does not display placeholder or whatnot for the videos but I read the links and then click to navigate to them. It works.

More so the thing bothered me as it worked before and then did not.
Thank you.

**Comment by DebSec** [comment]
The fix with using the TP Blue Shield to disable tracking protection works for streaming video as we were probably both doing.

I later on went back to see why placeholder images and things were not displaying correctly.
I could not then play archived videos. I tried your settings and exceptions but they did not work.
I opened the council and seen there were a plethora of cross domain requests that were blocked.

I needed to set :
+1: /* 1603: CROSS ORIGIN: control when to send a referer
 * 0=always (default), 1=only if base domains match, 2=only if hosts match
 * [SETUP-WEB] Known to cause issues with older modems/routers and some sites e.g vimeo, icloud ***/
user_pref("network.http.referer.XOriginPolicy", 1);

To default and the site functioned properly. I suspect they need to update there cross domain policies.

I will leave it as 1 and deal with it as needed as I should not have to have the addon to handle it for one website.

Wat to go .Gov :-1: 

Thanks
