### ISSUE TITLE
Add Note for Enabling WebRTC

### ISSUE THREAD

**Issue by MetalNeo** [arkenfox/user.js#1043]
WebRTC cannot be enabled by appending `user_pref("media.peerconnection.enabled", true);` to the bottom of `user.js`. The preceding `user_pref("media.peerconnection.enabled", false);` must be commented out and then the setting must be enabled manually in `about:config`. Even if `user_pref("media.peerconnection.enabled", true);` is present at the bottom of `user.js` to enable WebRTC, this manual process must still be completed. After being enabled once in `about:config`, the setting will remain enabled.

A note should be added under 2001 detailing these directions to enable WebRTC.

**Comment by Thorin-Oakenpants** [comment]
Thanks @MetalNeo : I'll get to this over the next week for the 82 release

**Comment by Thorin-Oakenpants** [comment]
@MetalNeo can you give steps to reproduce: including the site you used to test on, because I can't reproduce (but I also lack any attached mics/video cameras)

Here's what I did

Test1: https://test.webrtc.org/
Test2: https://browserleaks.com/webrtc

control: confirm it's working: vanilla profile FF81
- test1: udp/ tcp / relay / host: all checked
- test2: RTCPeerConnection + RTCDataChannel: both checked

confirm: add entire default user.js
- test1: completely broken
- test2: both blocked

add override: `user_pref("media.peerconnection.enabled", true);`
 - test1: [for me] prompted me to continue without audio/video, and when clicked continue, did nothing
 - test2: looks good to me

add another override: `user_pref("media.navigator.enabled", false);`
 - tests look the same (for me) as with just the one override: but do note I have one audio input apparently, but no video

**Comment by Thorin-Oakenpants** [comment]
bump @MetalNeo

**Comment by MetalNeo** [comment]
I wasn't trying to access a particular website. I was trying to get the [Snowflake](https://addons.mozilla.org/en-US/firefox/addon/torproject-snowflake/) addon to work, which requires WebRTC to be enabled.

At first, I tried adding `user_pref("media.peerconnection.enabled", true);` to the bottom of the default user.js. The addon didn't work upon starting because the setting was still disabled, so I manually enabled the setting in about:config. After enabling manually, I tried to restart the browser to test the addon again, but the setting was reset again to disabled upon restarting.

After this failed, I tried commenting out the original `user_pref("media.peerconnection.enabled", false);`, keeping the other line to enable it at the bottom, and testing the browser again. Upon starting, the setting was still disabled. Even though I had kept the line to enable it and commented out the line to disable it, it still wasn't automatically being enabled by user.js.

So, I manually enabled it in about:config one more time. This time it started to save the setting between restarts and I was able to get the addon to work properly.

**Comment by Thorin-Oakenpants** [comment]
so the second entry never got set: which I can't reproduce (I might try with the snowflake addon installed): the first entry sounds like a red herring (setting the value or commented out is immaterial).

so it's either something to do with a syntax error (everyone is human: I'm not ruling it out), or it's something else. Add the following lines to the _END_ of your user js

```js
user_pref("_user.js.parrot.special", "attempting to enable webrtc");
user_pref("media.peerconnection.enabled", true);
user_pref("_user.js.parrot.special", "congrats! webrtc enabled");
```

after a restart, go to about:config and type parrot .. what does the special one say. Not all syntax errors cause the parsing of the user.js to abort, but if the parrot.special doesn't even exist, then it indicates there's an issue further up

**Comment by earthlng** [comment]
That pref is one of the privacy Webextensions API prefs and that could be the reason for this issue.

@MetalNeo can you check your `extension-settings.json` file for `peerConnectionEnabled` and let us know which addon it came from (and what the `value` and `enabled` are set to) ?

**Comment by MetalNeo** [comment]
It ended up being human error. I only used one forward slash for the comment above the setting instead of two, causing it to not set properly. Issue resolved.

**Comment by Thorin-Oakenpants** [comment]
> That pref is one of the privacy Webextensions API prefs and that could be the reason for this issue.

reopening: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy

We could add something to the wiki or user.js. IDK
- maybe the troubleshooting: we already point out that extensions should be eliminated as the problem but it can't hurt
- user.js: maybe add an `[SETUP-EXT]` tag (sounds like too much work TBH) that indicates these can be controlled by an extension, or just selectively add info on a couple of prefs, or just provide a general warning and a link?

That's the privacy API ones, but we also have home page and I guess others

I've been wanting to warn about toggling RFP (and probably FPI). Some RFP features require existing tabs to close or they leak when reloaded (depending on if you toggled it on or off).

Thoughts?

**Comment by earthlng** [comment]
It ended up being human error and not related to the WE prefs APIs, so no, I don't think we need to add anything for this.

What we probably should do though is mention something about checking the console right after startup and look for warnings/errors about prefs not being applied due to syntax errors.

**Comment by earthlng** [comment]
^^ ... to the Troubleshooting wiki page

**Comment by Thorin-Oakenpants** [comment]
^^ done

**Comment by earthlng** [comment]
thanks! I changed it a bit to explicitly mention pref-parsing related errors

**Comment by Thorin-Oakenpants** [comment]
seriously .. I was going to use `jesus.on.a.dinosaur`
