### ISSUE TITLE
RFP is great, but I want my timezone back :)

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1049]
Tried to funnily write the title, but is there a way to restore local timezone/datetime with RFP enabled?

Thanks and cheers

**Comment by Thorin-Oakenpants** [comment]
*sigh* ....

```
/*** [SECTION 4500]: RFP (RESIST FINGERPRINTING)
   RFP covers a wide range of ongoing fingerprinting solutions.
   It is an all-or-nothing buy in: you cannot pick and choose what parts you want

   [WARNING] Do NOT use extensions to alter RFP protected metrics
```

if you can find an extension that only uses a list to apply to: i.e it only lies about the timezone for e.g. gmail (and you're already logged into gmail, so tracking you is not the issue), then sure: that shouldn't be an issue

However, if you use an extension to spoof all websites then your fingerprint is fucked: you'll be the only RFP person with a timezone of X. Also be aware that extensions lack the proper APIs to spoof timezone: however, in this case, all they would get is underlying RFP spoof of UTC 0: which is already known since they know you're using RFP (it can be detected in about 1ms)

Seriously: if you need the correct timezone, use a secondary browser. I have my nightly which is opening/closing tens of dozens of times a day, sanitizing on close. Just do something like that

**Comment by Thorin-Oakenpants** [comment]
Note: there are plans to provide an allowlist/exceptions for RFP (as a whole, not parts of it)
 - [1635603](https://bugzilla.mozilla.org/show_bug.cgi?id=1635603) is what you need to keep an eye on

**Comment by Thorin-Oakenpants** [comment]
> Tried to funnily write the title

Hmmm .. it's been bugging me. I can almost taste the answer. Like some line from a movie "Chad is great...". But I think it's a meme: "This is great .. but"

![tor-this-is-great-but-wheres-the-coffee](https://user-images.githubusercontent.com/16656956/97183064-34e63480-1795-11eb-8d46-b037222b2849.jpg)
