### ISSUE TITLE
FYI: WebRTC: how to enable Google Meet | JitsiMeet | BigBlueButton etc

### ISSUE THREAD

**Issue by gabriel-coelho** [arkenfox/user.js#1068]
I'm *unfortunately* obligated to use Google Meet everyday for school. The user.js seems to cause the [website](https://meet.google.com) to break. Does anyone know what should I enable/disable to get it to work?

**Comment by crssi** [comment]
Hi kiddo 😄 
Could you be more specific, what exactly does not work?

**Comment by rusty-snake** [comment]
BigBlueButton (and JitsiMeet) require this, Google Meet will require it likewise I guess.
```javascript
/* BBB */
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001
user_pref("dom.webaudio.enabled", true); // 2510
user_pref("media.autoplay.blocking_policy", 0); // 2031
```
Notes:
- Make sure "Prevent WebRTC from leaking local IP addresses" is unchecked in uBlock origin
- Instead of  "media.autoplay.blocking_policy=0" you can add a exception to allow audio and video autoplay

**Comment by crssi** [comment]
@rusty-snake... did you test it?

Here I have:
``` js
user_pref("media.peerconnection.ice.no_host", true); // 2001
user_pref("media.autoplay.blocking_policy", 1); // 2031
```
and it works, but I suspect it might also have something with https://github.com/arkenfox/user.js/blob/fa85c9da5b357726e6f35a138d6b96b977655012/user.js#L942-L945

At least I have:
``` js
user_pref("media.getusermedia.screensharing.enabled", true); // 2022
```

**Comment by gabriel-coelho** [comment]
I've added these settings to my user.js:

```
user_pref("media.getusermedia.screensharing.enabled", true); // 2022
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001
user_pref("dom.webaudio.enabled", true); // 2510
user_pref("media.autoplay.blocking_policy", 0); // 2031
```

Now everything seems to be working fine, thanks for the help!

---

One last question... privacy-wise, how much does this affect me?

**Comment by Thorin-Oakenpants** [comment]
> privacy-wise, how much does this affect me

privacy-wise, absolutely nothing is affected: it is about linkability: linking traffic can unmask a user, but that compromises anonymity, not privacy

`dom.webaudio.enabled`
- risk: SUPER LOW: used for fingerprinting, and known/major fingerprinters are blocked by default in Firefox's Enhanced Tracking Protection. If you're using uBlock Origin (and I hope you are), this will filter out a lot of tracking scripts (and thus fingerprintering scripts as well) and can be used in various modes. Fingerprinting scripts need to be consistent between each other in order to make the data cross script compatible, but they don't do that. Other fingerprinting metrics are already neutered with RFP (privacy.resistFingerprinting). IF you get fingerprinted by a decent script, chances it gets much is debatable, chances it can be widely used against you are slim. As as for webaudio itself - the entropy is not what people think it is: it is **not affected by hardware**, the entropy comes from math and floating points - you already leak the same equivalency (in fact more entropy since audio is limited in it's math functions and ranges) in other unprotected areas.
- as an example: my two android phones and my desktop machine (in windows and in several linux VMs) all report the same fingerprint for audioContext. Someone else has reported the same FP on a mac

`media.autoplay.blocking_policy`
- risk: NONE: as far as I can tell: you can use site exceptions as rusty pointed out, while still stopping vids autoplaying on every site

`media.peerconnection.enabled`
- this is WebRTC which can leak your IP if you're behind a VPN
   - Not all VPNs are equal: some have webrtc special protections in settings etc: you would need to test it
   - If you're not using a VPN, then you're already rvealing your real IP  = the super easy linkability of all your web traffic

**Comment by crssi** [comment]
Interestingly, it does work here with:
``` js
user_pref("media.peerconnection.ice.no_host", true); // 2001
```

@gabriel-coelho Can you re-test for this setting again? Thank you

**Comment by rusty-snake** [comment]
> > privacy-wise, how much does this affect me
> dom.webaudio.enabled

CB can be used to alter this a bit. However, CB must be configured correctly (it alters RFP too???). I don't use it.

> Interestingly, it does work here with:

Yesterday It had worked too, today it's broken. Weird.

**Comment by crssi** [comment]
Thanks @rusty-snake 

> Yesterday It had worked too, today it's broken. Weird.

But not here... here it is still working just great. Weird again. 😄

**Comment by gabriel-coelho** [comment]
> @gabriel-coelho Can you re-test for this setting again? Thank you

I have, but it only seems to work with all the changes I mentioned.

---

Thank you everyone for the help and thanks @Thorin-Oakenpants for the clarification.

**Comment by Thorin-Oakenpants** [comment]
we rejigged all the WebRTC prefs in AF v95 including making the override recipe obsolete, hence label changes
