### ISSUE TITLE
Missing on the script please add

### ISSUE THREAD

**Issue by samuraikidXDA** [arkenfox/user.js#1071]
Hi there ! Before all thanks for your work  ! 
Here are some additions i notice your script didn't add on my firefox 

```
browser.cache.offline.enable

Whether web applications and sites can use an offline cache on the local system.

    True: Web applications may use an offline cache (default)
    False: Offline cache functionality is disabled.



browser.cache.memory.enable

Whether a memory cache is used by the browser.

    True: Firefox will make use of a memory cache.
    False: The browser's memory cache is disabled and thus not used.



beacon.enabled

Sends data to servers when leaving pages.

    True: Feature is enabled and web apps can make use of it (default).
    False: Disables the feature.



browser.fixup.alternate.enabled

Defines whether Firefox's "fixup" feature is used.

    True: Will use fixup to automatically add prefix and suffix to single words you enter in the browser's address bar. (default)
    False: Won't use it which means that Firefox will always redirect to search, even for single word entries.



browser.safebrowsing.enabled

Determines whether Firefox should check urls that are opened in it against a web forgery database (uses Google by default)

    True: Firefox will check urls and block them if they are forgeries.
    False: Firefox will not run those checks.


browser.safebrowsing.malware.enabled

Whether Firefox will use malware information to determine if downloads are malicious.

    True: Will use a malware database to scan downloads. (default)
    False: Won't download malware information or scan downloads.

browser.selfsupport.url

Determines whether the Heartbeat feedback feature is enabled in Firefox.

    True: Feature is enabled and short feedback surveys may be displayed (default).
    False: Feature is disabled.



browser.send_pings

Informs servers about links that get clicked on by the user.

    True: Feature is enabled.
    False: Pings are not enabled.



dom.battery.enabled

Gives web applications access to the battery status of mobile devices. May be used in fingerprinting techniques.

    True: Allows web applications to retrieve the battery status (default).
    False: Disables the functionality.




dom.event.clipboardevents.enabled

Determines whether websites are allowed to access clipboard contents (check out: Block websites from reading or modifying Clipboard contents in Firefox for additional information).

    True: Websites may read or modify clipboard events. (default)
    False: Blocks access.




dom.event.contextmenu.enabled

Determines whether websites are allowed to block access to the right-click context menu.

    True: Websites may manipulate the context menu. (default)
    False: Web pages won't be allowed to manipulate or block the context menu.



dom.storage.enabled

This parameter defines whether "client-side session and persistent storage" capabilities are enabled in Firefox (meaning if the feature can be used by websites and applications to store data on the client computer).

    True: Client side storage is enabled.
    False: The feature is disabled.



extensions.getAddons.cache.enabled

This sends a daily ping to Mozilla about installed add-ons and recent start-up times.

    True: Sends the ping to Mozilla (default).
    False: Blocks it. This turns off add-on recommendations and won't update add-on metadata (the description) anymore).




geo.enabled

Determines if location aware browsing is enabled.

    True: Location Aware browsing is enabled. (default)
    False: The feature is disabled which means that you won't get prompts on websites using it.



media.video_stats.enabled

Provides web applications with information about video playback statistics such as the framerate.

    True: Web applications can access statistics (default).
    False: Statistics cannot be accessed.



network.cookie.lifetimePolicy set to 2

This defines when cookies expire in Firefox.

    0: The originated server sets the cookie lifetime. (default)
    1: Firefox prompts the user (unless network.cookie.alwaysAcceptSessionCookies is set to true).
    2: Cookie expires at the end of the session.




network.dnsCacheEntries set to 0

Defines how many entries Firefox will keep in the browser's DNS cache.

    400: the default number of cached DNS entries.



 
network.http.referer.XOriginPolicy set to 0

Defines when to set the referrer (the page a visit originated from).

    0: Never send it.
    1: only send if the base domain matches.
    2: only send if hosts match.


network.http.sendRefererHeader

Controls when to send the referer header and document.referrer is set.

    0: Never send the Referer header or set document.referrer.
    1: Send it after clicking on links.
    2. Send if after clicking on links or loading an image (default).



network.http.sendSecureXSiteReferrer

Defines whether a Referer header is sent when you are navigating from one secure site to another.

    True: The Referer header is added to connections (default).
    False: The Referer header is not added.


network.http.use-cache

Defines whether Firefox caches http requests.

    True: Enables caching in Firefox. (default)
    False: Disables the caching of http requests.




network.seer.enabled 

A component of Firefox's Necko Predictive Network Actions feature that improves page load time by performing overhead for connections before the connections are actually needed.

    True: The feature is enabled.
    False: Seer is disabled. 


plugin.scan.plid.all

Scans the Windows Registry key for plugin references. If found, adds them to Firefox.

    True: Will scan the Registry.
    False: Will not scan.


plugin.state.java

The default state of the Java plugin.

    0: turns off the Java plugin in Firefox.
    1: sets the Java plugin to ask to activate.
    2: enables the Java plugin.


```

**Comment by samuraikidXDA** [comment]
Can i ask you why invalid ? those are privacy issues i mentioned

**Comment by rusty-snake** [comment]
IDK why it was marked as invalid, but ...

These prefs are in the user.js:
- browser.cache.offline.enable
- browser.cache.memory.enable (commented)
- beacon.enabled
- browser.fixup.alternate.enabled
- browser.safebrowsing.malware.enabled (commented)
- browser.send_pings (enforce default)
- dom.battery.enabled (commented; [NOTE] From FF52+ Battery Status API is only available in - chrome/privileged code) 
- dom.event.clipboardevents.enabled (commented)
- dom.event.contextmenu.enabled (commented)
- dom.storage.enabled (commented)
- extensions.getAddons.cache.enabled (commented)
- geo.enabled (commented)
- media.video_stats.enabled (RFP Alt)
- network.cookie.lifetimePolicy (commented)
- network.http.sendRefererHeader (commented)

This pref is part of the user.js but with other value (0 is the default value, it has no benefit adding it as default):
- network.http.referer.XOriginPolicy

These prefs are missing on about:config, are you sure they still exist?
- network.http.sendSecureXSiteReferrer
- network.http.use-cache
- network.seer.enabled
- browser.safebrowsing.enabled
- plugin.state.java

Where's the privacy issue?
- network.dnsCacheEntries

Heartbeat is disable by 0503:
- browser.selfsupport.url

Is missing on about:config, but I'm on linux. However firefox' sets `plugin.default.state=1` (1=ask) by default.
- plugin.scan.plid.all

**Comment by samuraikidXDA** [comment]
all the above configurations i wrote i needed to manually add them after apply the .js file via updater.bat on win7 64x

**Comment by rusty-snake** [comment]
> all the above configurations i wrote i needed to manually edit them after apply the .js file via updater.bat on win7 64x 

Did you read [this](https://github.com/arkenfox/user.js/wiki/1.3-Implementation)?

If a pref is commented, it has a reason. `geo.enabled` for example is easy to fingerprint and firefox will always ask you, therefore it does not leak your location.

> yes they exist at least on windows 7 last ff version

Nope, they don't. I searched searchfox and `browser.safebrowsing.enabled` was the only one with a single match. In a changelog where it says that it was removed.

> network.dnsCacheEntries: Default 400 it can be safely be turn to 0

That's no argument. Just because something can be changes "safely", it's no reason to change it.

And I don't think it can be changesd "safely" as disabling the dns-cache will slow down browsing and make more DNS-request I guess.

**Comment by samuraikidXDA** [comment]
why would i lie on something i use and want to improve ?
![print](https://user-images.githubusercontent.com/46766062/100484433-4bfda680-30f4-11eb-8474-e6ae505c6545.png)

**Comment by rusty-snake** [comment]
No, i don't think they lie with intent, if at all, it is out of lack of knowledge, mistakes or mixing two different thinks.

But the following prefs are not in about:config or searchfox. `browser.cache.memory.enable` is indeed in the user.js and on about:config.
- network.http.sendSecureXSiteReferrer
- network.http.use-cache
- network.seer.enabled
- browser.safebrowsing.enabled
- plugin.state.java

> Also i don't see any loos of performance/speed opening websites

This will be a very small performance loose, so you would need to measure. If you have a fast internet connection or windows/your router has it's own cache it will be even faster (except you use DoH).

**Comment by samuraikidXDA** [comment]
![1](https://user-images.githubusercontent.com/46766062/100488249-085f6880-3105-11eb-83b1-651a9c573ddb.png)
![2](https://user-images.githubusercontent.com/46766062/100488252-08f7ff00-3105-11eb-850f-060b3e892d86.png)
![3](https://user-images.githubusercontent.com/46766062/100488254-09909580-3105-11eb-93a4-22f522bc17d6.png)
![4](https://user-images.githubusercontent.com/46766062/100488255-09909580-3105-11eb-85f7-cf47c9738bdd.png)

the other ones i wrote exist too

**Comment by Thorin-Oakenpants** [comment]
So let's just take one of your suggestions: `plugin.state.java`
- [1461243](https://bugzilla.mozilla.org/show_bug.cgi?id=1461243) - Part 5 -> [code changes](https://hg.mozilla.org/mozilla-central/rev/0124ef776161461243) .. this was in FF62 which was released to stable in Sept 2018, over two years ago

Just because something is user modified and persists in prefs.js, does not mean it exists
![prefs](https://user-images.githubusercontent.com/16656956/100492772-79b01300-3127-11eb-95eb-b5ca4129fbfc.png)

The bin icon is telling you something: either it's a "hidden" pref, or it doesn't exist. Compare those to the "reset" icon for `browser.cache.memory.enable` in your image

**Comment by Thorin-Oakenpants** [comment]
> Hi there ! Before all thanks for your work !
> Here are some additions i notice your script didn't add on my firefox
> 
> ```
> beacon.enabled
> 
> Sends data to servers when leaving pages.
> 
>     True: Feature is enabled and web apps can make use of it (default).
>     False: Disables the feature.
> ```

I wasn't going to say anything more, but then I noticed that you can't every represent OUR own data correctly: beacon.enabled is actively (i.e not commented out) disabled

https://github.com/arkenfox/user.js/blob/fa85c9da5b357726e6f35a138d6b96b977655012/user.js#L1131-L1133

And since I'm replying ... to answer your question ... I marked this as invalid for several reasons:
- you clearly didn't read the instructions
- you don't seem to grasp that this is a TEMPLATE (what might suit you doesn't suit everyone)
- almost all your information is outdated / just plain incorrect
- I dislike large lists being dumped at me (not that your list is that big, but I've had others in the past throw hundreds at me: I'm not a robot here to debug everyone's crap) <-- this is an INSTANT close as INVALID. If you have a problem with a pref, open an issue for that pref

I'm sorry rusty spent all that time checking - he deserves a fucking medal. When I saw you list things that are already covered I just hit the button, and even without checking I knew it was all immaterial, already covered, or deprecated (because I've been at this since before Jesus)

But go ahead and disable geo and make yourself more unique ... etc ... instead of listening to the answers rusty gave you. Even after he pointed you to the wiki page, you still didn't read and understand it

**Comment by samuraikidXDA** [comment]
i don't know if you are trolling or what ? 
Again, all i wrote are settings i manually had to edit to make them disable after running the script on win7 64x.
Do you think i liked copy paste them one by one to here ?

I know script was well apply because it resized my browser window, search don't work on main bar etc etc 
now what i wrote above the script simple didn't do anything on those settings now you can accept it or reject just don't try make someone look dumb i'm reporting those if they are on script something on the script isn't apply them

**Comment by Thorin-Oakenpants** [comment]
trolling? I'm the repo owner...

> I know script was well apply because

Who said anything about the script not being applied? Do you not understand user modified vs default settings? If only you had read the wiki... *sigh*

> all i wrote are settings i manually had to edit to make them disable after running the script

So you still haven't read the bare minimum, have you? It's a template. Some items are COMMENTED OUT, and for good reason (either to educate people NOT to use them, or because they're already covered by other means (e.g. geo, appcache), or because they don't really do much (context menu can be bypassed by using your shift key, and disabling it on all sites for all users just causes usability problems), or they do nothing (battery), or they're edge cases but may suit someone's threat model: and the reason is/should-be supplied - look at all the ⭐ s below

here's what rusty said (emoji emphasis mine, edits marked with ‼️ also mine)
> These prefs are in the user.js:
> - browser.cache.offline.enable
> - browser.cache.memory.enable (⭐ commented)
> - beacon.enabled ‼️ it is actively set by the user.js as false, so this claim is wrong
> - browser.fixup.alternate.enabled ‼️ it is actively set by the user.js as false, but I don't know what the fuck you're asking about, you seem to think that false is bad? IDK, you never said
> - browser.safebrowsing.malware.enabled (⭐ commented) 
> - browser.send_pings (enforce default) ‼️ it is actively set by the user.js as false, so this claim is wrong
> - dom.battery.enabled (⭐ commented; [NOTE] From FF52+ Battery Status API is only available in - chrome/privileged code) 
> - dom.event.clipboardevents.enabled (⭐ commented)
> - dom.event.contextmenu.enabled (⭐ commented)
> - dom.storage.enabled (⭐ commented)
> - extensions.getAddons.cache.enabled (⭐ commented)
> - geo.enabled (⭐ commented)
> - media.video_stats.enabled (⭐ RFP Alt)
> - network.cookie.lifetimePolicy (⭐ commented)
> - network.http.sendRefererHeader (⭐ commented)

> you can accept it or reject just don't try make someone look dumb i'm reporting those if they are on script something on the script isn't apply them

Why did you not read the readme in the user.js at the top, on this repo, or read the wiki pages? **What do you not understand about commented out prefs?** Why did you not read the comments for them? Why are you claiming the user.js doesn't disable `beacon.enabled` and `browser.send_pings` when it does?

You didn't even bother to read descriptions for anything, such as `browser.cache.offline.enable` which says
https://github.com/arkenfox/user.js/blob/fa85c9da5b357726e6f35a138d6b96b977655012/user.js#L1289-L1292

You see, appCache is already disabled, but your fingerprint is much harder to distinguish. But go ahead, disable the API and be more fingerprintable, etc.... you know, like don't LISTEN

I'm not trying to make anyone look like anything, you're doing it to yourself by continuing to insist on your incorrect statements. And ... for the record, I REJECTED everything when I closed this as invalid.
