### ISSUE TITLE
Slack login with Google breaks

### ISSUE THREAD

**Issue by rjshrjndrn** [arkenfox/user.js#1073]
Not able to sign in because popup is getting closed. I tried editing 
```
/* 2210: block popup windows
 * [SETTING] Privacy & Security>Permissions>Block pop-up windows ***/
user_pref("dom.disable_open_during_load", false);
```
but in vain. Any direction will be appreciated. 
Thanks
![image](https://user-images.githubusercontent.com/2563385/102002849-87a18e80-3cf8-11eb-9c7e-1aed70470da1.png)

**Comment by Thorin-Oakenpants** [comment]
try
```
/* 4001: enable First Party Isolation [FF51+]
 * [SETUP-WEB] May break cross-domain logins and site functionality until perfected
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1260931,1299996 ***/
user_pref("privacy.firstparty.isolate", true);
```

**Comment by rjshrjndrn** [comment]
@Thorin-Oakenpants By default, it was `true`, and I changed it to `false`. But the same effect.

**Comment by Thorin-Oakenpants** [comment]
I don't have a slack account or a google account (well I do but I'm not going to use it), so not sure if I can troubleshoot

- can you login with a new profile? I would assume so, but you never know
- are you on Nightly (because they're using dFPI), so it may be a bug
- have you tried disabling all your extensions to make sure it's the user.js causing it
- do you need to allow a third party cookie (which is why I asked about the ETP and the shield icon)?
- are there any console errors, messages

[Troubleshooting](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting)

**Comment by Thorin-Oakenpants** [comment]
wait a second... if I go to slack to sign in .. and I click `continue with google`, it opens a new tab ... what is meant to happen next? where is it breaking down? I mean you then enter your email and then password and then what? What should happen? What does happen?

Also did this just start happening, or is have you only just started using the user.js and/or slack+google-signin?

**Comment by rjshrjndrn** [comment]
> wait a second... if I go to slack to sign in .. and I click `continue with google`, it opens a new tab ... what is meant to happen next?
 
Yes it opens a new google signin tab, where we will enter our creds and authenticate. 

> where is it breaking down? I mean you then enter your email and then password and then what? What should happen? What does happen?

After authentication, that tab closes, and then from the original tab(the slack one) it'll just rediect to slack app.

> Also did this just start happening, or is have you only just started using the user.js and/or slack+google-signin?

I tried the same flow with brave, and it's working fine. Yeah I just started to use `user.js`

**Comment by Thorin-Oakenpants** [comment]
I'm still confused. I wanted to know where it breaks in Firefox. I need full STR with what happens and what should happen. I also can't really troubleshoot it because I can't test signing in

STR
- new Firefox profile with no extensions and just the arkenfox user.js
- go to slack's sign in page
- click `continue with google`, this opens a new TAB
- on the new tab for google credentials, enter your email or name + click `next`, then enter your password, click `continue`
- the tab will close and you will be back on the slack tab

EXPECTED
- slack then signs you in and you are redirected to your slack landing page or whatever

WHAT ACTUALLY HAPPENED
- the slack sign in says `popup was closed before logging in`

So is the above 100% correct? Are you using two-factor authentication (but I don't think that's the issue here)?

If it is, then try troubleshooting it as per the wiki - I linked it above. Try half the user.js in a new profile. Then add more of it and test again - etc. A binary testing method will quickly narrow down the problem pref

**Comment by rjshrjndrn** [comment]
will try that out. Thanks :)

**Comment by earthlng** [comment]
hi

try resetting `browser.link.open_newwindow.restriction`

**Comment by rjshrjndrn** [comment]
![image](https://user-images.githubusercontent.com/2563385/102443831-9604e880-401f-11eb-8d41-94f8f1a5d038.png)

@earthlng I commented out the above string in config, and still got same issue.

This is my override.js

```js
// USER CONFIGS //

user_pref("dom.allow_cut_copy", true); // 2400
/* google meet */
user_pref("media.getusermedia.screensharing.enabled", true); // 2022
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001
user_pref("dom.webaudio.enabled", true); // 2510
user_pref("media.autoplay.blocking_policy", 0); // 2031

// URL search
user_pref("keyword.enabled", true); //0801
user_pref("browser.search.suggest.enabled", true); //0807
user_pref("browser.urlbar.suggest.searches", true); //0807
user_pref("browser.taskbar.lists.enabled", false); //0870
user_pref("browser.taskbar.lists.frequent.enabled", false); //0870
user_pref("browser.taskbar.lists.recent.enabled", false); //0870
user_pref("browser.taskbar.lists.tasks.enabled", false); //0870
user_pref("privacy.clearOnShutdown.history", false); // 2803

// SSO login
// user_pref("dom.popup_allowed_events", "change click dblclick auxclick mouseup pointerup notificationclick reset submit touchend contextmenu"); //2212

```
cc @Thorin-Oakenpants

**Comment by Thorin-Oakenpants** [comment]
> I commented out the above string in config, and still got same issue.

commenting it out doesn't change it. You need to reset it in about:config and often a restart is good practice (or at least use a new tab and close any others of the site being tested), or add it to your overrides and restart

**Comment by rjshrjndrn** [comment]
I always, change the config and restart firefox. I Think that's enough right ?

**Comment by crssi** [comment]
> I always, change the config

Whatever is in user.js file will get set when you start Firefox.
So, If you do comment out in user.js, the you need to reset also the same in about:config.

**Comment by rjshrjndrn** [comment]
oh okay. Lemme try that @crssi

**Comment by Thorin-Oakenpants** [comment]
[Wiki: how to reset a preference](https://github.com/arkenfox/user.js/wiki/1.1-Overview#small_orange_diamond-resetting-preferences)

**Comment by Thorin-Oakenpants** [comment]
anything to report back yet @rjshrjndrn ?

**Comment by rjshrjndrn** [comment]
sorry @Thorin-Oakenpants I didn't pursue this issue, as my logged in worked with other browser. I'll check this issue later once I'm free a bit. do you mind keep this open ? or shall we close this one, and add comments as I work on this issue ?

**Comment by Thorin-Oakenpants** [comment]
no worries .. leave it open. I'm interested to know what the issue is

**Comment by crssi** [comment]
Deactivate (comment-out in user.js) and reset (in about:config) the following to default:
```
security.cert_pinning.enforcement_level
network.cookie.cookieBehavior
privacy.firstparty.isolate
```

Maybe the `security.cert_pinning.enforcement_level` has something to do with ESET, but if I would like login on slack to work here, I need to reset all those.
Also note with `network.cookie.cookieBehavior`... it might work with other settings, but it work as default and definitely doesn't work with value of `1`.

Cheers

**Comment by crssi** [comment]
@rjshrjndrn can you confirm upper solution?
If so, then someone should report to mozilla the FPI breakage.

**Comment by Thorin-Oakenpants** [comment]
Steps to try: Firefox stable or higher
- Create a new profile, no extensions, no user.js, confirm you can log into Slack using a google account - log out
- Clear everything for all time: Ctrl-Shift-Del
- Add user.js (as it is right now today here on github)
- Restart
- Confirm you can't log into Slack

Now ADD this to the user.js at the end
```js
user_pref("network.cookie.cookieBehavior", 4);
```

Restart, retest: note if any cookies or google stuff is blocked in the blue icon shield in the urlbar

If it's still broken, ADD this to the user.js at the end
```js
user_pref("privacy.firstparty.isolate", false);
```

Restart, retest

If it's still broken, ADD this to the user.js at the end
```js
user_pref("security.cert_pinning.enforcement_level", 1);
```

Restart, retest

If it's still broken, ADD this to the user.js at the end
```js
user_pref("browser.link.open_newwindow.restriction", 2);
```

I think the issue is as crssi said, you need the third party cookie. After that FPI can break *some* cross-domain logins, and after that IDK because I don't have any cross-domain logins.

Note: If you have to allow 3rd party cookies AND you disable FPI, then you lose a lot of tracking protection: a cookie permission is not just for cookies: it controls service workers and other other persistent local storage. That on it's own is OK if you clear everything on close AND you have FPI. But without FPI, 3rd parties will run amok (except for those caught by Enhanced Tracking Protection). So I suggest you use a secondary browser (e.g install Nightly or Beta) and use that just for Slack and other problem sites (and add the user.js with appropriate tweaks)

**Comment by heilrichst** [comment]
I have similar sturuggle. Googles "Sign in with Google" is not properly working, As it doesnt create the popup window, but instead leads to a whithe accounts.google site. Arkenfox is set up by default exept 1601 (setting about cross origin referers) is set to 0. Mabey sb gets the issue an can help.

**Comment by Thorin-Oakenpants** [comment]
@heilrichst - open a new issue, this one is fucking old and a lot has changed

> Mabey sb gets the issue an can help

i do not know what this word salad means - follow the issue instructions and make sure you tried all the steps it links to
