### ISSUE TITLE
Full screen video reporting exact screen resolution and doubts about PIP

### ISSUE THREAD

**Issue by rawlife56** [arkenfox/user.js#1078]
Thank you for this great work.
TZP reports the exact screen resolution in the full screen test with the clean installation of Firefox/user.js
In TB, during the same test it reports the RFP dimensions 95% of the time but occasionally the actual screen dimensions leak in 2 out of 10 tests. 
This issue is still open [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1450401).

Should we just abandon watching full screen videos until this is fixed by mozilla ? may be it isn't a big distinguishing factor for common screen resolutions like 1080, 768, 2160 ? 

At the same time, can you also throw some light on the new PIP(Picture in Picture) mode in FF ? It's quickly becoming one of my favorite feature to watch videos while working. Are their any downsides in using or resizing it ? What are the things we can expect to leak while using it ?

**Comment by Thorin-Oakenpants** [comment]
> Should we just abandon watching full screen videos

No - watch em how you want to. Watching FS videos on a couple of sites is no big deal: other sites will never get that info. I don't see this being fixed by Moz as it's very low priority (and would take a bit of engineering). The entropy is (exclude android which doesn't have screen protections) e.g. 8 common desktop resolutions = 99% of users and then there a very long tail.

PIP: I haven't used it. I don't think there's any fingerprinting that is useful/stable in there re sizes. Don't videos change to the correct aspect ratio, etc. Any new API nowadays is (almost) always given some sort of fingerprinting/privacy check: either at the standards level, or when implemented

**Comment by rusty-snake** [comment]
FWIW: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40147

**Comment by Thorin-Oakenpants** [comment]
> In TB, during the same test it reports the RFP dimensions 95% of the time but occasionally the actual screen dimensions leak in 2 out of 10 tests

This is the FS test? There's been a few weird things going on with TB since they changed the LBing position and added a border.
 
Someone else also reported this, and there's a number of tor tickets (they all get a bit messy with different wording and STR from multiple people, and so many variables that it's difficult to know wtf is going on) .. but I think this is something to do with tiling managers

Currently the FS test just grabs the values once (from an event listener: afaik that doesn't trigger until any FS animation finishes). The new window (or tab) test grabs values as soon as possible and continues to do so until it errors out, to create a history of size stepping.

I applied a history of changes to FS once, and the problem persisted, so I reverted it and decided it wasn't worth chasing. But if you're up to it, open an issue at TZP and I'll see what I can do for you to test: I'm probably slightly confused over what I did in the past, since the old TZP repo and issues have been blown away

**Comment by rawlife56** [comment]
> he entropy is (exclude android which doesn't have screen protections) e.g. 8 common desktop resolutions = 99% of users and then there a very long tail.

Thanks, that's what I thought considering TB also didn't care to hide it reliably. 

> PIP:  Don't videos change to the correct aspect ratio, etc. Any new API nowadays is (almost) always given some sort of fingerprinting/privacy check: either at the standards level, or when implemented

Yes, I guess it does resize to correct aspect ratio but was looking forward for some proper analysis before I use it on every website. Lets see what they'll finalize before jumping all in. 

>This is the FS test? There's been a few weird things going on with TB since they changed the LBing position and added a border (edit: but that shouldn't affect FS, but who knows).

Yes, that's the FS test. It'll show the correct display FS resolution when clicked on it for the first time but later it just bounces between the window resolution and true FS res in TB. It works fine in FF.

>But if you're up to it, open an issue at TZP and I'll see what I can do for you to test:

Never mind at this point as it isn't a priority and TB isn't trying to hide it. Why waste time!

**Comment by Thorin-Oakenpants** [comment]
> but later it just bounces between the window resolution and true FS res in TB. It works fine in FF.

OK. Sounds like a timing issue (or my code needs more logic). And I *think* sysrqb *may* have done something for android (I swear he did something based on an email I sent him) that he applied to all builds

At the end of the day, because FS is user-activated, it's not exactly a constant FPing vector [1]: so if it works in FF but gets fucked up in TB, then so be it: good on TB. Maybe down the track I'll get into it more: because it's not a real solution if I can bypass it: it's just super low priority

[1] sites can easily trick you into going FS but then you'd never visit the site again
