### ISSUE TITLE
Redirect tracking protection might not work properly

### ISSUE THREAD

**Issue by etotopuc** [arkenfox/user.js#1089]
Redirect tracking protection is enabled via `privacy.purge_trackers.enabled = true` by default. However, according to this hotfix: https://searchfox.org/mozilla-central/source/toolkit/components/antitracking/PurgeTrackerService.jsm#298 it seems to only work if `privacy.clearOnShutdown.history` and `privacy.clearOnShutdown.siteSettings` are set to `false.` Both settings that are set to `true` in user.js though.

Are there any considerations in this regard? Does deleting the history and site settings make more sense to avoid tracking and redirect tracking should be prevented via an addon?

**Comment by rusty-snake** [comment]
The user.js also sets

```javascript
user_pref("privacy.sanitize.sanitizeOnShutdown", true); // 2802
user_pref("privacy.clearOnShutdown.cookies", true); // 2803
user_pref("privacy.cpd.cookies", true); // 2804
```

Cookies (redirect or not) are deleted if you restart or clear-manually.

In addition you can use an add-on like ClearURLs, Request Control or Skip Redirect to skip redirect-trackers. This has the advantage that the server isn't contacted so it has no "IP 1.2.3.4 has clicked a link on example.com to visit example2.com".

Alternative you could use TC with global isolation.

**Comment by Thorin-Oakenpants** [comment]
`privacy.clearOnShutdown.siteSettings` has NEVER ever been set to true

user.js today
https://github.com/arkenfox/user.js/blob/27dd6aa62d1d73e9cdb0b751a7d4d4acdb893b75/user.js#L1320

user.js Feb 17 2017
https://github.com/arkenfox/user.js/blob/e97a1ceb5beb707d3a05252bc74a5e36530b3d9e/user.js#L1305

**Comment by Thorin-Oakenpants** [comment]
`privacy.purge_trackers.enabled`
- Added `false` in FF75+ [1599262](https://bugzilla.mozilla.org/show_bug.cgi?id=1599262)
- Read this [here](https://blog.mozilla.org/security/2020/08/04/firefox-79-includes-protections-against-redirect-tracking/) on what redirect tracking is
   - they talk about FF79
   - "Once every 24 hours ETP 2.0 will completely clear out any cookies and site data stored by known trackers. This prevents redirect trackers from being able to build a long-term profile of your activity."
- Flipped `true` in stable release in FF84+ [1675596](https://bugzilla.mozilla.org/show_bug.cgi?id=1675596)
- hotfix ... [1672394](https://bugzilla.mozilla.org/show_bug.cgi?id=1672394) .i.e don't purge if X or Y

---

So the question is, what exactly is being purged ... what exactly are you not already protected against. Answer those and you then you can probably close this issue

The first answer is (emphasis mine)
- This only applies to known trackers ... **_with a 45 day exception for any trackers that you’ve interacted with directly_**
- hence ETP requires history (and site permissions) in order to determine interaction
- clearly, sanitizing history means there are no exceptions, hence everything gets purged = excellent!!! 👍 FukYeah™

The user.js is set up to sanitize all site data on close: i.e web data, not site exceptions or passwords

However, users can tweak shit. Some people want to keep some cookies (I do) and bulk sanitize cookies on close doesn't allow that
- note: "cookies" = cookies only (so users auto-login etc). localStorage, service worker cache and IDB etc are covered by a different sanitizing pref
- example A: user keeps nothing: default user.js = sweet AF
- example B: user keeps history but not cookies: now purging happens (minus exceptions) - except the user.js already sanitizes all web data
- example C: user keeps cookies but not history: purging does not happen
- example D: user keeps cookies and history: purging works (minus exceptions) = default setup

In A+B the user is fine
In C + D the user has bigger problems keeping all cookies by default, let alone redirect tracking ones.

I don't know the answer: I actually don't recommend cookie cleaner extensions because they often leave orphaned web data lying around. TC though doesn't. But I don't know if these extensions handle cleaning up a website cookie/data used as a redirect/bouncy-bouncy

**Comment by Thorin-Oakenpants** [comment]
PS: if anyone cares about my superior solution: I block all cookies by default. A cookie permission also controls localStorage, sessionStorage, IDB, shared workers, service workers (and hence sw cache). Then I allow site exceptions as Allow or Allow for Session to a very tiny handful of sites. That's it.

Another option may be to set all cookies to be session only (in effect `Allow for Session`, but use site exceptions to change some login sites to `Allow` - but there are some weird things going on there. That's the `network.cookie.lifetimePolicy` pref but I think they're going to remove it .. lemme look that up

https://bugzilla.mozilla.org/show_bug.cgi?id=1681701
https://bugzilla.mozilla.org/show_bug.cgi?id=1681493
https://bugzilla.mozilla.org/show_bug.cgi?id=1681498

**Comment by Thorin-Oakenpants** [comment]
^^ https://bugzilla.mozilla.org/show_bug.cgi?id=1681493#c1

> Can you make sanitize at shutdown respect ALLOW exceptions?

^^ fucking this a billion times ove

**Comment by etotopuc** [comment]
Thanks for that extensive explanation! I wasn’t aware, that `privacy.purge_trackers.enabled` only or mainly deals with cookies.

**Comment by Thorin-Oakenpants** [comment]
> Thanks for that extensive explanation! I wasn’t aware, that `privacy.purge_trackers.enabled` only or mainly deals with cookies.

purging quoted from the link above (emhasis mine)
> Once every 24 hours ETP 2.0 will completely clear out any cookies **_and site data_** stored by known trackers

When I said cookies = cookies only, that in relation to the sanitizing prefs, talking about tweaking the user.js

**Comment by Thorin-Oakenpants** [comment]
FYI: fixed in FF85 [1675018](https://bugzilla.mozilla.org/show_bug.cgi?id=1675018)

**Comment by Thorin-Oakenpants** [comment]
Hah ... ETP's "tracking content" is only enabled in PB mode windows by default (and PB mode stuff is memory only)

Note: the user.js makes sure to not start in pb mode, and it does not set ETP's tracking protection on in all windows - maybe we should

**Comment by crssi** [comment]
> the user.js makes sure to not start in pb mode

How?
Doesn't need the `browser.privatebrowsing.autostart` be `false` to prevent PB mode?

**Comment by Thorin-Oakenpants** [comment]
yeah, sorry. We don't *enforce* it, it's commented out .. my bad
