### ISSUE TITLE
identifiers

### ISSUE THREAD

**Issue by privacyonly** [arkenfox/user.js#1102]
First is mixed content image , https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html

user_pref("security.mixed_content.block_display_content", true);

for us it is no, But for the rest of firefox user it is yes

Second is this
https://brax.me/geo/

user_pref("dom.webaudio.enabled", false);

It says, audio = not available, while for the rest it is reported as audio = 35.74996031448245, I am not sure if this will be the same with all OS, I am using android and it didn't change even if I changed my volume

**Comment by Thorin-Oakenpants** [comment]
FPing is a two edged sword. When you differ from the other FF users (default) and scripts measure that, it makes you stand out. If you do nothing, you will be in a very tiny group if not unique.

FPing scripts first need to get through: ETP's fingerprinters and uBO (in various configs) helps block a lot of that. Second, the scripts would need to be checking those (e.g. mixed passive). Third, the script would need to widely distributed (not all scripts are the same: e.g the canvas test used by ScriptA from EvilCompanyX is not the same as the one used in ScriptB from AssholesInc) - the same goes for the metrics collected. There are far more easier and higher entropy FPing metrics than pissing around with mixed passive (which would also probably slow the script down)

So in the case of mixed passive content: I doubt anyone is bothering to use it for tracking in fingerprints: and HTTPS-Only mode is catching on. The choice is a risk assessment
- allow mixed passive and let snoopers/ISP see in plain text
- block mixed passive and tighten privacy (may be some breakage = tradeoff: uber tiny hypothetical FPing metric with two values only)

The tradeoff is worth it these days. HTTPS sites with HTTP images in this day and age, can get stuffed IMO

---------

Audio: The entropy is from floating points in audio math. It is **_NOT_** , and I can't stress this enough, hardware dependent. The hardware is never touched. The limited (seven?) `Math.` functions used in the web audio API use a narrow range of values.

Enable web audio and do the test. I have seen two Linux, three Androids, a Mac, and four Windows machines all return `35.7383295930922`. There will be some entropy, but until someone actually does a real world test of one result for like 5000 devices (like a shield study), then we don't really know. My gut feeling is that audio entropy is actually pretty low, with maybe android causing the most buckets (it does in other math entropy tests by a very long shot)

Again, this comes down to a risk assessment
- FPing scripts love to include an audio test (which I think is overhyped, but it *is* a legit test with some entropy)
- assuming a script gets thru and FPs you .. you're probably IMO, right now, more likely to be in a bigger set of users with it enabled than disabled: almost no-one bothers to fiddle with about:config let alone disable webaudio

We choose to disable it, because we already know that we're in a small set of RFP users on FF with some distinct changes .. IF a FPing script gets thru (out audience should be using uBO etc) - and until someone does a real world study to determine the actual REAL entropy, or Mozilla patch the entropy (there is a known solution to fix this), then it's not worth giving the bastards anything. I'm kind of 50/50 on this one, given what I now know about the API vs the nothing I knew 5 years ago
