### ISSUE TITLE
Q: browser.display.use_document_fonts vs. CSS

### ISSUE THREAD

**Issue by atomGit** [arkenfox/user.js#1105]
for fingerprinting/RFP reasons, it's not recommended to set `browser.display.use_document_fonts` to '0'

i can't stand sites that specify stupid/tiny/ugly fonts, so i've been disabling this forever ( 0 )

regarding fingerprinting, what happens when you inject CSS? assuming JS is enabled, can the site know?

would it be better to use the web specified fonts and then force override with CSS?

**Comment by Thorin-Oakenpants** [comment]
`document_fonts` refers to local fonts installed (or bundled with your browser)
`web fonts` is confusing and I read that as downloadable fonts, which have nothing to do with fingerprinting

if you modify the web content, then yes, it can be detected: but given a lot of scripts are auto-blocked (ETP/uBO), and that this is probably not something that scripts bother to check, then the risk is probably low .. but who knows

why don't you set your system scaling higher? Or if it's just web pages, then try `layout.css.devPixelsPerPx` at e.g. `1.1` or something : this will not affect RFP as far as I know

There is also options UI preference .. `Zoom default level`, and `only zoom text` as optional. I am not sure on the FP here (yes it affects some values that are probably not in scripts) but it is pretty hard (and slowish) for sites to correctly detect your zoom level in gecko

Of course that is assuming the bulk of sites piss you off, otherwise you will have the opposite issue triggering you ... i can't stand sites that specify stupid/GIANT/ugly fonts
