### ISSUE TITLE
FB: some video's not playing (error)

### ISSUE THREAD

**Issue by gitthehubs** [arkenfox/user.js#1108]
Hi,

I noticed that on facebook that some video's were not playing and also a banner of a fb page(also video) is also not playing, they all generate an error that the video could not be played. I narrowed it down to the following setting:
/* 1603: CROSS ORIGIN: control when to send a referer
/* 0=always (default), 1=only if base domains match, 2=only if hosts match
/* [SETUP-WEB] Known to cause issues with older modems/routers and some sites e.g vimeo, icloud ***/
user_pref("network.http.referer.XOriginPolicy", 2);

When I changed this setting to 0 (default) it works again, 1 isn't working either.

A fb page example:
https://www.facebook.com/upnetworknl
The page banner(or how is it called) and if you scroll down some video's are not working when the XOriginPolicy setting is 2 or 1.

I know it is already mentioned in the comment that the setting can break some sites or functionality, but I thought of letting you know. Maybe the setting need some reconsideration?

Keep up the work!

**Comment by Thorin-Oakenpants** [comment]
> 1 isn't working either ... Maybe the setting need some reconsideration

https://github.com/arkenfox/user.js/commit/8c9d0bbe7280307ff172b1a9db244344cabd424a - we changed it from 1 to 2 .. and it's been active at 1 (or 2) since mar 4th 2017, just after we arrived here

feb 2017
https://github.com/arkenfox/user.js/blob/e97a1ceb5beb707d3a05252bc74a5e36530b3d9e/user.js#L709-L711

mar 4th 2017
https://github.com/arkenfox/user.js/blob/b48b4935ec3c197e539e3d0ca0e8c8ee7a7b8316/user.js#L673-L675

---

So I don't think we need to revisit the setting. I would rather something broke for some users and they then got Smart Referer by blocking all referers and then allowlisting the likes of facebook

**Comment by Thorin-Oakenpants** [comment]
@gitthehubs : what is the error message: is it in the console, or on facebook. Also, what is the source of the videos: i.e is it a FB problem or the video source problem (sorry if I don't now much about FB videos: isn't it all self hosted?)

re-opening: pending reply, and maybe I'll add FB videos to the setup web tag info

**Comment by gitthehubs** [comment]
@Thorin-Oakenpants 
The error is on the facebook page itself, not in the console. The video's come from fb's own cdn network, the (3rd-party) domain fbcdn.net.
The problem don't occure that often, not that I watch many video's on fb, but since I can use fb again with Firefox I noticed that now and then some video's would not play while chrome wasn't giving any problems. So this weekend I spend a little time on it to find the setting in the user.js. I don't really know why some video's give this problem, or why it depends on some referer information, while like 99,x% is playing perfect with no problems.

I added 2 screenshots so you can see for yourself.
![fb0001](https://user-images.githubusercontent.com/49681755/106466266-057d4d00-6493-11eb-8a21-ad63d3b4a427.jpg)
![fb0002](https://user-images.githubusercontent.com/49681755/106466280-0a420100-6493-11eb-87ad-d614b8f303a9.jpg)

**Comment by Thorin-Oakenpants** [comment]
thanks. so self hosted (on a 3rd party). FB isn't the only site, but I get it that it's a major one :) One reason a lot of sites do this is so images/videos aren't served willy-nilly free-for-all : https://en.wikipedia.org/wiki/Inline_linking .. I call it hotlinking

I'll ponder what I can add to the user.js for that pref

**Comment by iWARR** [comment]
I have made a quick tests proposed above and fb videos **work** for me with _arkenfox_ default value `2`.
`user_pref("network.http.referer.XOriginPolicy", 2);`
So (IMO) better continue your discoveries.

FIY: I have some issues with payment when a shop refers to banking (other) source. 
(I'm using much hardened presets than **arkenfox**).
I beleive this mostly relative to the installed addons / overall privacy setup or my be the "Temporary Containers" addon.
(No luck for me when putting all eggs into the same container).
But FF "Privacy mode" with uBO, PrivacyBager and without "TC" - **works** almost fine.

Reading this thread, I decide relax this pref to `1` back, because I think `1 = Only if base domains match` as same good as `2 = Only if hosts match`. On my opinion both values are safe, but with `1` I will have less breakage there and there. Will see.

**Comment by iWARR** [comment]
**NOTE:** fb console videos were not tested, because this annoing frame always hidden for me due to my own uBO restrictions.
But videos in the fb thread work.
(I dont' have account at fb and use only external links sometimes (rare)).

**Comment by gitthehubs** [comment]
@iWARR 
Maybe your quick test was too quick. :) You say you have no fb account, so there you have the problem. If I don't log in to fb and go to https://www.facebook.com/upnetworknl the page banner video is played, but when I log in to facebook the same video(and some other video's on that fb page) is not played anymore.
Another thing I noticed while testing is that you really need to do a proper page refresh with shift+refresh or a firefox restart before firefox will use a new value in the about:config.

In my tests I used a new fresh firefox 85.0 portable installation with no add-ons, no user.js or custom settings in the about:config, so a real default firefox installation. When I only change the network.http.referer.XOriginPolicy setting to 1 or 2 and log in on facebook and go to https://www.facebook.com/upnetworknl the video's will not play and show an error as seen in the screenshots. Please use this same method in testing if you want to reproduce this error.

**Comment by gitthehubs** [comment]
@Thorin-Oakenpants 
I understand it need some thinking whether you will leave to setting to 2 and make a comment in the user.js about it or change to value to 0 so it works and nobody have problems. Of course it is all fine with me, I'm only the messenger so you know about it. :) 

And I don't really know what the real life impact is, if you change the value back to default 0 how often is this a privacy concern?

**Comment by iWARR** [comment]
> Maybe your quick test was too quick. :)

No. My tests were correct (using restart).

FIY: Today I've switched to the new Mozilla's code for isolation (dFPI). The behavior of this tespage was not changed.
Probably switching to dFPI is too early for now, but I beleive it will be polished with time-flow and old FPI code will be retired some day.

> You say you have no fb account

Correct. But I don't have header banner FRAME at all when non-signed. Looks like a regular webpage. That's it.
I can easily launch and stop the videos represented inside the fb thread for testing.

**Comment by iWARR** [comment]
@gitthehubs 
The thing about my FF set-up is that I don't use RFP, but use FPI (now dFPI), and bunch of add-ons, plus I have _arkenfox_ section for non-RFP users enabled.
This way I can achieve better protection + less breakage + more granular control.

May be RFP is the case...

**Comment by gitthehubs** [comment]
@iWARR 
I don't wanna start a discussion if you're test was good or not, but I will quote again what i said to you before:

> You say you have no fb account, so there you have the problem. If I don't log in to fb and go to https://www.facebook.com/upnetworknl the page banner video is played, but when I log in to facebook the same video(and some other video's on that fb page) is not played anymore.

So the problem with your test is that you haven't test it with logging in to facebook and without that you will not be able to reproduce the problem.

Look, network.http.referer.XOriginPolicy=2 and it works:
![fb0003](https://user-images.githubusercontent.com/49681755/106599385-e2b16e00-6550-11eb-9032-48eaacf1cb99.jpg)

But when I log in on facebook it shows the error as in the screenshot in my previous comment.

If you want to reproduce the problem I am mentioning, you will need to create a facebook account, until then you're tests are of no use..sorry. :)

**Comment by Thorin-Oakenpants** [comment]
@gitthehubs don't sweat it man :) Thanks for the troubleshooting and info

@iWARR ... when doing tests, always use a vanilla profile with no changes to get a control test. Then add the suspected problem and retest to confirm. At this stage if you can't replicate the problem (because you have no FB account), then the "having a FB account" step is important. STR (steps to reproduce) are important :)

**Comment by Thorin-Oakenpants** [comment]
I don't have a FB account. Same as [here](https://github.com/arkenfox/user.js/issues/1108#issuecomment-771535167)

practically vanilla FF (nightly). One thing I have noticed is (and maybe because I am on nightly) there are issues just showing the banner video (also see those console errors about reading resources from `https://video.fakl1-3.fna.fbcdn.net/`). In order to get it to show, I click on videos in the left hand menu and then click the back button. Once the video is there in the banner slot, it fails to finish loading .. it just shows a "spinning" loading icon .. until I right click and select play. Play works fine.

So ignoring all those red herrings ... the video is served no issues with no FB login, with any value for xOriginPolicy
![FB](https://user-images.githubusercontent.com/16656956/106630932-2d90ad00-6574-11eb-8006-5f4fef1829cc.png)

**Comment by gitthehubs** [comment]
@Thorin-Oakenpants 
You're welcome.

I guess people can expect site breakage on all sites that are whitelisted in the smart referer add-on.
https://gitlab.com/smart-referrer/whitelist/-/blob/master/whitelist.txt

**Comment by Thorin-Oakenpants** [comment]
Since we hardened referers recently (from 1 to 2), and since it's a common breakage (with tell tale signs), I have added the following to the [wiki](https://github.com/arkenfox/user.js/wiki/1.3-Implementation)

---

:exclamation: ULTRA UBER IMPORTANT: Pay attention!

- snip snip snip
- We hardened cross origin referers (1603, 1604)
  * :star: This is going to cause common breakage where third party images and videos may not load
  * Change to suit and consider installing an extension

---

I will add something to the readme part of the user.js
