### ISSUE TITLE
users.js causing image breakage on some sites

### ISSUE THREAD

**Issue by kanyck** [arkenfox/user.js#1114]
FF shows some colored rectangles instead of images when user.js is in place, without  users.js the image is OK.

Example page: https://gitlab.com/teobigusgeekus/Accuweather_conky_script/-/blob/master/Accuweather_README_INFO/Acc_README.pdf

Tried to fiddle with settings that seem to be relevant with no success. Please help.

FF 78.7.1 esr
Gentoo Linux

**Comment by rusty-snake** [comment]
`privacy.resistFingerprinting`

**Comment by kanyck** [comment]
This is it. So I've to switch it off... Thanks!

**Comment by Thorin-Oakenpants** [comment]
@kanyck that pref (RFP) covers a **_lot_** of anti-FPing measures: and unfortunately, when you break web standards by blocking, lying, spoofing etc: there can be web compat and usability issues. Canvas is used a lot more now than three years ago when RFP started: so hopefully they might change it

When you see those patterned images, it's almost always going to be RFP's canvas protection. If it looks legit (as per that website is using a js pdf viewer to show the contents, then you can always allow a temporary (or permanent) site exception (there is a canvas icon in the urlbar)

And of course, the other option on that page was to download it to view it

![allow-canvas](https://user-images.githubusercontent.com/16656956/107735776-6826e200-6cf8-11eb-9182-9e9972e6e1b5.png)

So rather than throw the baby out with the bath water: you have options

**Comment by kanyck** [comment]
Thanks @Thorin-Oakenpants!
I did have question if I'm able to toggle it on a site basis, indeed. However I don't see such icon on my FF78, so I'm still unsure on how to achieve that. Of course, I'd prefer to have this option activated unless it causes breakage. 
BTW, what's your opinion on CanvasBlocker add-on? How good is this solution?

**Comment by rusty-snake** [comment]
Try to set the exception under Page Info -> Permissions.
Linux: Crtl+i
Windows: Alt, Tools -> Page Info

> BTW, what's your opinion on CanvasBlocker add-on? How good is this solution?

https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-extensions-maybe

**Comment by kanyck** [comment]
It works, however less convenient than just a button. Thanks again!
