### ISSUE TITLE
user.js causing issues with addons that require loggin

### ISSUE THREAD

**Issue by gabriel-coelho** [arkenfox/user.js#1115]
I use addons like [Notion Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/notion-web-clipper/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and the [Save to Notion](https://addons.mozilla.org/en-US/firefox/addon/save-to-notion/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).

Both require me to login to the [Notion website](notion.so), but though I can login successfully to the webpage, the addons do not seem to update, leaving me logged out. Does anyone know which lines I should overwrite to make this work?

**Comment by Thorin-Oakenpants** [comment]
since it requires a login, I cannot troubleshoot it for you
- https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting

First: are there are web console errors to do with the extension
Then you can try the usual suspects: look at `[SETUP` tags: such as below
If it's none of those: then you will need to troubleshoot: the best method is to do a binary search: see the wiki

Let us know how you get on

PS: looking at the comments on AMO, it seems as if the likeliest pref is FPI (others have complained it doesn't work with containers, which use the same logic/paths as FPI)
```js
/* 4001: enable First Party Isolation [FF51+]
 * [SETUP-WEB] May break cross-domain logins and site functionality until perfected
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1260931,1299996 ***/
user_pref("privacy.firstparty.isolate", true);
```

**Comment by crssi** [comment]
Interestingly it looks like the domain in question got on bad list... `https://github.com/nextdns/metadata/issues/578` 😉

**Comment by Thorin-Oakenpants** [comment]
@gabriel-coelho any updates?

**Comment by Thorin-Oakenpants** [comment]
closing. feel free to re-open if you get any more information
