### ISSUE TITLE
`user.js` Customization Interface

### ISSUE THREAD

**Issue by F1nx** [arkenfox/user.js#1132]
I think a lot of us who are on this repository believe that utilizing the browser is one of the most effective ways for casual users and experts alike. This is normally seen to be done through security/privacy extensions, as they're easy to install. However, I am afraid that the sophistication that goes into configuring `user.js` may deter users from trying it. So, it would be beneficial if we develop some kind of interface.

_At first, one of us may jump to the conclusion that if this is going to be made, it should be done through the terminal (similar to how npm initializes a `package.json` file); but let's not forget that if we want to reach out to the audience, we have to meet them half way, because some people may not even know about the/a command prompt._

My first proposal is that we start with HTML and build it into an application with a framework. If that fails, other languages are always an option, such as V, Python, and the C family. When it comes to the interface, the user is given the option to either use the shell/batch files to update the script or implement it into their browser. For first timers, they are shown choices to customize their own `user.js` based on their priorities and threat model (potentially accompanied by pictures).

**Edit: _It would actually be even more effective if we develop this as a browser extension!_**

Maybe this could be a separate project - maybe it could be a separate branch. Who knows? 
Nevertheless, I'd love to hear your thoughts on this enhancement.

**Comment by atomGit** [comment]
i think a lot of people would appreciate this, however to gain max exposure it would have to be (eventually) an add-on on AMO

it doesn't seem to make any sense to have a UI with 100+ options, therefore presets would have to be determined which adds a bit of complexity

lastly, i'm guessing (actually not because this was brought up b4) pants will not want anything to do with this so it would have to be a separate project, and preferably not a fork, rather just a UI i would think

**Comment by F1nx** [comment]
@atomGit
What is "AMO", who is pants, and where/when was this previously brought up?

**Comment by rusty-snake** [comment]
AMO = addons.mozilla.org
pants = Thorin-Oakenpants

**Comment by atomGit** [comment]
1. addons.mozilla.org
2. the lead project manager
3. i dunno, but it was, long ago... by myself, maybe others

**Comment by F1nx** [comment]
Oh! That's a possibility! Having it be a browser suggestion (though I am not sure how we would implement the shell scripts)!
Gotcha, I tried giving the issues a search myself, but I was not successful.

**Comment by atomGit** [comment]
it would take some think time to figure it all out i suppose - the question is, is anyone interested (and capable) in doing it?

you could start with a web page, as you mentioned, and go from there - it would be a matter of figuring out what presets to have and how to implement that and i suspect this would not be a trivial project because user.js gets updated often and so you'd have to figure out whether a change affects a preset, whether a pref needs to be moved from 1 preset to another, etc

regarding the scripts, i don't believe there's an API to modify files in the profile, so the cleaner script, at a min., may still be necessary - then to actually update user.js, the web page/add-on would have to spit out the text which the user would have to save as user.js, though i think this could be automated using a 3rd party service as is the case with (some) add-ons that allow to add/remove search engines

this is all off the top of my head, so there's that

**Comment by Thorin-Oakenpants** [comment]
I wouldn't mind an interactive page, from within the arkenfox repo: e.g. `arkenfox/config/` - that way it is on the same eTLD+1. It's on my wish list ever since
- @overdodactyl and #569, #574, #578 - https://nwmviewer.shinyapps.io/ghacks_userjs/ (not sure what old version it is currently pulling, it used to be the live one)
- also see @icpantsparti and #608 - https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html

I personally find nwmviewer to be very slow to load (5+ seconds), always have . And I would prefer to use no external libraries or anything third party.

I can create a new repo and assign members. I definitely do not want to do this in here. And TBH, it is not high on my priorities, as I consider the user.js already as easy as it gets. I mean come on, it's a TEXT file, and has 17 `[SETUP-WEB`, 13 `[SETUP-CHROME` and one `[SETUP-HARDEN` tags. It doesn't get any easier

I see two parts
- create an interactive that lets to show/hide relevant things
- allow altering values to create an `overrides` text

**Comment by F1nx** [comment]
@Thorin-Oakenpants 

What is eTLD+1?

I will gladly look at the sources you have provided; and I am excited that you also like to have your projects as vanilla as possible.

**Comment by crssi** [comment]
@F1nx  `https://web.dev/same-site-same-origin/`

**Comment by F1nx** [comment]
Thank you for the useful information @crssi!
Concerning @Thorin-Oakenpants' wish(es) with the project, I think it would be doable to the extent of merely providing a customized `user.js` file.

**Comment by F1nx** [comment]
> @icpantsparti and #608 - https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html

Although this project provides a comprehensive interface, it lacks simplicity.

**Comment by F1nx** [comment]
I would say that the other project is wonderful! The information is kept short and sweet. All I think it needs is the ability to configure the setting variables. It would be nice, too, if we just had the description fully extended instead of some of it being hidden by the drop-down arrows.

_(I do notice a bug, though, that allows us to double click an element, and it shows the HTML without even accessing the web console.)_

Here are additional thoughts from the issues:

In #569 @overdodactyl said

> Getting a list of active prefs in the corresponding section probably wouldn't be too bad...parsing the comments correctly might be difficult though.

I agree on that! With the power of regex & fetch, it can be done!

On the other hand, he also provided this option

> If we wanted a non-JS solution we could probably add to your travis build some configurations to run any scripts and update the tables on each commit.

It may help the repo if this was done, but I'll mention that if the default file is templated with the interface, it could be updated client-side. And hey! What if we find that the shell scripts come in handy?

**Comment by F1nx** [comment]
**I'll sum up my review of this project by saying that I have noticed a pattern in what is the biggest obstacle. There is a bridge to cross when transitioning the data from `user.js` to be displayed on these visuals. As a result, I now stand with the idea of keeping the interface a separate repository from this one.**

**Comment by F1nx** [comment]
@Thorin-Oakenpants 
Would it be beneficial if we revisited this old, HTML version of the project?

**Comment by Thorin-Oakenpants** [comment]
If  anyone wants to take a copy of the user.js, and build an HTML file in their own repo, that parses it with no third parties, and returns an interactive HTML page, then go for it. When there is a proof of concept, then we can add a new arkenfox repo and work on styling. The user.js is pretty regimented in it's syntax for comments, notes, settings, test pages, references, setup tags, version numbers, etc

**Comment by Thorin-Oakenpants** [comment]
> the idea of keeping the interface a separate repository from this one

It still needs to pull in the live master user.js: it's pointless using a static or modified one. A modified one requires upkeep, and a static one doesn't solve parsing issues

**Comment by F1nx** [comment]
^ If I could pin that statement, I totally would.

**It is safe to say that we can close this issue until those requirements are met.**

I can start a repo and begin working on a parser for it, but I would need to know what information in particular should be displayed. If all of it should, then in what order of priority?

**Comment by F1nx** [comment]
Even though the issue is closed, somebody please let me know.

**Comment by Thorin-Oakenpants** [comment]
> but I would need to know what information in particular should be displayed

All of it up to and including 4500 section. It's more a case of collapsing/hiding some content

What I envisage is some toggle buttons and drop-downs. Only one applies at a time
- e.g. all | section | version | win/mac/linux | settings | setup-tags | test | default | active-inactive | warnings
- click active and all you see are active prefs etc
- then click setup-tags and all you see are the setup items

Another option, independent of the toggle buttons can be collapsed/full

**Comment by F1nx** [comment]
In the making of this, would NodeJS's default library be considered vanilla?

**Comment by Thorin-Oakenpants** [comment]
Why do you anyone else's libraries? I get that it's a little complicated, and the rules are in my head, but it's not that complicated. All you need to do is parse using the syntax/rules logic that the user.js follows

You're going to need some generic functions, like stripping multiple spaces, search and replace - you don't need a massive bloated external library for that, IMO

**Comment by F1nx** [comment]
I was asking because while I understand how the parser will work, I thought file reading and writing (including JSON formatting) would be a must-have.
