### ISSUE TITLE
review: troubleshooter

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1139]
Not in the user.js since at least v78 (the oldest version people should be using), might be others (didn't do a full check)
- `dom.push.serverURL`
- `dom.push.connection.enabled`
- `font.blacklist.underline_offset`
- `canvas.capturestream.enabled`
- `plugin.default.state`
- `dom.IntersectionObserver.enabled`

notes
- some people might not do any prefCleaning so I do get perhaps having some removed there might help
- can we reduce to 64 items or under, since it's a binary search (AFAIK)
- maybe there are some more deserving new prefs e.g.
    - `dom.security.https_only_mode`
    - worth considering: but TBH, Earthlng has kept it pretty tidy and spot on

current 68 (or 69) items
```
    'network.cookie.cookieBehavior',
    'network.http.referer.XOriginPolicy',
    'privacy.firstparty.isolate',
    'privacy.resistFingerprinting',
    'security.mixed_content.block_display_content',
    'svg.disabled',
    'browser.cache.offline.enable',
    'dom.storage.enabled',
    'dom.storageManager.enabled',
    'dom.caches.enabled',
    'dom.push.connection.enabled',
    'dom.push.enabled',
    'dom.push.serverURL',
    'dom.serviceWorkers.enabled',
    'dom.webnotifications.enabled',
    'dom.webnotifications.serviceworker.enabled',
    'browser.display.use_document_fonts',
    'font.blacklist.underline_offset',
    'gfx.font_rendering.graphite.enabled',
    'gfx.font_rendering.opentype_svg.enabled',
    'layout.css.font-loading-api.enabled',
    'browser.link.open_newwindow.restriction',
    'canvas.capturestream.enabled',
    'dom.event.clipboardevents.enabled',
    'dom.event.contextmenu.enabled',
    'dom.IntersectionObserver.enabled',
    'dom.popup_allowed_events',
    'full-screen-api.enabled',
    'intl.accept_languages',
    'javascript.options.asmjs',
    'javascript.options.wasm',
    'permissions.default.shortcuts',
    'dom.vr.enabled',
    'media.ondevicechange.enabled',
    'dom.webaudio.enabled',
    'media.autoplay.default', // FF63+
    'media.autoplay.blocking_policy', // FF78+
    'browser.formfill.enable',
    'signon.autofillForms',
    'signon.formlessCapture.enabled',
    'security.cert_pinning.enforcement_level',
    'security.family_safety.mode',
    'security.OCSP.require',
    'security.pki.sha1_enforcement_level',
    'security.ssl.require_safe_negotiation',
    'security.ssl.treat_unsafe_negotiation_as_broken',
    'security.ssl3.dhe_rsa_aes_128_sha',
    'security.ssl3.dhe_rsa_aes_256_sha',
    'security.ssl3.ecdhe_ecdsa_aes_128_sha',
    'security.ssl3.ecdhe_rsa_aes_128_sha',
    'security.ssl3.rsa_aes_128_sha',
    'security.ssl3.rsa_aes_256_sha',
    'security.ssl3.rsa_des_ede3_sha',
    'security.tls.enable_0rtt_data',
    'security.tls.version.max',
    'security.tls.version.min',
    'plugin.default.state',
    'plugin.state.flash',
    'dom.popup_maximum',
    'geo.provider.network.url',
    'layout.css.visited_links_enabled',
    'mathml.disabled',
    'network.auth.subresource-http-auth-allow',
    'network.http.redirection-limit',
    'network.protocol-handler.external.ms-windows-store',
    'privacy.trackingprotection.enabled',
    'security.data_uri.block_toplevel_data_uri_navigations',
    'privacy.window.name.update.enabled', // FF82+

    'last.one.without.comma'  // is this part of the binary search?
```

**Comment by earthlng** [comment]
I just ran the troubleshooter in a fresh FF86 profile with the latest user.js and there are exactly 30 prefs that the script will use for the halfing process. That means if there's a single culprit, it'll take either 4 or 5 cycles/prompts to find it, depending on where the culprit is located.
To make it into the to-check list, a pref has to be user-set and not match the default value of the current Firefox version.

Of course we can always add more prefs if necessary but we don't really have to care too much about removing "old" stuff.
If somebody has kept up with our changes and reset removed prefs then those prefs won't make it into "the list"; and if they haven't then those prefs could still be the cause of their problem and the troubleshooter can help find it.
We also don't know what people add to their overrides and therefore I'd argue that more is actually better.

**Comment by Thorin-Oakenpants** [comment]
OK
