### ISSUE TITLE
question: network.protocol-handler.external.ms-windows-store

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1142]
What exactly is a reason for `network.protocol-handler.external.ms-windows-store` to be active and different as is default?

Thank you and cheers

**Comment by Thorin-Oakenpants** [comment]
so that is `disable links launching Windows Store on Windows 8/8.1/10`

Do you really want a link for ilovetaylorswift.com opening up somewhere else other than your default browser?

**Comment by github-account1111** [comment]
>If you click on it in a browser on Windows 10, the games' page on the Microsoft Store websites gets opened, and so does the Windows Store application and the game's page there.

It doesn't though.
Nothing will open until you click Get, at which point you quite obviously want to open Microsoft Store and install the app.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1756209

**Comment by Thorin-Oakenpants** [comment]
Note that windows store is one of a very few handlers that have no warning dialogs
- see https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#975-982

also FYI
- FF101+: [1756209](https://bugzilla.mozilla.org/show_bug.cgi?id=1756209) Support attribution from the Microsoft Store
- this is a nothing burger, a campaign id is not PII and no-one cares, especially me since we nix the handler anyway

---

So this was added in FF24: [866065](https://bugzilla.mozilla.org/show_bug.cgi?id=866065) 

Which leads to bugzilla [1677753](https://bugzilla.mozilla.org/show_bug.cgi?id=1677753) Show permission prompt before opening macOS or windows app store via external protocol.

That bugzilla is confusing - it shows that there is a permission prompt, so IDFK

Anyway the pref stays as is

**Comment by Thorin-Oakenpants** [comment]
url: https://www.microsoft.com/en-nz/p/monster-go/9nblggh2s4gt?rtc=1&activetab=pivot:overviewtab
pref: `network.protocol-handler.external.ms-windows-store`
os: windows 11
test: click `get`

pref true (default) - opens MS store (I have no ms account, btw) - no prompting
pref false (AF) - nothing happens

If you're on windows, I guess you can just open edge IMO

**Comment by Thorin-Oakenpants** [comment]
then again, I agree, you wanted to install it .. so yup, let's remove that pref
