### ISSUE TITLE
iframes/web worker fingerprinting defense?

### ISSUE THREAD

**Issue by eleius** [arkenfox/user.js#1163]
I tried your TZP test and... I don't know enough about web technologies to understand how some of those results are calculated, but I noticed the values in the "iframes" and the "worker" sections are constant across sessions, and RFP doesn't help much either. Scary.

So I have to ask: is there a way to mitigate/spoof those values?

**Comment by Thorin-Oakenpants** [comment]
### 🔻 I'll start with this

TZP is designed to do several things
- get metrics
   - make sure values match via other methods (e.g. iframe, worker, matchmedia, css, PoCs, etc)
   - make sure values match via equivalency
   - this so we can weed out lies and return the real values
      - if it's not a lie, then it's a bug: this is part of building a robust test: e.g Brave still leaks canvas via a particular iframe access method
- NOTE: sometimes leaking the real value via another means/method/equivalency is also OK
   - e.g. useragent header can differ from js navigator: but as long as everyone is the same, it's OK, especially given that you can't hide the OS and the header helps protects against passive fingerprinting (e.g. in TB when the slider is at safest), as well as possibly fooling naive scripts
- detect spoofing (randomizing or spoofed values)
   - to reduce the "noise" - i.e return a static value
   - Note: this is OK: the key is to not leak the real value
- detect errors/blocking/unusual results (e.g. AOPR in uBlock Origin, or extension fuckery)
   - to reduce the "noise"
- by eliminating the "noise", the datasets become more robust
   - the purpose of TZP is to eventually collect some data to determine
      - how many results per metric
      - maybe do one test per profile and get some entropy figures

Oh, and TZP can
- 100% reliably detect gecko
- 100% reliably detect Tor Browser vs Firefox
- 100% reliably detect if RFP is enabled
- 100% reliably detect the OS

So the datasets would be purely gecko, and we could easily drill down into TB vs FF vs FF+RFP (and by version if we wanted to)

For example: if we did an audio test
- if we just accepted the values then we might end up with `thousands` of results because lots of people use an extension to randomize audio: this would make our dataset tainted
- if we return all the lies as a static value, in reality it might be more like `20` distinct values, plus "all the lies".
   - we could then drill down into the OS to gauge equivalency (we cannot hide the OS)
   - e.g. we might find that Mac is only one distinct value, and that Android has 15
   - e.g. ^^ so that would be something that could be actionable of GeckoView: bundle a special audio-only math library
   - ^^ just a made up example based on my knowledge

### 🔻 a snippet from some shit I posted elsewhere

Here's an idea of some metrics in a real world study. This is what I want TZP to do, but purely for Gecko, sliced+diced for TB/FF. To that end I made detecting FF/TB, OS, Version, and RFP super fucking hard to beat, and to prove a point (the point being .. use RFP)

> title: Who Touched My Browser Fingerprint?: A Large-scale Measurement Study and Classification of Fingerprint Dynamics
> url: https://dl.acm.org/doi/10.1145/3419394.3423614
> pdf: https://yinzhicao.org/fpmeasurement/imc20.pdf
> 
> wow, table one just shows [what a f__king mess the user agent devolved into](https://webaim.org/blog/user-agent-string-history/)
> 
> interesting static values' distinct groups
> - font list `115k`
> - user agent `41k` .. seriously, the web needs to get it's shit together
> - OMG ... plugins `16k` (and 14k unique .. wow) <-- really? must be a chromium thing
> - language header `14k` <- so additional/fallback languages here is quite painful
> - canvas `14k`
> - GPU renderer `5.7k`
> - GPU type `5k`
> - pixel ratio `2k`
> - language list `1.2k` 
> - Audio `114` <-- I knew audio entropy was low (23 of those were unique)

### 🔻 So ... what is it you are trying to do?

The values are **_supposed_** to be the same across all tests. See above: **_I either want to catch a bug where something like RFP leaks, or I want to catch you lying_** in order to not taint the dataset

I haven't actually added much in the way of iframe/worker tests (but I will): and they can differ in what they can check compared to the main document: e.g. workers can only check six of the eleven navigator properties that make up the user agent

Since the only one I have done really (with iframes + workers) is user agent, I will assume that's what you're concerned about.

Short of disabling JS, you cannot hide that you are Firefox, you cannot hide your OS (major: e.g. windows, linux, mac, android), you cannot hide your Firefox version (you might be able to screw up some of my individual tests: but I tried to make them all robust as fuck and none are reliant on any prefs), and you cannot hide if you have RFP enabled. After all that, there is very little that you can spoof that can't be detected as a lie even if you blocked the other methods like iframes and workers - e.g you could say you were windows 7 instead of windows 10 and I can't tell that .. except, I can make an assumption that a value is not trustworthy if I detect extension interference (via prototype lies which [creepy built](https://abrahamjuliot.github.io/creepjs/tests/prototype.html) after we had a chat about [palant's article](https://palant.info/2020/12/10/how-anti-fingerprinting-extensions-tend-to-make-fingerprinting-easier/))

What you are trying to do? You literally cannot spoof user agent properly unless you code it into the browser - like RFP. The same goes for most other metrics

**Comment by eleius** [comment]
Wow, thanks for the detailed explanation.

> What you are trying to do? You literally cannot spoof user agent properly unless you code it into the browser - like RFP. The same goes for most other metrics

I'm okay with g00gle & other evil megacorps knowning what browser/os I'm using and even if I'm lying or not. What I don't like is being identified among the crowd - those TZP tests seem to attribute an unique id to my machine even if I'm hardening my user.js, installing addons and so on.

Canvas can be spoofed, audio api can be disabled... my question is, can we also spoof iframes and worker results somehow?

**Comment by Thorin-Oakenpants** [comment]
iframes MAYBE .. to answer your question. e.g. I don't even load a document in them, so uMatrix did exactly diddly squat. And I create them on the fly as needed (and then remove them). Maybe an extension always block them, IDK, I'm not an extension developer.

workers YES... you can block all types of workers (without blocking cookies) - you'll need an extension for workers/shared workers. Service workers is behind a pref (in the user.js)

But my QUESTION would be why block them: just let em rip and trust in two things
- using uBO and ETP you probably don't get FPed much if at all, and almost certainly not by *universally widespread advanced ones**
- the math says with RFP you're looking good (even if you aren't in a set like Tor Browser) on most metrics. Add with webgl/audio spoofing or blocking, you can't be worse off (audio debatable)

And of course FPI (or Total Cookie Protection aka dynamic FPI) is a must - stops a lot of cross site chatter from within the browser

---

> those TZP tests seem to attribute an unique id to my machine even if I'm hardening my user.js

You don't know that until you do a large scale study of one result per profile. But yes, changing prefs can be detected: but unfortunately, some of them we just have to: such as webgl (the entropy is too great), and even flipping things like beacon changes things.

The good news is that a lot of these aren't really checked for, at least not comprehensively
- 800+ window properties: via an iframe
- 1000+ css style properties
- all those prototype lies
- no-one does my domrect known values and shift test (I invented them) - well except creepy who I collaborate with
- no-one does my TimeZone epoch PoC (I invented it) - well except creepy who I collaborate with
- no-one does my devicePixelRation PoC ... not even creepy
- no-one does my user Agent BS detector like I do
- etc

Part of the reason is that these metrics (and even my lie tests) are not super stable: but that's a different topic, because at the backend (server), the data can be manipulated to still connect previous fingerprints. The point is to use JS attack templates to get everything possible. When I say my lie tests are not stable, by that I mean that the extension of browser can randomly decide to lie or not.

Another good thing to think about is that a lot of this is equivalency, or not as bad as your think
- e.g. audio is actually NOT that bad: I honestly believe it is no more than 20 distinct values (in FF), and that this is a direct result of the math entropy (but not as high since the ranges are less in the audio spec)
- javascript user agent: if you don't mess with it
   - without RFP: then you're the same as 60-70% of other Firefox users if you're on stable release: the uptake of new releases is [here at the bottom](https://data.firefox.com/dashboard/user-activity) .. it fluctuates over the four week rapid release cycle
   - ESR: probably 5% of FF users
   - with RFP: then you're definitely in a small group, but will look like ESR
- domrect: this is bit messy since it involves so many things like fonts, webrender or not, system scaling I think, device pixel ration might play a part, etc - but ultimately it all comes down to equivalency elsewhere.  E.g. your default font: so if you don't change your default font (based on your language + OS), you're already better off to a large degree. Exactly how bad domrect is, I'm not sure

I'll take that list from above and give some insight into **_the set of RFP users_**

> - font list `115k`
> on windows this will give away Win10 vs Win7 users: probably 6 to 10 distinct values overall
> mac is probably much the same, linux is a bit of a mess: not all linux distros are covered, it needs work
> android has no font protection with RFP: and as long as you haven't installed custom fonts, it's probably pretty much equivalency of the OS version and hardware model

> - user agent `41k` .. seriously, the web needs to get it's shit together
> as I said above, you're going to be one of **FOUR**: stable, ESR, stable+RFP, the fourth is the previous/next stable

> - OMG ... plugins `16k` (and 14k unique .. wow) <-- really? must be a chromium thing
> Firefox always returns nothing: there is **no entropy(( (flash is now banned)

> - timezone
> it wasn't mentioned, but with RFP, there is **no entropy** - everyone is `UTC 0`

> - canvas `14k`
> RFP randomizes every executiuon, there is **no entropy** except for naive scripts which get sucked in

> - GPU renderer `5.7k` / GPU type `5k`
> RFP spoofs these the same for everyone: so no entropy 

> - pixel ratio `2k`
> RFP spoofs this as `1` for everyone: so no entropy (except subpixels are used everywhere, seee PoCs like mine)
> most of these `2k` distinct values would, I guess, be from mobiles

> - language header `14k` <- so additional/fallback languages here is quite painful
> - language list `1.2k` 
>  if you spoof when prompted to use en-US (and don't add additional languages or change the language order to `en,en-US`), then you're in a very large group

> - Audio `114`
> already spoken about: 95% sure it can;t be more than 20 distinct groups, and that 20 might have a long tail: needs to be looked at though, don't get me wrong

So .. all those super giant scary numbers suddenly look a lot better, some of them are completely eliminated. And there are a lot more RFP protections than those mentioned. It's going to take advanced scripts to really dig. 

One drawback is compat issues with e.g. canvas (and webgl and audio?)
- canvas: now that canvas is more widely used than 3+ years (it seems to be used for almost everything these days: when it doesn't "have to", they just do), a lot of sites break: instead you can allow a site exception for canvas (you will see it in the urlbar). Now if that's a site you're logged into, that's OK. If it's not, then CanvasBlocker kicks in, and randomizes but doesn't break it.
- audio: seems now that webRTC and WorkFromHome is booming, it's OK to enable audio (given I think the entropy is low). Canvas blocker here can also randomize (but not break) it.
- webgl ... again, enable it and randomize in CanvasBlocker

The chances an advanced script hits you, and is used widely across many sites to link your traffic .. **_is slim to none_**. So while CanvasBlocker's spoofing can be detected (and indeed, the spoofing FP can be extension specific), just go ahead and use it. I personally wouldn't bother with the screen or navigator parts since they are covered by RFP.

**Comment by Thorin-Oakenpants** [comment]
sheeshus ... I need COFFEEEEFFFEE now

does that answer the question? feel free to keep asking questions: just be aware that this is off the top of my head **_and simplified_**, so take it with a grain of salt :)

**Comment by Thorin-Oakenpants** [comment]
> I'm okay with g00gle & other evil megacorps knowning what browser/os I'm using and even if I'm lying or not

If you're logged in with a persistent ID, then who cares: except that they use that to re-id you elsewhere or when you come back in a different account etc. Most of these I assume people only have the one account: I always suggest you use a dedicated browser for all your social media etc: gmail, google docs, youtube - e.g. a secondary FF with dFPI, sanitized on close, with a few tweaks

**Comment by eleius** [comment]
That's a lot of info to digest. Thanks for now :)
