### ISSUE TITLE
Migrating from old version

### ISSUE THREAD

**Issue by Onfroygmx** [arkenfox/user.js#1173]
[user-overrides.txt](https://github.com/arkenfox/user.js/files/6446689/user-overrides.txt)

Hello,

I've been following you since quite some time but haven't updated in a while and got a bit lost.
When I run a diff on the current version there are a lot of changes and most of them are deprecated settings, I think.
Could it be possible to have a file containing only what has disappeared? (Deprecated does not mean disappeared)
I can help test it on Mac and Linux if needed?
Regards,

JB
PS: not an Issue just a question.

**Comment by Thorin-Oakenpants** [comment]
everything deprecated prior to FF78
- https://raw.githubusercontent.com/arkenfox/user.js/master/scratchpad-scripts/arkenfox-clear-deprecated.js

everything that has ever been in the user.js but is now removed (and not removed due to deprecation)
- https://raw.githubusercontent.com/arkenfox/user.js/master/scratchpad-scripts/arkenfox-clear-removed.js

For both these
- open about:config (privileged page)
- go control-B to open multi-line editor
- paste in the script
- click run

This will clean up all old prefs, deprecated and removed up to ESR78

To reset deprecated ones in 78 or later, either go through the list at the end in the user.js, or run prefs cleaner

**Comment by Thorin-Oakenpants** [comment]
Note: this only applies to arkenfox, not anything else you have added from all those sources listed in your txt file
