### ISSUE TITLE
How disable Worker, SharedWorker, Web Workers?

### ISSUE THREAD

**Issue by vebmaster** [arkenfox/user.js#1180]
Hi.
serviceWorkers disable:
```
user_pref("dom.serviceWorkers.enabled", false);
```

Please tell me how to disable Worker, SharedWorker, Web Workers?
```
     [1]    Web Workers: https://developer.mozilla.org/docs/Web/API/Web_Workers_API
     [2]         Worker: https://developer.mozilla.org/docs/Web/API/Worker
     [4]   SharedWorker: https://developer.mozilla.org/docs/Web/API/SharedWorker
```

**Comment by rusty-snake** [comment]
You can block them with µBlock origin (https://github.com/arkenfox/user.js/wiki/4.2.2-uBlock-Origin, https://gitlab.com/rusty-snake/firefox-config/-/blob/40a3d9732398a351df0bc3c9974c152a215fd69d/assets/uBlockOrigin:My_filters.txt#L1-3, https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#csp). However by blocking all kinds of workers you should expect much more breakage than if you just disable service worker. Besides I am not sure whether it is better or worse for privacy.

Add this to the "My filter" tab
```
*$csp=worker-src 'none'
```

and add exceptions like
```
*$csp=worker-src 'none',domain=~example.com|~github.com
```

I think you can also `badfilter` these rules for specific domains but I did not tested this.
```
*$csp=worker-src 'none'
||example.com$csp=worker-src 'none',badfilter
||github.com$csp=worker-src 'none',badfilter
```

**Comment by vebmaster** [comment]
Thank you.
I added *$csp=worker-src 'none'.
but it has no effect.
Checking SharedWorker on http://mdn.github.io/simple-shared-worker/
And SharedWorker works
Test page source code: https://github.com/mdn/simple-shared-worker

**Comment by rusty-snake** [comment]
Sad, maybe this only worked on older firefox releases or it only works with WebWorkers (your example uses SharedWorkers). Depending on the reason you want to disable them, you can use 

```js
*##+js(set, Worker, noopFunc)
*##+js(set, ServiceWorker, noopFunc)
*##+js(set, SharedWorker, noopFunc)
```

**Comment by KOLANICH** [comment]
1. just workers cannot be disabled by prefs.
2. service workers currently can be disabled ... [but Mozilla is going to replace webextensions background pages with service workers ...](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)

**Comment by vebmaster** [comment]
> you can use

Thx, work :)

**Comment by Marc05** [comment]
> 
> 
>     1. just workers cannot be disabled by prefs.
> 
>     2. service workers currently can be disabled ... [but Mozilla is going to replace webextensions background pages with service workers ...](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)

Interesting - I wonder if this warrants revisiting dom.serviceWorkers.enabled default.

**Comment by KOLANICH** [comment]
>this warrants revisiting dom.serviceWorkers.enabled default.

No. This only means the fact that was obvious for a long time, but was just ignored, because knowing that fact is useless, because we have no choice: we just should not use browsers by Mozilla. Remembering that we also should not use browsers by Googlag, this means we should not use any browsers and the Web  at all. The game is lost. Now it is obvious that we are fools. The game was already lost by the time Googlag has announced it will have an own browser. If Googlag ever considered making an own browser, it has meant that our game has been lost. What can be wrong when a rich company already owning the Web makes an own browser? Nothing, the result is predermined, they will own not only the Web, but also the browsers. So, a monopolist goes to guaranteedly expand its monopoly. If we allowed it to do it, it means the game had already been already lost.

**Comment by Marc05** [comment]
I understand where you're coming from. There's always going to be a battle for what we want. However, we can still be practical and realistic about things - and that means being constructive; hence the question remains.

**Comment by atomGit** [comment]
he wasn't being impractical - if we are going to connect to the net with any modern browser using any modern device, the game IS lost, several times over, and at least as far back as '98 or so, and it matters not how hardened the browser is or what browser it is

this repo (rightfully) doesn't deal with hardware or firmware and therein is where the real danger lies

**Comment by WildByDesign** [comment]
> Sad, maybe this only worked on older firefox releases or it only works with WebWorkers (your example uses SharedWorkers). Depending on the reason you want to disable them, you can use
> 
> ```js
> *##+js(set, Worker, noopFunc)
> *##+js(set, ServiceWorker, noopFunc)
> *##+js(set, SharedWorker, noopFunc)
> ```


@rusty-snake 
These filter rules still work great. Thank you for sharing this.

Do you know if it is possible to have these same rules (or similar) that would allow excluding specific domains?

**Comment by rusty-snake** [comment]
Try the exeption syntax from https://github.com/arkenfox/user.js/issues/1180#issuecomment-850838385

**Comment by WildByDesign** [comment]
Unfortunately, uBlock Origin suggests that anything with `||`, `@@` or ,`badfilter` is invalid.

Although there was one solution that did work:

```
mayoclinic.org##+js(set, Worker, noopFunc)
mayoclinic.org##+js(set, ServiceWorker, noopFunc)
github.com##+js(set, SharedWorker, noopFunc)
```

I was hoping to do a block all strategy followed by exempting specific domains but I am not sure if that is possible. Unless I play around with the other parameters from (https://github.com/gorhill/uBlock/wiki/Resources-Library#set-constantjs-). Instead of passing `noopFunc` parameter, I may try the others such as `true` to see if something can achieve that. If not, I still have a working option.

**Comment by rusty-snake** [comment]
The people who can help you can be found [here](https://www.reddit.com/r/uBlockOrigin/).

**Comment by iam-py-test** [comment]
> Unfortunately, uBlock Origin suggests that anything with ||, @@ or ,badfilter is invalid.

Those are only valid for "network" filters (i.e. the $csp filter shared earlier); these are scriptlets.
You have two options:
- add exceptions to the original rules
```adblock
*,~domain.to.exclude##+js(set, Worker, noopFunc)
```
- add separate exclusion rules
```adblock
domain.to.exclude#@#+js(set, Worker, noopFunc)
```
Please see [the uBlock Origin documentation on scriptlets](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection)
Thank you

**Comment by Thorin-Oakenpants** [comment]
> The people who can help you can be found [here](https://www.reddit.com/r/uBlockOrigin/).

go ask in https://old.reddit.com/r/uBlockOrigin/new/
