### ISSUE TITLE
Regarding ETP and uBO

### ISSUE THREAD

**Issue by TearJoy** [arkenfox/user.js#1190]
Hi there! Big fan of the project ever since I've found out about it. I have a few questions about ETP and uBO.
Do i need to use ETP if I use uBO in hard mode, and if yes does it need to be the whole list?
Another question is do i get a performance boost if I disable ETP and have uBO on hard mode (ofcourse 3p cookies are still blocked)

Looking forward to the response

Thanks again!

**Comment by rusty-snake** [comment]
> Do i need to use ETP if I use uBO

The ETP lists only block a few Tracker/Crypto-Miner/Fingerprinter. uB blocks far more, therefore you can disable ETP (blocking) safely.

> do i get a performance boost if I use uB in hard mode

yes

> do i get a performance boost if I disable ETP

Hmm, ETP is C++ and has only a small list (compared to uB). It is very fast, so a boost would be very small. IIRC request "blocked" by ETP are handled be extensions (webRequest) too and allowed if the extension redirects it. If this isn't the case uB (JS/Wasm) will do the blocking which could result in a slowdown.

**Comment by TearJoy** [comment]
I see, I've done some research myself in the past by checking disconnect's list and check if uBO has the same sites blocked or not. What i can tell is yes uBO covers most if not all sites that are blocked with ETP. But i've also seen pants said that ETP's fingerprinter list is the first line of defense and extensions are second. That's what made me confused and wonder if I should actually enable the ETP fingerprinters list or just disable everything and rely on uBO.

Anyways, thanks for your response, I'll do some more thinking and come up with a final conclusion sooner.

**Comment by Thorin-Oakenpants** [comment]
Just leave ETP on
- any possible perf gained by not using ETP wouldn't be detectable by a human, you're talking milliseconds
- uBO is mandatory, and the more requests you block, the less to wait for and load and interpret etc, including third parties that then make more requests .. doh
   - in other words, if you're looking for **_meaningful_** perf improvements, this is where you should be looking, not at ETP
- ETP literally [cannot hurt](https://old.reddit.com/r/firefox/comments/l7xetb/network_priority_for_firefoxs_enhanced_tracking/gl9rn9n/)
   - overlap in lists is immaterial, as long as one blocks, it's blocked (except see gorhills list fifth item re redirect)
- ETP ships with extras
   - such as shims, but ETP shims are limited to strict mode
   - such as Total Cookie Protection in strict mode
   - crypto/fingerprinters lists (IDK if uBO contains those and IDCare)

Just leave ETP on and be done with it

> But i've also seen pants said that ETP's fingerprinter list is the first line of defense and extensions are second

- blocklists are the first line of defense against known scripts, but that's a game of whack a mole, only works against "known" scripts, and scripts are becoming "embedded" into js files that are required for the site to function: i.e, you can't block them
   - first line, because blocking the source of the FPing nullifies the whole FP which means zero leaks/bugs/whatever
- built-in browser initiatives, such as RFP, or Brave's Shields, are the next defense: protecting various APIs and metrics, and there are seven or eight ways they can do this
- extensions are a LAST resort, and only good for naive scripts: advanced ones dance rings around them
