### ISSUE TITLE
Web Extension getting force-installed by Mozilla even with Normandy and telemetry disabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [arkenfox/user.js#1201]
I created a new Firefox (89.0.2) profile with a `user.js` that included the following:

```
user_pref("app.normandy.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("browser.ping-centre.telemetry", false);
```

I used the profile for about an hour, which included ~4-5 sessions of Firefox (meaning FF was opened/closed 4-5 times during that hour).

After I did this, I examined the new profile's folder.  I was unhappy to see that the profile now contained a new `features` subfolder which contains a UUID-named subfolder, which in turn contains `reset-search-defaults@mozilla.com.xpi`.  That XPI file is for the "Reset Search Defaults" web extension, which I did not install.

I had hoped setting `app.normandy.enabled` to `false` would prevent this nonsense.

Note also that these two settings got added by Firefox to `prefs.js`:

```
user_pref("extensions.reset_default_search.runonce.3", true);
user_pref("extensions.reset_default_search.runonce.reason", "previousRun");
```

It's concerning that the "reason" is "previousRun", as this is a brand new profile.  I can think of 3 possible explanations:

1. The "reason" description is meaningless and misleading.
2. Even with all the prefs above added to `user.js`, profile tracking/telemetry was still somehow being performed.
3. Mozilla is performing tracking/telemetry per-installation, and not just per-profile.

Why is the unwanted `Reset Search Defaults` web extension getting installed without consent even with Normandy and Telemetry (supposedly) disabled?  How can this unwanted behaviour be prevented?

**Comment by Gitoffthelawn** [comment]
Looking at `prefs.js` in the new profile, it now also includes:

```
user_pref("app.normandy.migrationsApplied", 10);
```

That's a bit concerning because the old profile had the same setting and value.  If that literally means that 10 Normandy migrations have been performed, then either Firefox performed 10 Normandy migrations on the new profile (even with Normandy disabled), or somehow Mozilla is tracking things for the system, and not just per profile.

**Comment by Thorin-Oakenpants** [comment]
lay off with the innuendo (force-installed, tracking, misleading reason etc) and stick to facts. Mozilla doesn't "track" you, the "reason" may not make sense to you but it sure will to mozilla devs .. etc

This will have nothing to do with telemetry.

FWIW, I have no `reset_default_search` prefs in any of my profiles (one profile per Firefox version). These are all portable except for Beta and Nightly (which are installed). These are all en-US builds.

My first thought is that this has something to do with regional settings: in my everyday FF I have an override `user_pref("browser.search.region", "US"); // [HIDDEN PREF]` - but I do not do that in other firefox instances/profiles. I am NOT in the US, and I do not block regional settings in all the other profiles (they're for testing), and yet I do not have any such system extension or any prefs indicating resets

When or if I get time, the answer will be to go find the relevant bugzillas to understand what triggers this - I do recall seeing a number of these in the past (I scan all bugzillas per release looking for version PoCs). There will be nothing nefarious or dubious about this - the key is to work out how/why it is done

As for your actual default search engines - so what? who cares? You can add your own and you can disable built in ones. I do not understand the fuss - I do understand the issue with remote changes, but that's not really different to them just changing the code in the next update - big deal IMO. You may not like my answer, but effectively it is if you don't trust mozilla then stop using Firefox

**Comment by rusty-snake** [comment]
> If that literally means that 10 Normandy migrations have been performed, then either Firefox performed 10 Normandy migrations on the new profile (even with Normandy disabled), or somehow Mozilla is tracking things for the system, and not just per profile.

or it is a version meaning thie profile is at version 10 (migrated or created) and only needs migration when there is a version 11.

> user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{[UUID]}\",\"addons\":{\"reset-search-defaults@mozilla.com\":{\"version\":\"2.0.0\"}}}");

Did you tried to set

https://github.com/arkenfox/user.js/blob/a6d20eaf5b4d6fc306257cf56beb89595c6be173/user.js#L328-L330

**Comment by Thorin-Oakenpants** [comment]
It's incredibly hard to find anything about this: tried mercurial, searchfox, bugzilla, site specific google searches, and more. Doesn't help with generic terms, and so much to wade through. Maybe some/all of it is hidden due to commercial sensitivity, IDK.

The fact that it doesn't seem to change for me on all my vanilla profiles, is likely because my actual region search defaults haven't changed and match en-US. The "migration" was run, I am at 10 - might be interesting to go back over releases, I go back to FF60, and see what the values are

It was always intended that system addons could be remotely updated, security reasons among them, bug fixes for another - e.g. some aspect of normandy is how they rolled out the addon-geddon 2 fix - and without digging up any links, they then hardened/limited that method to be untamperable and it is reserved for emergencies: and they have never used or abused it since AFAIK. This is completely different to a system addon getting updated: and if they want to update the default search engines to match a region, so be it - that's entirely within their right to do so in order to try and maximize returns on and to respect search engine deals.

Change your search region to en-US, assuming you are installing an en_US build. And/or block system addon updates (which the user.js does by default)

Closing. Feel; free to re-open if it still happens in a new profile with system addon updates disabled

---

Just to back up what Rusty has pointed out, AFAICT system addons will not update if there is no URL. The master switch should also work - the URL was defense in depth IIRC.

https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIInstall.jsm#4037
```js
let url = Services.prefs.getStringPref(PREF_SYSTEM_ADDON_UPDATE_URL, null);
```

https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIInstall.jsm#110
```js
const PREF_SYSTEM_ADDON_UPDATE_URL = "extensions.systemAddon.update.url";
```

**Comment by Gitoffthelawn** [comment]
> It was always intended that system addons could be remotely updated, security reasons among them, bug fixes for another - e.g. some aspect of normandy is how they rolled out the addon-geddon 2 fix

Are you saying they sometimes use Normandy to push security fixes?  Don't you disable Normandy and publish a `user.js` that disables it?

**Comment by Gitoffthelawn** [comment]
@rusty-snake wrote
> or it is a version meaning thie profile is at version 10 (migrated or created) and only needs migration when there is a version 11.

Yes, that's definitely another possibility.  Although in a couple profiles I examined, there were exactly 10 settings previously pushed by Normandy.  Could be a coincidence, although it would be quite a coincidence.

> > user_pref("extensions.systemAddonSet", "{"schema":1,"directory":"{[UUID]}","addons":{"[reset-search-defaults@mozilla.com](mailto:reset-search-defaults@mozilla.com)":{"version":"2.0.0"}}}");
> 
> Did you tried to set
> 
> https://github.com/arkenfox/user.js/blob/a6d20eaf5b4d6fc306257cf56beb89595c6be173/user.js#L328-L330

I have not.  The issue there is that it's "all or nothing", so you will lose important updates including webcompat changes and things like that.

For most system Add-ons (all of them, except this troublesome one, from what I've seen), you can just remove them from the `features` folder of Firefox's install folder.  They will then get updated by Mozilla as needed without issue (as long as that pref isn't toggled).  This one, for reasons unknown to me (which, Mr. Thorin Crazypants, isn't some sort of allegation... it's just a fact) behaves differently than all the others.  If it acted just like all the other system add-ons it would be a non-issue.

Because it behaves differently than other other system add-ons, and because I have no use for it, and because it causes security software alerts when it gets force-installed (if Thorin has a better term, he's welcome to propose one) I would like to simply have it not get installed... especially since it gets installed at unpredictable times and in unpredictable situations (I witness it often getting installed/uninstalled on its own, while Thorin can't get it installed at all).  If setting `extensions.systemAddon.update.enabled` to false or nixing out `extensions.systemAddon.update.url` are truly the only ways to accomplish this (which is still unknown despite this issue being quickly closed), then the cost is likely greater than the benefit, and I'll work with Mozilla to come up with a better way to implement this functionality.

**Comment by Thorin-Oakenpants** [comment]
> which, Mr. Thorin Crazypants, isn't some sort of allegation

Yes, it IS an allegation. It's ad hominem and a personal attack, because you didn't like my answer. I'm not going to tolerate abuse. This is your only warning.

For the record, **_I spent several hours digging into this_** (and even considered annoying mixedpuppy, but didn't), and everything I do I would like to think is based on logic, facts, common sense, looking at all sides of an equation, etc. And yet I get called "crazy" (here) and "biased" (in another recent post, user now banned). Call me whatever the fuck you like elsewhere, but don't disrespect me in my own repo. I would have thought after 4.5 years on here, with my discussions and transparency and explanations of decisions etc, that I am thorough and logical and always do what is best (which can sometimes be subjective) and have never wavered in always trying to make things better

If I going to be treated like this, it's the fucking banhammer, or I'll just walk away

stuff
- does this happen in a new profile with the user.js ?
- repeat: does this happen in a new profile with the user.js?
- DID YOU EVEN TRY WHAT I SAID about setting your search region: e.g. you can make it match your build
- what is your build language
- what is your region: see about:support, at the bottom
- are you changing IP often via VPN and the region is getting updated (see 0207)
- Try policies: https://github.com/mozilla/policy-templates/issues - although I think search is limited to ESR but might have some workarounds and they plan to change it
- ask ~~mixedpuppy~~ someone on bugzilla

I fail to see how any of this is an arkenfox problem
- first you haven't shown or been clear that it happens with the arkenfox user.js, all I know is you added "some" prefs
- second, where is the privacy or security concern
- third, why is it MY problem if your security alert gets triggered - that's a YOU problem

**Comment by Thorin-Oakenpants** [comment]
marking as invalid until you show that it happens on a new profile with the user.js, and can show that it is a security or privacy concern

**Comment by Gitoffthelawn** [comment]
Are you setting the standards for yourself and others equal?  How are anonymous Telemetry and Normandy security and/or privacy issues?  If they are real and verifiable fact-based issues, please let me know, and I'll report them to Mozilla so they can be addressed through regular channels.

Before I answer your myriad of questions, please have the courtesy to answer mine.  I asked only 2 questions:

@Thorin-Oakenpants wrote:
>> It was always intended that system addons could be remotely updated, security reasons among them, bug fixes for another - e.g. some aspect of normandy is how they rolled out the addon-geddon 2 fix

@Gitoffthelawn responded:
> Are you saying they sometimes use Normandy to push security fixes? Don't you disable Normandy and publish a user.js that disables it?

Please answer.  Thanks.

If you find honest fact-based questions like these unacceptable, just let me know in a ***kind and calm*** way, and I'll be sure to not ask them again.  Thank you.

**Comment by Thorin-Oakenpants** [comment]
> Are you setting the standards for yourself and others equal?

I find this incredibly naive - go look up what a threat model is. The arkenfox user.js is a template, and a user.js is limited in what it can do. As for what constitutes a privacy or security concern is not always black and white - if you're in the brigade that believes that, then I have nothing more to say

> Before I answer your myriad of questions

They are rhetorical questions to see if you can follow the template for issues. I repeat: **_marked as invalid until you show that it happens on a new profile with the user.js, and can show that it is a security or privacy concern_**

> Please answer. Thanks.

The answer is already there. This has nothing to do with system addons or telemetry. Read what I said - it is a security/fallback mechanism for emergencies that .. quote "they have never used or abused it since AFAIK" (i.e since they pushed a change for addon-geddon 2).

This cannot be addressed in a user.js (for security reasons), and while some people scream and rant about it - it is a security mechanism, with a lot of safeguards (such as not being manipulated by third parties e.g. a user.js), that should it be abused by Mozilla would cause a massive outcry. If you believe this would be abused, then I have a bridge to sell you along with two rocks that keep tigers away. Not to mention that they can just push any changes in the next 4-weekly update

I'm not arguing for or against, just pointing out the facts. Do I personally like them to be able to remotely change something - not really. But do I understand why they decided to keep and harden this mechanism after addon-geddon 2, yes. Do I trust there are enough safeguards in place that it isn't really an issue - yes.

**Comment by Gitoffthelawn** [comment]
> I find this incredibly naive - go look up what a threat model is. The arkenfox user.js is a template, and a user.js is limited in what it can do. As for what constitutes a privacy or security concern is not always black and white - if you're in the brigade that believes that, then I have nothing more to say

I think that's the third or fourth time you've tried to pigeonhole me as a person who believes something specific.  Please stop that behaviour.  Your assumptions are all wrong and the recurrent mudslinging isn't appreciated and serves no purpose unless your intent is to be rude and offensive.

> > Before I answer your myriad of questions
> 
> They are rhetorical questions...

You provided no indication they were rhetorical.  Although your comments repeatedly indicate you believe you know what I think, I truly have no idea what you are thinking.  I'm not a mind reader.  I started writing answers for all those questions, but fortunately I only spent about 5 minutes on it, so no big harm done.

> [Regarding Normandy...] The answer is already there. This has nothing to do with system addons or telemetry. Read what I said - it is a security/fallback mechanism for emergencies that .. quote "they have never used or abused it since AFAIK" (i.e since they pushed a change for addon-geddon 2).
> 
> This cannot be addressed in a user.js (for security reasons), and while some people scream and rant about it - it is a security mechanism, with a lot of safeguards (such as not being manipulated by third parties e.g. a user.js), that should it be abused by Mozilla would cause a massive outcry. If you believe this would be abused, then I have a bridge to sell you along with two rocks that keep tigers away. Not to mention that they can just push any changes in the next 4-weekly update
> 
> I'm not arguing for or against, just pointing out the facts. Do I personally like them to be able to remotely change something - not really. But do I understand why they decided to keep and harden this mechanism after addon-geddon 2, yes. Do I trust there are enough safeguards in place that it isn't really an issue - yes.

Thank you for your reply.  I agree with the actual facts you wrote, but please stop assuming or guessing what I believe and don't believe and talking about selling bridges to me.  It's not productive, and your repeated behaviours border on libel.  Plus, your assumptions/guesses are completely wrong.

Regarding Normandy, why do you have it disabled in the `user.js` you publish, if the goals of your `user.js` are to increase security and privacy?  I haven't seen you publish any known privacy problems with Normandy (if I just haven't found your publications on the topic, please kindly let me know), and you state that one of Normandy's purposes is to push security updates using a hardened mechanism that you trust.  Based on your stated goals for your `user.js` and supporting facts you provided, it seems like the `user.js` you distribute should ensure Normandy is enabled, and *not* disabled.

**Comment by fxbrit** [comment]
FYI the list of all search engines extensions available in firefox is stored in [this](https://searchfox.org/mozilla-central/source/services/settings/dumps/main/search-config.json) part of the source code.
as you can see it contains extensions targeted towards various regions of the world with the relative correspondent entry in the json itself, so the assumption of it being a regional thing was surely right, although I wouldn't know which pref controls that (but probably by looking at the file itself and how the regions are represented you could find that out).

as far as I can tell, there's no way to prevent the search extensions for your regions from being installed in a new profile (or when clicking on "Restore default search engines" in the settings) unless you manually stripped the search engines from this file at compile. take this as an empirical evidence: I know it because I tried and failed, so I just strip engines from the source code when I patch stuff before building, and that does the trick in the sense that they can never come back at that point.

as a final note, I believe the search engines are not installed remotely as no outgoing connection is triggered on first launch of a freshly built browser, and I leave wikipedia and ddg so if that was the case I believe the connection would show up in about:networking. also, policies don't fully remove the search extensions, if you disable them through policies and the hit the reset button, google and the rest of the gang will be back (with no additional connection I believe, and I'm only saying this cause I saw that URLs were being investigated but I believe they are not involved tbh).
so yeah, not a definitive answer to the issue but it might be helpful in some way.

does any of this really matter for this repo? likely not, but since you were searching for something I might have already kinda seen I decided to stop by. cheers everyone.

**Comment by Thorin-Oakenpants** [comment]
[stop digging](https://en.wikipedia.org/wiki/Law_of_holes)

- you've called my standards into question, so I pointed out it was a template
- what part of this is INVALID until you show that it happens with arkenfox user.js in a new profile
- what part of the questions/pointers do you not understand that they are solely for YOU in order to overturn with the INVALID
- now you're making assumptions about [normandy](https://mozilla.github.io/normandy/) and this user.js - "should ensure Normandy is enabled, and not disabled" - I wish I had never mentioned it. What part of "this cannot be addressed in a user.js" is confusing? What part of "some aspect of normandy is how they rolled out the addon-geddon 2 fix" means that all of it needs to be enabled

> "but fortunately I only spent about 5 minutes on it, so no big harm done"

Pay attention - the questions/pointers were to help *you*, not *me*. And not answering the questions just means everyone, myself included, have little to zero information. As it happens, I read up today on a lot of search engine bugzillas, and found out quite a few things - but it's ALL IRRELEVANT unless you show that this issue is not invalid

> does any of this really matter for this repo

No

---

If you had come in here and said, "hey guys, I'm struggling to find out why my default search engines change in a new profile. I tried with arkenfox and it doesn't happen, and wonder if anyone has any ideas on what prefs stop it, I tried these ones" everything would have been peachy. Alternatively it does happen with arkenfox, in which case I would then really dig into it.

Stick to the [issue instructions](https://github.com/arkenfox/user.js/blob/master/.github/ISSUE_TEMPLATE/troubleshooting-help.md)
