### ISSUE TITLE
browser.urlbar.sponsoredTopSites

### ISSUE THREAD

**Issue by Onfroygmx** [arkenfox/user.js#1203]
Hello,

I don't know the impact and since it is here, but I don't like this setting:
browser.newtabpage.activity-stream.showSponsoredTopSites
default to true.
![sponsored](https://user-images.githubusercontent.com/25054585/124486896-5a105580-ddae-11eb-8727-5dc6d1b1aba0.png)
Previously this was your setting:
user_pref("browser.newtabpage.activity-stream.showSponsored", false);

Onf.

**Comment by Thorin-Oakenpants** [comment]
> Previously this was your setting:

It has **_never_** been in the arkenfox user.js

It was added to Firefox in FF83+, see #1061
- ignored by me: I'm the only person who does changes: earthlng provides diffs and points things out if they he thinks I missed anything (which is super rare), and no-one else piped up
- arkenfox disables start and newtab using Activity Stream 
- also see `0105`: disable Activity Stream stuff (AS) - see `0102`
    - > `**NOT LISTING ALL OF THESE: USE THE PREFERENCES UI**`
- sponsored shortcuts being collected and stored would be the same for everyone, at least by region: like snippets, or safe browsing updates etc - everyone gets them, it's not a threat
   - IDK if they are retrieved or not if AS is never shown, and IDCare
   - IDK if the links themselves contain a referal, but again, I doubt it's anything more than a marketing id to gauge success: not trackable or individually identifiable
   - not really interested in looking at it TBH (see the other points) and I can do without the maintenance aspect of the *constantly changing* AS

The parent item is `browser.newtabpage.activity-stream.feeds.topsites` , and maybe I got that confused with `browser.newtabpage.activity-stream.feeds.section.topstories` which now seems to be Pocket related, which confuses me what with `browser.newtabpage.activity-stream.section.highlights.includePocket`  .. which is why I can't be bothered with AS stuff.

I'll @earthlng to see if he thinks we should add this. I get that despite us setting the start and newtab pages to not use AS, some people like it, so maybe it could go under the personal 5000s section (AFAICT this is not a tracking/privacy/fingerprinting/ or security issue)

**Comment by Onfroygmx** [comment]
I might seem crazy but I see it in the user.js:
![image](https://user-images.githubusercontent.com/25054585/124512136-fdc22b80-ddd7-11eb-9eef-f8f955ce5b7e.png)

**Comment by Thorin-Oakenpants** [comment]
you highlighted the child checkbox called "Sponsored shortcuts" and your first sentence says

> but I don't like this setting: `browser.newtabpage.activity-stream.showSponsoredTopSites` default to true.

`browser.newtabpage.activity-stream.showSponsoredTopSites` is the correct pref that controls the child checkbox. This is not the same as `browser.newtabpage.activity-stream.showSponsored`

**Comment by Thorin-Oakenpants** [comment]
The UI for it was added in FF87. It "fits" this description, so I'll just add it there
- `0105c`: disable Activity Stream Top Stories, Pocket-based **_and/or sponsored content_**
