### ISSUE TITLE
[Hearsay] official Fenix with about:config mistakingly unlocked

### ISSUE THREAD

**Issue by KOLANICH** [arkenfox/user.js#1210]
https://github.com/mozilla-mobile/fenix/releases/tag/v90.1.0

Haven't tried it myself though, but according to some people in the internet it has about:config unlocked. If it is true it may be an opprtunity to unlock about:config on phones without root.

**Comment by Thorin-Oakenpants** [comment]
well .. to be as blunt as I can ... **_DO NOT DO THIS_**

- if it's **_mistakenly_** unlocked, it will simply get re-locked next update, meaning any pref changes the user does probably won't be reset, and the user will never be able to revert them should an issue arise, and since they are modified, Firefox updates won't change them either, which is a security issue. And if the next update decides to revert all modified preferences (I doubt it), then what was the point - I'm assuming no one is going to stay not-updated, that's just assinine
- hearsay .. don't post hearsay, post facts
- this repo does not care about android
- there is already a solution - it's called using beta/dev/nightly where about:config is unlocked

**Comment by KOLANICH** [comment]
>if it's mistakenly unlocked, it will simply get re-locked next update

Yes. But if I remember right, access to about:config is controlled by a pref within about:config itself, so ....

> and since they are modified, Firefox updates won't change them either

... it may be an opportunity to switch that pref and get a permanent access to it.

>there is already a solution - it's called using beta/dev/nightly where about:config is unlocked

Thanks for the info. It's nice that they haven't fully locked it yet.

**Comment by Thorin-Oakenpants** [comment]
> But if I remember right, access to about:config is controlled by a pref within about:config itself,

IDK for sure (because I'm not interested), I thought it was a build flag
