### ISSUE TITLE
With "privacy.resistFingerprinting = true" screen resolution detects as webpage square

### ISSUE THREAD

**Issue by asakura42** [arkenfox/user.js#1226]
With disabled `privacy.resistFingerprinting` screen size detects as usual `1366x768` that is popular and okay. But with `privacy.resistFingerprinting = true` screen size detects as pure webpage square which is more unique and traceable.

![test](https://user-images.githubusercontent.com/51290160/128331682-a4854227-aa91-4302-a5f6-3cc55bd5ffdb.png)

**Comment by rusty-snake** [comment]
Did you already read #1214? I think it's the same.

**Comment by asakura42** [comment]
@rusty-snake 
>It only leaks that you use RFP but this is already detectable is many places.

Real trackers doesn't see my resolution you think? Why https://coveryourtracks.eff.org/ writes this resolution? It isn't 'local' tracker like `css min` or smth like that.

**Comment by asakura42** [comment]
>RFP means screen is tied to inner window, period, end of story

Ehh, I see, so my only option is letterboxing, right?

**Comment by asakura42** [comment]
Yep. I read Mozilla's website and wiki here and realized that with tiling WM as i3 RPF is basically unusable because of screen spoofing doesn't work as expected. All other RPF options are great, but this is fail as for me because it creates really unique parameter of inner resolution that doesn't changes cus of tiling wm. The only option in this situation is letterboxing but come on, nobody wants to use little square instead of full browser page. I think I got the point an you can close the issue if I am right. But I hope that there is some option to spoof screen resolution more effectively.

**Comment by Thorin-Oakenpants** [comment]
> But I hope that there is some option to spoof screen resolution more effectively

No one "cares" right now, because Tor Browser is fine with the status quo because they are super busy and it's not "broken" per se, and Moz is busy as well and consider RFP on the back-burner as it is not a front facing supported feature

That doesn't mean that it won't become front-facing or used in Firefox. Moz have already done studies on privacy measures vs usability, and they know that anti-fingerprinting needs uptake to be effective. So reducing compat/side-effects is important, as well as managing users expectations (education). One of the biggest reasons users abandoned RFP was real estate: new windows sizes, not starting maximized. At the time, letterboxing didn't even exist.
- ooh, here it is https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/33282#note_2670948

Personally I believe screen (+ available screen) should be decoupled from inner (+ outer). This would make resizing much less "risky" (scripts don't bother with inner as its too unstable) and makes letterboxing as more optional than a strict requirement (tying screen to inner means inner has to be defended tooth and nail - it doesn't have to be this way). I also believe that the default max width should be increased and can be done so without compromising existing entropy - why are we still pushing default small squares on widescreen devices?

Don't overthink it. If letterboxing is not for you (and goodness knows I have avoided it by using a default 1600x900 browser since it came out), then don't use it. Don't let it ruin your workflow or how you want to use the web.

RFP already defeats naive scripts (naive meaning they swallow the poison pill of a random canvas, so you are different each time they check you out), and that's all you need. Advanced scripts (that realize your canvas is random) can already somewhat distinguish you (depends on the script) ...  so at this point don't bother. And that's assuming a script runs (becoming more and more likely as they are embedded into 1st party js files that are required for the website to work), and is universally used (not all scripts are the same) and shared (you can link different fingerprint)
