### ISSUE TITLE
FYI: Something about Fingerprinting

### ISSUE THREAD

**Issue by rusty-snake** [arkenfox/user.js#1228]
*Sometimes I fell that I need hobbies.* Anyway. I did some testing with "FP test sites" and different browsers.
This post contains only the results, the interpretation is up to you.

## How I made the tests?

1. Do https://amiunique.org/ and https://coveryourtracks.eff.org/.
2. 
   - Visit and safe ID
     - https://arkenfox.github.io/TZP/tzp.html
       - Every hash in fingerprints
     - https://fingerprintjs.com/
     - https://abrahamjuliot.github.io/creepjs/
       - Your ID at the top
   - Restart Browser
   - Compare IDs

### LibreWolf 

Version: 90.0.2
Install: Flatpak

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: Your browser has a nearly-unique fingerprint
- TZP: Same ID
- FingerprintJS: Different ID
- CreepJS: Same ID

### Firefox

Version: 90.0.2
Install: Flatpak

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: Your browser has a nearly-unique fingerprint
- TZP: Same ID
- FingerprintJS: Same ID
- CreepJS: Same ID

### Firefox with arkenfox/user.js and uBlock origin

Version: 90.0.2
Install: Flatpak

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: Your browser has a nearly-unique fingerprint
- TZP: Different ID for loose, Same ID for known lies and methods
- FingerprintJS: Different ID
- CreepJS: Same ID (after page refresh) (Same ID as LibreWolf)

### Brave

Version: 1.27.109

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: ◕ your browser has a randomized fingerprint
- TZP: Same ID
- FingerprintJS: Same ID
- CreepJS: Same ID

### Brave (agressive ads & trackers blocking; strict fingerprinting protection)

Version: 1.27.109

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: ◕ your browser has a randomized fingerprint
- TZP: Same ID
- FingerprintJS: Same ID (same as Brave)
- CreepJS: Same ID (same as Brave)

### Brave (Private Window with Tor)

Version: 1.27.109

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have strong protection against Web tracking, though your software isn’t checking for Do Not Track policies.
  - Blocking tracking ads?: Yes
  - Blocking invisible trackers?: Yes
  - Protecting you from fingerprinting?: ◕ your browser has a randomized fingerprint
- TZP: Same ID (known lies and methods same as Brave)
- FingerprintJS: Same ID (same as Brave)
- CreepJS: Same ID

### Tor Browser (Security Level: Safer)

Version: 10.5.2

- AmIUnique: Yes! You are unique among the ####### fingerprints in our entire dataset.
- Cover Your Tracks: Our tests indicate that you have some protection against Web tracking, but it has some gaps.
  - Blocking tracking ads?: Partial protection
  - Blocking invisible trackers?: Partial protection
  - Protecting you from fingerprinting?: Your browser has a non-unique fingerprint
- TZP: Same ID
- FingerprintJS: Different ID
- CreepJS: Same ID

**Comment by Thorin-Oakenpants** [comment]
Aside from getting the values for each metric, these tests don't mean anything. One: derived entropy figures are nutbar crazypants. Secondly, the retention of the "id" can be misleading. Tests only make sense if you understand what the test is doing

coveryourtracks for example gives special preference to brave because it has several randomizations. In reality, for 99% of naive scripts, you only need one poison pill. And yet despite RFP also randomizes canvas, but it gives you a shit score and doesn't even mention that you have randomized - see the results as "Your browser has a nearly-unique fingerprint" for arkenfox and even "Your browser has a non-unique fingerprint" for Tor Browser: not a single fucking mention of randomizing

coveryourtracks, seriously it's hardcoded, gives a free pass to brave because of extra randomizing, but fails to realize that all the other metrics combined still carry a lot of entropy, not to mention a lot of other metrics are not even tested: it's pretty simple test. Items like screen metrics, devicePixelRatio (not so much for desktops), fonts, languages, timezone combined are very high

amiunique and fpjs don't bother to allow for randomizing, so aside from checking the values you get for each metric, they will always be unique

TZP: I haven't leveraged all the detectable lies I could - and some are easy (I can detect Brave and it's Shield mode) -> instantly just return a lie on metrics such as textmetrics, etc. But I am more interested in finding universal solutions (and I haven't even started to leverage service workers: I want to use non-blockable methods first). I'm trying to unmask spoofing to show that lies are detectable (which is not a problem if everyone is lying) which does two things: prove randomizing is ultimately futile against advanced scripts, and to show that extensions give themselves away or leak. As a consequence this help keep the ID more stable. There are other factors that influence this: namely changing zoom levels is impossible to reverse, and changes to what is being spoofed (e.g. shield level, extensions spoofing different sets of items) - I might yet split out zoom affected items into a separate FP.

Another example is that I am not recording a lot of metrics in the fingerprint, as they are not stable enough: FPing ultimately relies on a certain amount of stability. e.g. recording if you are full screen or not, or in PB mode or not. Recording the inner and outer browser measurements. But I could include them and tell people, resize .. HA, GOT YOU!!! Don't ever resize or you DIE, which is clearly bullshit (ignoring RFP which links screen to inner)

And other items are redundant - such as orientation means nothing especially if it's adaptive , and why I record highest x lowest, and not width x height. The screen gives it away, and generally speaking, mobile is portrait and desktop is landscape.

And TZP doesn't bother with a bunch of non-FF features

Since TZP records the bypassed value or "untrustworthy", I still need to track the lies (and bypassed values for easy reference), and I track the method - because that adds entropy

creep is much like TZP - it wants to detect all the BS, bypass the lies if possible

It really depends on what the site is trying to do: either show that any changes to your browser changes your ID which generally adds entropy, or show that changes can be detected and even bypassed.

The other thing to remember is that scripts can collect what they like - behind the scenes, you can manipulate that data and use what they want. Just because an ID changes doesn't make it foolproof. IDs can still be linked .. for example using the info in tzp's methods and non-bypassed lies, I can tell which metrics to ignore when trying to link other IDs - and that's not even considering the science of linking IDs that mutate over time (e.g browser update changes user agent, graphics driver update, etc)

At the end of the day, don't take the entropy seriously AT ALL, and don't take any ID as sacrosanct or final. It's just a representation of one state of the data. Even the prototype lies can differ between runs

PS: @abrahamjuliot is the genius behind the prototype code (after I said we should build one after palant's article). We feed off each other. I'm more of a visionary (epoc timing, two domrect shift methods, textmetric lie methods (not added yet), known canvas method which not new but I didn't see anyone else doing it and same with canvas spoofing fingerprint, css pseudo bypassing, and more) and abraham is the code wizard (and visionary too)

**Comment by Onfroygmx** [comment]
First: I like your approach.
Second: I don't mind'd you're using data in order to test/validate settings
Third: Ask your community for specific/custom test cases,, they will help you.

Personally, I'm lost with with RFP.

Onf.

**Comment by Thorin-Oakenpants** [comment]
> Plus Brave doesn't do extra randomizing ... doesn't do enough randomizing

Brave does plenty of randomizing. Randomizing isn't the issue, it's that they don't cover enough metrics yet for advanced scripts - and to be fair, advanced scripts is not their aim (but always considered: the key is to not leak the real values). They are not looking for Tor Browser level protection (but that may come anyway as they gain enough metrics), they are after a solution that is less compat/breakage/side-effects (but these are inevitable is they want Tor Browser levels of protection). Among others, they have covered canvas and webgl (webgl would have to be the worst item for entropy IMO) and protection is on by default. Kudos. It's very effective.

> To verify this one only needs to download all the versions of last 12 months and find it - hiding device name in one chromium update only to show it in next, then 3 months later, same stuff again

IDK, not following it. AFAIK userAgent etc doesn't hide the OS but instead standardizes it (e.g. Android), and adds random amounts of trailing spaces - and that hasn't changed. Brave users are meant to be auto-updated, so any numbering is kinda moot (at least on windows, there's a background updater and no option to disable it in options AFAIK = that's fine, no issues with that), and userAgent is only one item - canvas, webgl, plugins, audio etc are already more than enough

> Brave results in coveryourtrack test results

Not Brave's fault. I just find it super hypocritical of CYT to detect the randomizing but then claim "hey randomized more than x things = highest score" - they are literally proving that randomizing can be detected and returned as a static result, but fail to take that into account.
