### ISSUE TITLE
Scratchpad scripts

### ISSUE THREAD

**Issue by Leonis87** [arkenfox/user.js#1246]
Hi
I've been using Arkenfox.js for a while. No problem so far. I'm just curious if I'm doing it right because I'm experiencing little issue after run scratchpad scripts. When I apply scratchpad scripts and run updater and prefscleaner batch again, updater says "nothing to apply press any key to continue...". Is this alright or am I doing something wrong ?
My process when creating new Arkenfox profile is:

Create profile directory

Run firefox with arkenfox.js

Close firefox

Copy and paste "user-override.js" to profile directory

Run updater and prefscleaner

Disconnect internet

Open firefox console and run scratchpad scripts in this sequence:

    1. arkenfox-clear-RFP-alternatives.js

    2. arkenfox-clear-deprecated.js

    3. arkenfox-clear-removed.js

Is this the right procedure? I'm still learning so I don't want to follow the wrong start. I searched all over the internet, even on closed githube issues, but I didn't find the answer. I appreciate any advice. Thanks

**Comment by Thorin-Oakenpants** [comment]
If it's a brand new profile, then there is no need to run any scratchpad scripts

Scratchpad scripts is really only needed to reset items arkenfox _used to_ set (and they might still be modified in your profile). And since they are no longer in the arkenfox, prefsCleaner won't know about them, and thus can't reset them

prefsCleaner, resets EVERY SINGLE pref listed in the user.js, regardless of if it is commented out or not. You can/should do this each update, with Firefox closed. Then when you restart Firefox, only the active prefs get reapplied. I restart twice so any prefs that may required a restart after being changed are properly picked up. That way, if we make a pref inactive, then you will match. It will also reset any deprecated prefs in 9999, which is not super important (the prefs no longer do anything), but helps keep things tidy.

Resetting is important, because prefs set via user.js are "modified preferences", and do not get changed by Firefox updates, which could cause problems. e.g. image if you had (madeup name) security.level modified at 3 .. Firefox would never be able to upgrade you to level 4

---

I don't use a `user-override.js` file, I just add mine to the end of the actual user.js, and I don't update, because I'm the author. Maybe someone else can check that bit.

Is this the problem? Nothing to apply? I don't use the updater

---

Starting this version, v91, items removed from arkenfox (and thus you should make sure to reset them) .. if they were active (i.e not commented out), I now add them to item 0650 (or 0651 for the next ESR cycle). I made sure for this release to include everything in 79-91. This should make it easier to NOT have to rely on the scratchpad scripts. i.e you update once a release, rerun prefsCleaner, job done


@rusty-snake help?

**Comment by Leonis87** [comment]
Thanks mate ! You helped me a lot ! I was thinking same about use scratchpad scripts but I wanted be sure that it's alright. I have one more question if you don't mind... Do I have to keep "user-backup" file in Arkenfox profile directory ? So far I just checked if Firefox is working OK after run update and prefscleaner batch and I deleted old "user-backup" file.

**Comment by Thorin-Oakenpants** [comment]
prefsCleaner is simple as - close FF, run it, open Firefox twice - done

scratchpad scripts I have run a few times for testing - make sure to open the console from a privileged page like about:config - and that's pretty simple too. Both those are all about resetting deprecated, removed, useless prefs. Should be zero problems

---

I'm the author, my user.js is live, and I just copy/paste changes from that into the master here at github, and reset items as I tinker. So I don't use an overrides file, or updater - it's not my thing. I would assume the backup file(s) is just in case something goes wrong - delete excess or all of them as you like IMO (same with prefs backups from prefsCleaner)

You said you're using an `user-override.js` - make sure that gets appended to to user.js after each update, as per the [wiki](https://github.com/arkenfox/user.js/wiki/3.3-Updater-Scripts)

v91 is about to be released, just waiting on one more change
