### ISSUE TITLE
Had a Nice discussion with my bank today!

### ISSUE THREAD

**Issue by Onfroygmx** [arkenfox/user.js#1273]
I'm not traceable enough.
I raised an IT security alert because they could not identify me enough.

I'm in Europe and the rules here are clear for the banks (they have to prove the identity off all payments for the last 5 years and most of them do it for 10-15 years).

How to keep yourself safe, knowing that the banks use social media to keep track of their users?

Onf.

**Comment by KOLANICH** [comment]
>How to keep yourself safe, knowing that the banks use social media to keep track of their users?

Require your employer to pay you in cash, I guess. It may be illegal for them to refuse (i.e. in the rules of the org I work it is explicitly highlighted that the employee has a right to get cash in the org, that point is almost the exact quote from the legislation (`salary is to be paid to an employee, usually, at the place where he does his job, or to be transferred to a financial organization mentioned by the employee in his application`)), but you will have a very tough talk to the chief accountant of the org and and you will have to be extremely adamant in pushing for that, because the accountants would do every sabotage they can. And yeah, first you must be 100% sure that the org management staff just won't find it convenient for them to just fire you.

**Comment by Thorin-Oakenpants** [comment]
What does this have to do with arkenfox? What does social media have to do with it? If you need to require proof of who you are, then you can do so (chicken vs egg - how do you get a passport without ID?) - just be thankful you can and pity the poor individuals who are wrongly recorded as having died and fall into a weird loophole where no-one can do anything
- https://www.theguardian.com/world/2021/jan/12/french-woman-spends-three-years-trying-to-prove-she-is-not-dead
