### ISSUE TITLE
updater.sh args not working properly

### ISSUE THREAD

**Issue by MetalNeo** [arkenfox/user.js#1280]
updater.sh does not appear to be accepting args correctly. `-u` still asks for confirmation when running and any capitalized args will throw an error, despite the Wiki indicating these flags should be case-insensitive [wiki](https://github.com/arkenfox/user.js/wiki/3.3-Updater-Scripts)

**Comment by Thorin-Oakenpants** [comment]
thanks, IDK when earthlng will return, but maybe some of the other regular users can diagnose
- @a1346054 @Xathros1 @Onfroygmx 

does it work with an older version? - https://github.com/arkenfox/user.js/commits/master/updater.sh

**Comment by gwarser** [comment]
Maybe `shopt -s nocasematch` will help. Put it in new line after "# Execute #" header.

**Comment by earthlng** [comment]
Hi, thanks for the report.
I'm pretty sure the wiki is wrong and those arguments are case-sens and we only support lowercase.

What's the error message you get?
Can you give the full command line you're trying to run? Maybe you're incorrectly using `-u` after `-p` or `-o`, both of which require an additional argument and would thus swallow the -u. (?)
Does it work if `-u` is the only option?

I don't think `nocasematch` will help here because our getopts doesn't use/accept uppercase options and it doesn't directly affect getopts either.

**Comment by Onfroygmx** [comment]
Hello,

Just did some tests, because I'm not using the script myself, but pretty sure the wiki is not up to date.

Difference between -u and -d:
- It just sets the variable UPDATE to 'yes' or 'no' in order to update the script itself not the user.js
- The first confirmation request is regarding user.js whatever the option and is normal.
- Im' not sure the second confirmation for the script itself is even triggered, because:
  The check is strangely implemented
  Line 194: if [ "$UPDATE" = 'check' ] => which is never set

And for the reason uppercase does not work natively on Unix machines, well ....
And there is no specific implementation for that in the script.

For further troubleshooting these kind of issues, please provide:
- Shell used (BaSH, ZSH,  *SH)
- Shell version
- OS and version

Onf

**Comment by Onfroygmx** [comment]
For a simple no confirmation/check script:

`
#!/bin/zsh
local date_today arkenfox
date_today=$(date +"%Y-%m-%d")
arkenfox=arkenfox_$date_today.js

curl -fsSL -o $arkenfox  https://raw.githubusercontent.com/arkenfox/user.js/master/user.js
cat $arkenfox user-overrides.js > user.js

`

**Comment by rusty-snake** [comment]
> For a simple no confirmation/check script:

Yet another one (with uncomment support): https://codeberg.org/rusty-snake/firefox-config/src/branch/main/assets/updater2.sh

**Comment by Thorin-Oakenpants** [comment]
we can remove `-RFPAlts`

**Comment by Onfroygmx** [comment]
Indeed no reason to make it case sensitive ( code + usage + documentation must be updated then)
I would even remove some options to make it simpler actually.

Just did some unit tests and checked the update function, not the whole script, so my mistake :)
