### ISSUE TITLE
Suggestion: Enable Discussions on github

### ISSUE THREAD

**Issue by BraINstinct0** [arkenfox/user.js#1285]
Open up `Discussions` section. It's for all those questions that don't technically belong to Issues, but still is related to this repo. Good for addressing 'How do I do X with Y' type questions, especially those that aren't normally intended use-cases for user.js.

**Comment by Thorin-Oakenpants** [comment]
I'd rather not: I hate discussions, they auto collapse threads. But I get your point. IDK if I want that sort of noise going on in here - reddit can handle it :) heh

I also hate open issues, so closing

**Comment by BraINstinct0** [comment]
True, (for most) reddit would suffice. Me being one of those avoiding reddit, can well do some more research oneself. After all I should know what I'm doing, right?
Thanks for the quick reply 😉

**Comment by Thorin-Oakenpants** [comment]
can't stand the circle jerking either (or the ignorance, trolls, BS, peacocks) .. I always prefer masturbating to myself anyway - it;'s the only way to fly, baby :)

**Comment by Thorin-Oakenpants** [comment]
> After all I should know what I'm doing, right?

oh, snap. I missed that bit. I guess the answer is ["do you drink"?](https://www.hypable.com/tyrion-lannister-quotes-game-of-thrones/)

**Comment by EdwardLangdon** [comment]
Is there a Subreddit for Arkenfox ?

**Comment by Thorin-Oakenpants** [comment]
your best bet is to use `r/privacyguides` or `r/librewolf`

I would say `r/firefox` but honestly I feel that (just the nature of the beast, not anyone's fault) many in there like to just automatically shit on AF as fast as possible because they do not read what we actually do

I personally do not want any arkenfox reddit sub to exist, and if it ever does, I will denounce it as unofficial in giant 1000px font

**Comment by Thorin-Oakenpants** [comment]
> if you're not interested pants, i get that, but you could simply ignore the whole thing (and i'll even provide the CSS if need be to hide it)

it's not like I can ignore my own repo, I need to be able to see/track everything that happens so I can moderate/answer/fixup-the-BS - and AFAIK I can't turn off notifications for select parts

I don't need to hide the visuals, I need to STFU on the whole section, which, see above, I cannot do otherwise I wouldn't be a very good repo owner

**Comment by atomGit** [comment]
i didn't say, nor imply, that you ignore the repo - just the github discussions section

**Comment by Thorin-Oakenpants** [comment]
> i didn't say, nor imply, that you ignore the repo - just the github discussions section

and I didn't say you did. I said I cannot ignore parts of the repo (emphasis mine)
> I need to be able to see/track **_everything_** that happens so I can moderate/answer/fixup-the-BS - and AFAIK I can't turn off **_notifications for select parts_**

the answer is NO
