### ISSUE TITLE
add "user-overrides example.js"

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1287]
I am in the process of rewriting the wiki

One thing I would like to do is provide a ready to go overrides example
- name it `user-overrides example.js` (so if you unpacked a release as an update, or accidentally dragged the file out of it) it won't overwrite the user's one
- it provides info directly to the user rather than having to go online for it
- it [maybe] allows the wiki to be less verbose
- it makes the user think .. oh what is this, and investigate

I don't use the updater, so I just want to check that all the instructions wouldn't break anything

```js
/******

 THIS IS AN EXAMPLE FILE
  - The real file should be named "user-overrides.js"
    and should be in the profile directory with "user.js"

  An override file serves as a master list of your changes
  - If you use an updater script it will automatically append
    your overrides to the end of the updated user.js
  - If you update manually, you can just copy and paste your
    overrides back in each time

  There are some override recipes ready to go for you at
  - https://github.com/arkenfox/user.js/issues/1080

  ToDo: add link to wiki entries: Overrides, Updating

******/

/*** MY OVERRIDES ***/
user_pref("_user.js.parrot", "overrides section syntax error");

/* EXAMPLE: override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
user_pref("privacy.clearOnShutdown.history", false); // 2803
user_pref("privacy.cpd.history", false);

/* EXAMPLE: I trust my search engine, enable keywords ***/
user_pref("keyword.enabled", false); // 0801

user_pref("_user.js.parrot", "overrides section successful");
```

**Comment by Thorin-Oakenpants** [comment]
hah - https://github.com/arkenfox/user.js/issues/435

**Comment by Thorin-Oakenpants** [comment]
Questions: (I do not use updater scripts)
- when you check for an update and there is none, do both scripts do the same? And is that to modify nothing, or to reapply the overrides?
- what decides if the user.js is ready for an update? Is it just the change in version?
- in non-silent, lets say you are on `95` and `96-alpha` exists, are you prompted to apply
  - if so then this would alleviate the problem (mostly) in #1299 

TIA

**Comment by earthlng** [comment]
2nd question first because it also partially answers Q1 + Q3 ...

The Windows version doesn't care at all about the version online, it only displays the version of the local user.js.
The *nix updater displays both user.js versions (local + online) and then it's up to the user whether to continue or not.

> when you check for an update and there is none, do both scripts do the same?

there's no code in either script that actually compares the version numbers/strings. (see above answer)

> And is that to modify nothing, or to reapply the overrides?

both scripts work on a temporary file. The latest user.js gets downloaded, then it applies the overrides and after that compares the new file with the currently installed user.js. If the files are identical, the temporary file gets removed and the original is left untouched. Otherwise the original is backed up/renamed and the new file renamed to user.js.

re: 3rd question - see answer 1

**Comment by earthlng** [comment]
> I do not use updater scripts

even if you don't use the updater scripts yourself, stuff like this is actually super easy to test.
Just create a new folder somewhere (fe your Desktop) and place an older user.js + the updater in there + run it.
By default the updater always works on the files in the same folder as the updater.
Optionally you can also create an overrides files and see how that's handled.

**Comment by Thorin-Oakenpants** [comment]
thanks E
