### ISSUE TITLE
Rework on the Implementation Wiki Page of user.js

### ISSUE THREAD

**Issue by Loki-L1130** [arkenfox/user.js#1294]
Generally, On the Implementation page, there is no proper way of saying on how to implement user.js . I think that a seperate Github Page or a Video Tutorial hosted on the wiki on how to use it and Update it would be great.

**Comment by Thorin-Oakenpants** [comment]
It's ALL being rewritten, elsewhere without distraction - including #1218 which I'm going to close because I hate open issues

![wiki](https://user-images.githubusercontent.com/16656956/145151735-6e252d88-f229-4042-8693-63b1d8b680a0.png)

This includes making sure people understand what this repo provides and to properly set up expectations

Here's another screenshot: not finalized
- I think the how to use a user.js should go under Implementation
![structure](https://user-images.githubusercontent.com/16656956/145152038-664e496c-2bdd-4d18-b462-2ec6913a0a3f.png)
