### ISSUE TITLE
7015: the DNT (Do Not Track) HTTP header is not actually enforced?

### ISSUE THREAD

**Issue by g-2-s** [arkenfox/user.js#1298]
The user.js says
```
7015: enable the DNT (Do Not Track) HTTP header
 * [WHY] **DNT is enforced with Tracking Protection which is used in ETP Strict** (2701) ***/
   // user_pref("privacy.donottrackheader.enabled", true);
```
But for me the only way to get the DNT to be set to Always is to put this pref in a user-overrides.js. I tried creating an insane amount of new profiles, all vanilla, on 3 different OS and the result, without a user-overrides, is that the DNT is never set to Always.
What am I doing wrong?
Or is the "Only when Firefox is set to block known trackers" what the enforcement is about?
I'm confused

**Comment by Thorin-Oakenpants** [comment]
The pref is inactive, it is commented out, and has been since v91. So the user.js will not set it

```js
  // this line is commented out
  // user_pref("this pref is also commented out", "and will not be applied")

user_pref("this pref is not commented out", "and WILL be applied") // this is another comment
```

here's the commit which changed it - https://github.com/arkenfox/user.js/commit/3697bd8d3a3a011ecfc82e2b345dd7d6bf1880fa in 91-alpha

---

if the pref is false, then it is only sent with TP (tracking protection). ETP standard does not have TP, ETP Strict does, therefore it's a waste of time setting the pref, because we're already sending it - and arkenfox is only going to support ETP strict, so it's redundant

You could fluff around with standard or custom mode and flip bits and bobs and not send DNT, but that's a bit pointless - just use ETP Strict

**Comment by Thorin-Oakenpants** [comment]
to clarify
- before v91 for some time, not sure when we started maybe v68: we had the pref uncommented out and set to true (always send)  so DNT was sent
- since v91: we had TP on in ETP custom mode - so DNT is sent regardless of pref
- today I did commit that switch on ETP Strict - so DNT is sent regardless of pref
