### ISSUE TITLE
Updater downloads 'alpha' instead of stable

### ISSUE THREAD

**Issue by BraINstinct0** [arkenfox/user.js#1299]
- Related: updater.bat
- Platform: (obviously) Windows (11)
- Issue: Updater gets latest(currently version 96-alpha) instead of latest stable(v95)
- Details: Though it'll almost definitely be me missing something already missing in the wiki, but most users will be using the latest stable release-v95. However using the `updater` means you get a version mismatch. This might not be desirable, so I am reporting this as an issue. ~~Besides if I use FF 95, then I should use v95 right?~~<-- very obviously written in the user.js file, though wondering what would be the (most common) problem of using mismatched profiles..

**Comment by a1346054** [comment]
That's expected behavior of the updater, as you can see on https://github.com/arkenfox/user.js/blob/master/updater.bat#L63

You can work around it by downloading the last stable release from the releases page.

The updater could be modified to download from the releases page too, and then extract the necessary files. Alternatively, the repo could be split to have a master/stable/esr branches, and then have the updater automatically point at stable (with an option to instead point to master/esr). However, I'm not sure if the extra work to make that happen is worth it, I'd like to see more people express a want for it.

**Comment by Thorin-Oakenpants** [comment]
The updater runs on end-user's command. I am rewriting the wiki, so I will make it clear that it updates to the live master.

Everything is backwards compatible (i.e we keep prefs around in deprecated and also 6050) and anything new in alpha doesn't usually matter. There are edge cases - e.g. in 96-alpha I deprecate something used in 95 and user on 95 updates and runs prefsCleaner

We could default to only updating if the version does not contain `-alpha`, and add a switch? IDK if it's worth it though TBH

**Comment by earthlng** [comment]
IMO ideally the live master should always match the current FF release and any changes for the next version should be kept in an (ongoing) PR

**Comment by Thorin-Oakenpants** [comment]
That sounds like the ideal solution. Will do from 97 on
