### ISSUE TITLE
Question about dom.keyboardevent.dispatch_during_composition

### ISSUE THREAD

**Issue by GuestGt** [arkenfox/user.js#1305]
Hello,

At one point dom.keyboardevent.dispatch_during_composition was listed as active false.  The commit change, https://github.com/arkenfox/user.js/commit/7a05580c625968d7870e4044aa6990308cf56df1, mentioned it being default false, removed and would be revisited if the default was changed to true.  The default is true now.  Is default true the recommended setting?

And in case it helps anyone, security.ssl.require_safe_negotiation, still needs to be false on a site like Hulu to get it to load videos.  Apparently one of the 1% of sites mentioned in its setting notes that won't work correctly.  That setting is already listed in the troubleshooter but mentioning the specific example just in case or if a [SETUP-WEB] tag is warranted.

Thank you.

**Comment by Thorin-Oakenpants** [comment]
Thanks fore the info/feedback

haven't been there for a while - https://www.ssllabs.com/ssl-pulse/

99.2% support renegotiation in the top 150k alexa top sites - hulu is [ranked](https://www.alexa.com/siteinfo/hulu.com) around 210th place - someone should tell them :)

I want to keep setup tags (currently at 12 - greatly reduced by having optional sections etc) to a minimum and given it's infrequency I don't think it's warranted (even for a one off case like Hulu). We added the `SSL_ERROR_UNSAFE_NEGOTIATION` for searches

**Comment by Thorin-Oakenpants** [comment]
```js
/* 2507: disable keyboard fingerprinting ***/
user_pref("dom.keyboardevent.dispatch_during_composition", false);
```

notes
- removed from AF in Aug 2017
- changed in FF65 from false to true - [1496288 Part 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1496288)
- TB uses default: TB60 = false, TB68+ = true

In the _Before Times_ we used to add all sorts. Side note: the diff was listed when it changed but was not considered (or at least acted on)

Today, in reality, this is just going to be another item that fits under `DON'T BOTHER: FINGERPRINTING`. What is the threat here? One assumes it is keyboard entropy on keydown/keyup to leak different keyboard layouts (e.g. DE vs EN: i.e keyCode + charCode combos). I think this is a bit more complicated than just blocking some keypress events, and ultimately requires us to sit back and wait for RFP to handle it: there are tickets open at Tor Project and Bugzilla related to this, and it's very hard (or requires a lot of work) to crack and is probably a lower priority due to user action required (not that no-one doesn't want to tighten this all up)

Feel free to dig through the labyrinth of keypress and other related keyboard/language/char/locale code :)

---

from https://github.com/arkenfox/user.js/issues/610#issuecomment-451646929

* dom.keyboardevent.dispatch_during_composition
Bug [1496288](https://bugzilla.mozilla.org/show_bug.cgi?id=1496288) - part 2: Stop dispatching non-printable &quot;keypress&quot; events, set keyCode or charCode value to the other value when it's zero, start to dispatch &quot;keydown&quot; and &quot;keyup&quot; events during composition, and enable window.event by default

* dom.keyboardevent.keypress.dispatch_non_printable_keys_only_system_group_in_content
Bug [1496288](https://bugzilla.mozilla.org/show_bug.cgi?id=1496288) - part 2: Stop dispatching non-printable &quot;keypress&quot; events, set keyCode or charCode value to the other value when it's zero, start to dispatch &quot;keydown&quot; and &quot;keyup&quot; events during composition, and enable window.event by default
Bug [1496288](https://bugzilla.mozilla.org/show_bug.cgi?id=1496288) - part 1: Make blacklist prefs for keypress event behavior changes ride the train

* dom.keyboardevent.keypress.hack.dispatch_non_printable_keys
Bug [1508503](https://bugzilla.mozilla.org/show_bug.cgi?id=1508503) - Remove medium.com from &quot;dom.keyboardevent.keypress.hack.dispatch_non_printable_keys&quot;

* dom.keyboardevent.keypress.hack.use_legacy_keycode_and_charcode
Bug [1510111](https://bugzilla.mozilla.org/show_bug.cgi?id=1510111) - Remove www.rememberthemilk.com from the blacklist of keyCode/charCode mirroring of keypress events
Bug [1502795](https://bugzilla.mozilla.org/show_bug.cgi?id=1502795) - Set keyCode or charCode of keypress event whose value is zero to the other's non-zero value by default again unless dispatched on known broken web apps

* dom.keyboardevent.keypress.set_keycode_and_charcode_to_same_value
Bug [1479964](https://bugzilla.mozilla.org/show_bug.cgi?id=1479964) - Set KeyboardEvent.keyCode and KeyboardEvent.charCode to same value if the event is &quot;keypress&quot; event

---

**Comment by Thorin-Oakenpants** [comment]
re Hulu: `https://github.com/pyllyukko/user.js/issues/237#issuecomment-459772737` .. someone should really contact them
