### ISSUE TITLE
[Q] Is it even possible to disable nagging update pop-up in 9x?

### ISSUE THREAD

**Issue by Kein** [arkenfox/user.js#1310]
If you set your update preferences to "Only check for updates" it will annoy you to death with the pop-up about update. I spent 2 days but havent found ANY way to disable it either via **user.js**

```
user_pref("app.update.background.scheduling.enabled", false);
user_pref("app.update.autoInstallEnabled",false);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.doorhanger", false);
user_pref("app.update.silent", true);
user_pref("app.update.url", "");
user_pref("app.update.url.details", "");
user_pref("app.update.url.manual", "");
user_pref("app.update.auto", false);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.enabled", false);
user_pref("app.update.staging.enabled", false);
user_pref("app.update.checkInstallTime", false);
user_pref("app.update.badgeWaitTime", -1 or 999999999);
user_pref("app.update.promptWaitTime", -1  or 999999999);
```
(every possible config option related to auto-updates set to disable/deny it)
or via [**policies.js**](https://github.com/mozilla/policy-templates/blob/master/README.md#appautoupdate) (as well as windows GPO):

```json
{
 "policies": {
   "DisableAppUpdate": true,
   "DisableFirefoxStudies": true,
   "DisablePocket": true,
   "DisableTelemetry": true,
   "DontCheckDefaultBrowser": true,
   "AppAutoUpdate": false,
   "AppUpdateURL": "https://yoursite.com"
   }
}
```
It does not care, it will **ALWAYS** shows the dub nagging pop-up.

My understanding is that they did it on purpose?
![image](https://user-images.githubusercontent.com/623756/147169429-48cabd13-e9fc-4e18-a25c-13c19f776c3d.png)

**Comment by Thorin-Oakenpants** [comment]
[A] No, Update your browser

> I spent 2 days but havent found ANY way to disable it either via user.js

first, you could have saved two days by clicking update. secondly, you can add an override
```js
/* override recipe: turn off the mildly irritating app update prompt which is for my benefit ***/
user_pref("app.update.auto", true);
```

**Comment by Kein** [comment]
> first, you could have saved two days by clicking update. secondly, you can add an override  

> user_pref("app.update.auto", true);

It is already in my user.js. it does nothing, pop-up still being shown.

**Comment by Thorin-Oakenpants** [comment]
your first post shows `user_pref("app.update.enabled", false);`, not `true`. 

You requested help to stop the prompt and all your efforts were to do that, not to enable the update. You wanted to fix all the symptoms instead of solving the problem. Everything you have said indicates that you did not want to update but instead stop the prompt

So what is it you want - to auto update or not? 

What is your OS? How did you install firefox, is it portable, a flatpack, install? If you click update does it update for you?

so this is non-windows. If you want windows to auto update you need to go to settings and tick automatically install updates
```
/* 0301: disable auto-INSTALLING Firefox updates [NON-WINDOWS]
 * [NOTE] You will still get prompts to update, and should do so in a timely manner
 * [SETTING] General>Firefox Updates>Check for updates but let you choose to install them ***/
user_pref("app.update.auto", false);
```

**Comment by Kein** [comment]
> So what is it you want - to auto update or not?

I want to disable auto-update and disable the nagging pop-up. Current default situation in Firefox 9x is this:

1. Either you have auto-update enabled and it will do it automatically, given the chance and will update/reinstall firefox
2. You set update to "Notify" , there is no disable - in this case every X second the annoying poo-up will notify a new update is available

There are no known user.js directive or policy that can prevent it, when I say "no known" - I'm talking about every single one I've tried which I found on the internet with 1 year actuality results,

> What is your OS? How did you install firefox, is it portable, a flatpack, install? If you click update does it update for you?

1. Windows 10
2. Manual extraction of the distributive, call it "portable"  
3. Yes it will update

Policies.json is in `./Firefox/distribution/` and appears to be read.

**Comment by Thorin-Oakenpants** [comment]
So I was right - you want to disable auto-update AND not be prompted

arkenfox doesn't change the auto-update setting for windows, _and can't since FF65+_ - portableapps FF I think makes sure auto-update is off on each new profile. Regardless, on windows you need to do it manually in settings

On windows - the info on updating is kept in an update.json file, one for each firefox "instance" (not per profile, but per FF)
- in here: `C:\ProgramData\Mozilla\updates` (but nightly just moved the location of theirs)

That's to enable auto-updating which wold remove the prompt

---

To remove the prompt (which only happens if you don't auto update) on windows you need policies. AFAIK it does not work on portable (I have never used it, so I'm not sure if it's even limited to ESR)

At the end of the day, the answer is to update. Why are you not updating? (rhetorical question)

**Comment by Kein** [comment]
> Why are you not updating?

I prefer to have control and update on my own pace and need.

> To remove the prompt (which only happens if you don't auto update) on windows you need policies. Enterprise Policies is out of scope for this repo

Already went through all of them - none affect the prompt.

**Comment by Thorin-Oakenpants** [comment]
Take it up with Enterprise Policy, this is not an arkenfox problem
