### ISSUE TITLE
Can't joins experience/games in roblox.com

### ISSUE THREAD

**Issue by SwiftyPop** [arkenfox/user.js#1319]
# Steps to Reproduce (STR)
You need an account to join one. Go to one of the experience/games for example, [this one](https://www.roblox.com/games/443406476/Project-Lazarus-ZOMBIES-M26-MASS) and when you click the "Play" logo button. I got this error
![firefox_QVixOOzdSl](https://user-images.githubusercontent.com/90952326/147903639-13d7bd47-6265-4b9f-8358-2bfb342cb092.png)
I do check the console and this is what I got:
![firefox_scnt5DOCgi](https://user-images.githubusercontent.com/90952326/147903740-55cbcda8-25f7-499e-816e-3cac97f15367.png)
I'm pretty sure it's arkenfox fault as Firefox with different profiles and Librewolf working just fine. I don't think it's my overrides( I only have homepage enabled and letterboxing disabled in the overrides) fault either. Is there any info I should be giving? Do you guys know what caused this? 

# Expected Results
It will ask you to open Roblox and you will get into the game
![brave_5F8pACxeno](https://user-images.githubusercontent.com/90952326/147903985-f2c48525-806c-4fb5-823e-1803bba856ce.png)

# Browser version
Firefox 95.0.2

**Comment by kolva3** [comment]
* 0=always (default), 1=only if base domains match, 2=only if hosts match
* [SETUP-WEB] Known to cause issues with older modems/routers and some sites e.g vimeo, icloud, instagram ***/
user_pref("network.http.referer.XOriginPolicy", 2);

**Comment by Thorin-Oakenpants** [comment]
So Librewolf is working. We don't have much different
- try resetting FPI (to see if it's the cause and then toggle it back on)
  - we will be changing from FPI to dFPI next version, but it requires you to redo your site exceptions
- not sure what LW has for referers, try resetting
   - `network.http.referer.XOriginPolicy` <-- more likely
   - `network.http.referer.XOriginTrimmingPolicy` <- less likely

Otherwise, you will need to troubleshoot it - start with the [SETUP-WEB] tagged items

**Comment by fxbrit** [comment]
> not sure what LW has for referers

`network.http.referer.XOriginPolicy` = 0

**Comment by SwiftyPop** [comment]
@Thorin-Oakenpants Setting the `network.http.referer.XOriginPolicy` to 0 and 1 seem to fixed my issue. Thanks!
