### ISSUE TITLE
302 `app.update.background.scheduling.enabled` still in use?

### ISSUE THREAD

**Issue by yokoffing** [arkenfox/user.js#1325]
https://github.com/arkenfox/user.js/blob/06b8d8bfa3a8fd63083be4aaa1afbe0d21df8814/user.js#L143-L146

This is not an option in `about:config` for Firefox Nightly 97 and Beta/Dev 96.

If it is a pref the user needs to create, then we should add `// [HIDDEN PREF]` to the end.

**Comment by rusty-snake** [comment]
> /* 0302: disable auto-INSTALLING Firefox updates via a background service [FF90+] **[WINDOWS]** 

Do you use Windows?

**Comment by yokoffing** [comment]
> Do you use Windows?

Yep. I was on my Windows 10 machine when I was looking into this.

**Comment by rusty-snake** [comment]
Onl appearance in firefox' code base (without system extensions?):

```js
    // To be thorough, remove any traces of the pref that used to control the
    // default value that we just set. We don't want any users to have the
    // impression that that pref is still useful.
    Services.prefs.clearUserPref("app.update.background.scheduling.enabled");
```

https://searchfox.org/mozilla-central/source/toolkit/mozapps/update/BackgroundUpdate.jsm#340

**Comment by Thorin-Oakenpants** [comment]
this was already on my radar. it's difficult, because I use portables. I do have two installed (Beta, Nightly) and I don't install any maintenance services etc - and there have been changes happening in the last several releases, ongoing

I don't actually thing the pref does anything anymore, toggling the UI changes a different pref `app.update.background.previous.reasons` which would be runtime

I think the pref to actually use is `app.update.background.enabled`

**Comment by Thorin-Oakenpants** [comment]
nightly 97 + beta 96 (both installed) and dev (portable) have the following
- i.e the setting is present
- ![nightly97installed](https://user-images.githubusercontent.com/16656956/148699683-10de9837-579a-4dcf-9182-bf43b8b2470f.png)
- ![dev96portable](https://user-images.githubusercontent.com/16656956/148699696-0814e101-eafe-4a02-b205-ee291076920c.png)

FF95, 94, 93 (all portables) do not that the setting: I will need to check back to when I added it and follow the bugzillas down the rabbi hole - maybe the UI is/was dependent on the release channel

It's weird because I always check settings exist: but maybe I added this before stable and relied on dev/beta/nightly

**Comment by Thorin-Oakenpants** [comment]
This will be covered in FF95-FF96 diffs

In FF96+ there are four combinations (windows users) of the two values
- note the background update is a sub-item
- I will call them on and off

do not exist in about:config
- app.update.background.scheduling.enabled
- app.update.background.enabled

four combos
- A: default
  - on + on
  - `{"__DEFAULTS__":{"app.update.background.enabled":true}}`
- B: portable default (or at least a portable that updates)
  - off+on
  - `{"__DEFAULTS__":{"app.update.background.enabled":true},"app.update.auto":false}`
- C: user manually unchecks subitem before unchecking parent
  - off+off
  - `{"__DEFAULTS__":{"app.update.background.enabled":true},"app.update.background.enabled":false,"app.update.auto":false}`
- D: user just wants to stop background updates
  - on+off
  - `{"__DEFAULTS__":{"app.update.background.enabled":true},"app.update.background.enabled":false}`

In all the above tests, the ONLY difference in prefs between ALL four of them is
- `app.update.background.previous.reasons`

---

case B is cosmetic, and if the user already has to manually change update settings in windows, then the sub-menu item can be done at the same time

The only thing left that I want to test is what the hidden pref `app.update.background.enabled` does when run from user.js

**Comment by Thorin-Oakenpants** [comment]
app.update.background.enabled = false: test from about:config and from user.js

setup config to be no auto-installs but the submenu item for background is dimmed out but checked
- added via about:config: does not change UI or JSON
- added via user.js does not change UI or JSON

So the background update is the same as `app.update.auto` on windows - i.e the user must do it manually and the settings are stored on disk (per firefox)

closing, the pref in OP is deprecated in FF95-FF96 diffs, will do it there

**Comment by Thorin-Oakenpants** [comment]
ugh, I guess I forgot to post this
- yes the pref still works and yes the UI exists
- it's just that the pref also controls the UI - the commit above tidied the description

Here's FF95 and I also checked ESR91
![UI](https://user-images.githubusercontent.com/16656956/149069556-29b420a9-c550-4e54-a2a9-320a4a454816.png)

**Comment by crssi** [comment]
> C: user manually unchecks subitem before unchecking parent
> 
>     * off+off
> 
>     * `{"__DEFAULTS__":{"app.update.background.enabled":true},"app.update.background.enabled":false,"app.update.auto":false}`

@Thorin-Oakenpants  is there a "typo" in  `{"__DEFAULTS__":{"app.update.background.enabled":true},"app.update.background.enabled":false,"app.update.auto":false}`, I mean this part or array `{"app.update.background.enabled":true}`

**Comment by Thorin-Oakenpants** [comment]
there is no typos, the values were copy pasted from the JSON file
