### ISSUE TITLE
privacy.window.maxInnerWidth

### ISSUE THREAD

**Issue by TommieWong** [arkenfox/user.js#1329]
Hi all,
So I recently switched to Arkenfox and I am slowly finding my way through. Among the few issues that stick out for me is the size of the browser window at startup.

To be clear:
- I have read and am using the override recipe at https://github.com/arkenfox/user.js/issues/1286 for #4502 (also read related issues);
- I have privacy.resistFingerprinting and privacy.resistFingerprinting.letterboxing set to true and I am fine with the letterboxing itself;
- I am on mac with a screen res of 2560x1600;
- my browser window is not maximised nor full-screen;
- I have used TZP to check my inner window size.

What I want is to open the window larger than the current inner size of 900x700 so as not to have to resize it manually.
My issue is that, regardless of the values I enter in the override settings, I cannot seem to have FF open as big as it could -- which TZP reports as an inner window size of 1100x700.
I have slowly increased the override settings from 1600x900 to 2200x1400 (double the goal of 1100x700), but the largest that it opens is 900x700 (at 1600x900, if I recall correctly, it opens at 700x700).
I even tried to quickly math it out. If a value of 1600x900 (16/9 ratio) gives me 700x700 (ratio of 1), then a 11/7 ratio should be obtained by something like 2515x900 (ratio of 2.7 something). But no, it still opens at 900x700.

Not sure what to do at this point. Anything I'm missing?
Thx
Tom

**Comment by Thorin-Oakenpants** [comment]
forget about aspect ratios, that is just a consequence/fact of width/height. With RFP we are stuck with new window sizes, but at least we can bump the width up to make websites more usable (I mean in developer edition, the settings UI gets a horizontal scrollbar FFS) and not serve mobile pages etc

you also can't get what you want, aspect ratio wise, when values are rounded. The aspect ratio is not what is being protected by RFP

---

you haven't given any actual values you used with their respective results.

Do the following
- open about:config and toggle `privacy.resistFingerprinting.letterboxing` = false
- open another tab and in about:config toggle `privacy.resistFingerprinting` = false
- open another tab and go to TZP
- go maximized (not full screen) and copy or write down the four screen/window metrics
- see example pic (I wasn't maximized it was to show you what info I want)
- ![example](https://user-images.githubusercontent.com/16656956/149562143-bb664999-a47e-408d-ae50-7642081b8e2c.png)
- close TZP
- reset the two prefs in the two open tabs back to true

Post me the results

**Comment by TommieWong** [comment]
Thanks for the reply. Indeed, all the values I gave were the ones with resist.fingerprinting activated. 
Here are the results you asked for:
- screen resolution  ● | 1440 x 900 [sizes match x4]
- available resolution  ● | 1385 x 875
- outer window  ● | 1384 x 875
- inner window  ● | 1168 x 790
When I reset the prefs to true, all four values return to 1100x700.

**Comment by Thorin-Oakenpants** [comment]
> I am on mac with a screen res of 2560x1600;

What makes you think your screen res is `2560 x 1600`? JS and Firefox is saying it's `1440 x 900`

**Comment by Thorin-Oakenpants** [comment]
you have a native resolution of 2560x1600 ... that's not the same as your actual resolution, it's scaled (or you have changed `layout.css.devPixelsPerPx` and/or both)

I don't use macs, but there must be a setting or info somewhere that tells you this info

**Comment by Thorin-Oakenpants** [comment]
so, to answer your original question
- inner window ● | 1168 x 790
- when maximized this shows the most room for the inner window you have is 1100 x 700 (when rounded down)

**Comment by TommieWong** [comment]
Well, thanks, but that's the part I already knew. The problem I have is that I cannot manage to have FF open at those dimensions. When I enter 1100x700 as my values, it opens at 700x700. When I set higher values, the largest window I get is always 900x700.. I get that it would not open maximised to occupy all the screen, but I would at least want it to open at the max inner window size, which it never does.

**Comment by Thorin-Oakenpants** [comment]
do you have the sidebar showing, are you using a tiling manager?

**Comment by TommieWong** [comment]
Yes, I use Sidebery, to make up for the lack of vertical tabs. Once again, and to be clear, I've made my peace with 1100x700 if that's the most I can get with my sidebar and top bars and all. What I want to avoid is having to always resize the window manually, and I simply cannot get FF to open at those dimensions.

**Comment by Thorin-Oakenpants** [comment]
I don't use macs, sorry. And you make everything so confusing

1100x700 is the most you can get, fine, good, we _already_ established that.

Stop fucking changing the pref values. If they're at 1600 x 900 and the best you can do is lower than that, then leave them alone

What you said was that you were getting **_900_** x 700 (instead of 1100 x 700).

Do you use Tor Browser. What do you get if you use Tor Browser? What do you get if you use 1000x1000 (which is the default) which is what Tor Browser uses

WTF is sideberry? 

Post a screenshot of the entire desktop so I see what the heck you are talking about (block out anything personal)

@fxbrit

**Comment by fxbrit** [comment]
> WTF is sideberry?

https://addons.mozilla.org/en-US/firefox/addon/sidebery/

> 1100x700 is the most you can get

how was this determined? macos has a ton of UI elements that take away what one would consider to be available screen (topbar, dock etc). it's possible that the window doesn't have enough space to stretch above 700x700 because of the macos app dock for example.

@TommieWong try hiding the dock with `cmd + option + d` then open a new window and see how the size changes.

**Comment by Thorin-Oakenpants** [comment]
> how was this determined

the values reported when maximized and RFP and LB were off
- screen resolution ● | 1440 x 900 [sizes match x4]
- available resolution ● | 1385 x 875
- outer window ● | 1384 x 875
- inner window ● | 1168 x 790

So
- screen vs available : `55 x 25` pixels eaten out of screen by IDK cuz I don't use macs
- outer vs available: `1px` width cuz why not, probably a border
- outer `1384 x 875` minus inner `1168 x 790` = chrome of `216 x 85`
   - the 85px height is the toolbar/urlbar
   - the 216px width will be the sidebar (which is why I asked)

So we end up with 1168 x 790 max for the inner, which rounds down

So IDK why tommie can only achieve 900, which is why I asked if there was a tiling manager or something

On Tor Project I just tell people to post a screenshot, at least that way I can see everything and even measure it

**Comment by Thorin-Oakenpants** [comment]
Get more height: 790 is so close to 800 .. you could use compact mode :)
- browser.compactmode.show - true
- toolbar > right click > customize > density > compact
- on windows it frees up 19px from normal mode

**Comment by TommieWong** [comment]
That's weird, I thought that was all pretty clear. Anyway, I'm on my way out so I'll the other message soon. In the meantime, here are the screen caps you asked for.
FF with 1600x900; this is 900x700.
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/97629645/149624200-b1fac2cf-0555-42b7-b5e4-0d28ed70fcb7.png">
FF with 1600x900 after manually extending; this is 1100x700.
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/97629645/149624204-c184e4c7-8fb4-468e-a5c9-19e9588e64c7.png">
FF with 1000x1000.
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/97629645/149624205-21f1c6e7-af64-4daf-a672-690cf784bb7b.png">
Tor.
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/97629645/149624207-72b8da3d-9f06-4a2e-af40-6c18081ab08b.png">

**Comment by Thorin-Oakenpants** [comment]
OK, so point one:
- width is rounded in 200's (when it exceeds 1000) so your max width is 1200 (without the sidebar) or 1000 (with sidebar)

**Comment by Thorin-Oakenpants** [comment]
issue one, and my bad for not remembering. LBing and new window sizes do not have identical stepping
- width is _**always**_ in 200s

here's the user.js
https://github.com/arkenfox/user.js/blob/7a4676fe2dcb5bf55974b5cbc82f8353114175d3/user.js#L898-L902

maxwidth (LB off to measure the real inner window)
```
-     < 600 =  454 (minimum at least on windows: chrome elements prevent further shrinking)
-  600- 799 =  600
-  800- 999 =  800
- 1000-1199 = 1000
- etc
```

To test, you don't need to close Firefox, just open a new window
- that's about:config searching for `privacy.window.max` (Height on top, Width below)
- ![maxwidths](https://user-images.githubusercontent.com/16656956/149643642-c451c741-45c7-4a67-b3a1-cf0c0b444888.png)
 
So that clears up one misconception (which again, I should have already noted)

**Comment by Thorin-Oakenpants** [comment]
Here's what's happening, see pic
- you have 1440 width
- the docker reduces the available space to 1385
- the pic is default maxWidth as `1000`, (at AF's prefs the maximum you could get is 1200 (1385 rounded down in 200s))
- so the new window opens at 1000 wide (or 1200 wide with AF's prefs)
- the new window is then eaten into by sideberry (which happens to be just over 200)
- this leaves the inner window with 785 pixels (or 985 with AF prefs)
- Letterboxing which works in 100s at this scale, drops the inner _viewport_ to 700 (or 900 with AF prefs)

<img width="1440" alt="measure" src="https://user-images.githubusercontent.com/16656956/149644081-a6a0a91b-6035-4d8e-838e-fac6a6a77c36.png">

So as you can see, being just under a multiple of 200 available width, and the sidebar being just over a multiple of 200, (and height being just under a multiple of 100), you end up with less real-estate than you could

**Comment by Thorin-Oakenpants** [comment]
solutions
- move docker to bottom? IDK = instant 200px hit
- resize sidebar to 200 (or fractionally under) - just resize it while in TZP and stop when the inner size jumps = instant 100px hit

That's a 300px improvement

**Comment by TommieWong** [comment]
Thanks a lot for all that, @Thorin-Oakenpants. Clears up a lot of points. I'll see what I can do to improve.
