### ISSUE TITLE
Multiple Profiles Some Won't Run Prefscleaner

### ISSUE THREAD

**Issue by DanitiKain** [arkenfox/user.js#1332]
v. 96.0.1

I have been using user.js for a while I notice on some of my profiles I have to manual run prfescleaner.bat after I run updater.bat.

I have tried copying the update.bat from the profiles where I don't have to do this. I have also made sure prefscleaner.bat and .sh are in place.

I have even copied everything over from the profile where this works and into the one that doesn't work and still doesn't run it automatically. 

Any ideas?

**Comment by DanitiKain** [comment]
I realized I wasn't supported to be moving prefs.js around.

**Comment by Thorin-Oakenpants** [comment]
> I have to manual run prfescleaner.bat after I run updater.bat

sorry for the delay. What makes you think the updater script runs prefsCleaner? They are two separate scripts

> I realized I wasn't supported to be moving prefs.js around

prefsCleaner should be placed and run in the root of each profile directory where prefs.js is kept. I do not understand what you mean by "moving prefs.js"

**Comment by DanitiKain** [comment]
I guess my only real question is do I need to run prefs cleaner after every update.bat that I run?

**Comment by Thorin-Oakenpants** [comment]
Starting in v97 on, I am going to do all commits in a PR, so the updater will only get new versions when I do a final new version - rather than multiple live commits over the course of an alpha version

In each version, items can get removed, or made inactive or deprecated. Deprecated ones don't really matter (because they do nothing), but generally speaking the others are important as they could interfere (but I'm careful to always counter that such as changing the value and leaving it active, i.e not commented out) - long story short: it is always best to run prefsCleaner, as this saves you doing things manually and keeps things tidy (and less troubleshooting etc)

Several releases ago, I started keeping "removed" items in the user.js (number 6050), so that everything is covered

So yeah, updater, with your changes in an overrides file, then prefsCleaner - every time 100% it's the only way to fly baby! - I'm rewriting the wiki to make this all as clear and simple as possible

**Comment by earthlng** [comment]
> What makes you think the updater script runs prefsCleaner? They are two separate scripts

FYI: IF the prefsCleaner exists in the profile folder, the Windows updater script will offer to run it

**Comment by Thorin-Oakenpants** [comment]
Ahhh, thanks @earthlng . But can it do it _automatically_ ? BTW I want to update the updater wiki page so the windows examples use generic prefs rather than real ones
- would you like to do it?

**Comment by earthlng** [comment]
you mean the prefs used as examples for how the `-merge` option works? If so, IMO it makes more sense to use real prefs instead of generic ones. I'd leave it as-is

**Comment by earthlng** [comment]
> But can it do it _automatically_ ?

No. All it does, is offering to run it - and only *if* the user.js actually changed, see [code](https://github.com/arkenfox/user.js/blob/master/updater.bat#L199-L209)

**Comment by Thorin-Oakenpants** [comment]
yes, those ones. If I use generic ones then they won't get out of date, and most of those ones are. Elsewhere I have used e.g.
```js
user_pref("pref.name.example", "purple")
user_pref("pref.name.string", "i am a string");
user_pref("pref.name.boolean", true);
user_pref("pref.name.integer", 0)
```

I just think to be consistent and not worry about upkeep/professionalism we could use generic terms. And especially, I do not want users thinking these are valid up-to-date prefs that can be used

**Comment by earthlng** [comment]
IMO it's easier to understand with real prefs (especially since those 4 prefnames are all pretty self-explanatory)

**Comment by Thorin-Oakenpants** [comment]
that's probably true, but it's still not hard to understand. I'm too fussed about that so much as making it so I never have to look at it again

So if we use real ones, then we should use ones that won't move (change number) and will never change (values or active state)

do you want to give it a go?
