### ISSUE TITLE
Firefox Addon Missing in Search Results

### ISSUE THREAD

**Issue by DanitiKain** [arkenfox/user.js#1333]
v. 96.0.1
I have firefox installed on a laptop without user.js and on a desktop with it.

Desktop: user.js settings enabled
1. Go to addons.mozilla.org
2. Search: multi-account = no results
3. If I go direct to the link where multi account containers is it says you need an updated version of firefox for this extension
4. help > about  shows firefox is up to date and version is 96.0.1

Laptop: users.js no installed more of a fresh copy of mozilla
1. Go to addons.mozill.org
2. Search: multi-account = results show and I can install

**Comment by Thorin-Oakenpants** [comment]
The search results and the warning are because mozilla is only showing compatible results - RFP is lying about your version (as 91) and MAC requires 94+ or something due to them integrating Mozilla VPN

https://addons.mozilla.org/firefox/addon/multi-account-containers/
 - You can just bypass it by clicking download file

**Comment by m77e4t** [comment]
Same thing happened to me :) 
Spent 5-10 minutes finding the extension via search function on add-on site, then found it via normal search engine. Afterwards, I could not download it as it said non-compatible firefox version. 

Downloaded the extension as Thorin mentioned and it worked.

**Comment by Thorin-Oakenpants** [comment]
RFP no longer spoofs version on desktop FF102+
