### ISSUE TITLE
Questions regarding ETP Strict mode and privacy addons

### ISSUE THREAD

**Issue by adrian5** [arkenfox/user.js#1344]
I have ETP Strict enabled and also clear cookies each shutdown (presumably `network.cookie.lifetimePolicy = 2` ?). I manually whitelist domains which may store persistent cookies.

With the above and **T**otal **C**ookie **P**rotection in mind, is there any use for:

* [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/)?
  - This addon can "block" blacklisted domains (mostly trackers) from loading within a page; is that still something of value privacy wise, e.g. not even sending those requests from my IP? When it comes to cookies, I reckon trackers could only set & read their own (transient) ones, which is probably useless for them.
* [Firefox Multi-Account containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)?
  - I only used this for privacy — e.g. keeping my Google accounts separate from regular browsing — never to manage multiple logins on the same domain. Can I get rid of the addon in that case, since most cookie domains should be contained via _TCP_?

Thank you.

**Comment by Thorin-Oakenpants** [comment]
PB is redundant
- who cares if a tracker loads (Tor Browser don't care) .. it does not negate the fact the partitioning is protecting cross-domain sharing
- it has a very minimal static list
- it can learn but to do so means it becomes detectable (not that I think sites are going to test this)
- for bigger impact you already have uBO which is a content blocker (not a tracker blocker) which brings extra benefits, such as removing ads and the attack surface that brings, levels of modes/configs, and things like query param stripping

MAC
- redundant in your case
- > since most cookie domains should be contained via TCP
   - cross domain logins still require relaxing first party, but it's not what you think, see example

example
- you login to SiteA using PartyC
   - PartyC is now it's own first party
- you visit SiteX, SiteY and SiteS
   - all these sites PartyG is isolated to the first party and cannot talk to each other, nor to the one on SiteA
- you login to SiteB using PartyC
   - PartyC is now it's own first party and is the same one used on SiteA = links traffic
   - this is not a problem, because you chose to allow/use PartyC

So lets say you use google to login into youtube and gmail. Even if you isolated those two sites and the google SSO from each other, google still knows - that's what a SSO (single sign on) is - a single point of authentication

**Comment by adrian5** [comment]
Thank you for the clarification Thorin, and thanks for maintaining this project!
