### ISSUE TITLE
I Made a Script for Arkenfox

### ISSUE THREAD

**Issue by thatfatblackcat** [arkenfox/user.js#1358]
Hello everyone, I just wanted to let you know I'm maintaining a script called [`userjs-dl`](https://github.com/thatfatblackcat/programs).
I just released version 2.0 and I'd like to know what are your thoughts.

The script is only 35 lines and it does the same things `updater.sh` and `cleaner.sh` do but better.
You can run it manually when you feel like updating or from the crontab periodically (eg. each 15 min).

However there's a caveat, if you want to customize your profile you need a patch file.
The script treats every prefs except browser UI and extensions as temporary.

If you need an example there's a file named `user.js.diff` on my repo under config.
Here you can learn [where your data is stored](https://support.mozilla.org/en-US/kb/recovering-important-data-from-an-old-profile).

This script wouldn't have been possible without Arkenfox, thank you so much.
Try out `userjs-dl` see if it's for you and report bugs if there are any (make a backup, just in case).

**Comment by rusty-snake** [comment]
FWIW, I made another updater too: https://codeberg.org/rusty-snake/firefox-config/src/branch/main/assets/updater2.sh

It just
1. creates a backup of the current user.js
2. downloads the master arkenfox user.js
3. uncomments prefs listed in `user.js_prefs_to_uncomment.txt`
4. appends user-overrides.js

**Comment by thatfatblackcat** [comment]
My script is POSIX compliant and it doesn't have bash/zsh/dash as a dependency.

**Comment by xfzv** [comment]
> FWIW, I made another updater too: https://codeberg.org/rusty-snake/firefox-config/src/branch/main/assets/updater2.sh
> 
> It just
> 
>     1. creates a backup of the current user.js
> 
>     2. downloads the master arkenfox user.js
> 
>     3. uncomments prefs listed in `user.js_prefs_to_uncomment.txt`
> 
>     4. appends user-overrides.js

Thanks for sharing. Two noob questions:

1. Why step `3.` instead of adding the preferences to `user-overrides.js` (which you also use)? I don't understand why you split the process in two parts but I'm sure there's a good reason for that, I'm curious to know.

2. Considering you directly edit `user.js`, can you still run `prefsCleaner.sh` after each update as usual without any issue?

**Comment by Thorin-Oakenpants** [comment]
> You can run it manually when you feel like updating or from the crontab periodically (eg. each 15 min).

since each release is done in it's own branch and only merged at the end, this is now pointless

Keep chatting, I'm going to unsubscribe and close

IDCare what people do - e.g. edit the actual AF file, run diffs, add their own notes, run cron jobs that play tada and tadum sounds, or whatever, run special items like uncomment a list, flip switches, replace "Firefox" with "GODZILLA", etc - and there are many ways you can handle updates - but the only thing I am going to support is overrides file (not even happy about more advanced updater options)

**Comment by rusty-snake** [comment]
> Two noob questions:
> 
>     1. Why step `3.` instead of adding the preferences to `user-overrides.js` (which you also use)? I don't understand why you split the process in two parts but I'm sure there's a good reason for that, I'm curious to know.
> 
>     2. Considering you directly edit `user.js`, can you still run `prefsCleaner.sh` after each update as usual without any issue?

1. Personal decision. I prefer it to just set the inactive (setup-harden) prefs that I use to active instead of copy&paste them.
2. I don't use prefscleaner but there shouldn't be any issue.
