### ISSUE TITLE
Pop up window issue

### ISSUE THREAD

**Issue by Leonis87** [arkenfox/user.js#1368]
Hi,
So I was able solve almost all websites breakage. Firefox working very fast now. I'm just experiencing little problem with one chat website. When I get personal message and click on it, that popup window open on full screen. I don't know how to explain exactly, basically size of that window should be about only quarter of screen but with arkenfox that personal message popup window is opened on full screen. I tried change some preferences, header, referer... RFP, even disable addons. Nothing worked.

**Comment by crssi** [comment]
``` js
/* 4513  */ user_pref("browser.link.open_newwindow.restriction", 2);
```

**Comment by Thorin-Oakenpants** [comment]
please clearer and follow the instructions for logging an issue

full screen is when the browser "window" uses the entire screen and hides the toolbars/urlbar etc
maximized is when the browser is using the whole screen, sans task bars

if I understand you correctly, what you are saying is you have a browser window at say size X (big) and normally when you click the chat invite, it pops up a small chat window as a NEW window - new window being you can drag it around

as crssi says, we restrict all _types_ of "new windows" to instead open in a new tab (to prevent malicious window sizes) - try overriding `4513`

if that doesn't work or the issue is not what I think it is, then reopen and explain more

**Comment by Leonis87** [comment]
Thanks guys :) It does work correct now. How could I missed this preference I don't know. I spent 2 days on this :) Thanks

**Comment by Thorin-Oakenpants** [comment]
it's going to be deprecated soon to something like this - https://bugzilla.mozilla.org/1714939

```js
// THIS IS JUST A MADE UP NON-FINAL SAMPLE LEARN TO READ PEOPLE
/* 2404: set popup windows requested by window.open() to open in a new tab [FF99+]
 * 1=pop-up windows, 2=normal windows, 3=tabs
 * [SETTING] Privacy & Security>Permissions>Open allowed pop-up windows as
    ^^ might end up in >Popups>Exceptions>Open allowed pop-ups as...
 * [temp ref] https://bugzilla.mozilla.org/1714939 ***/
   // user_pref("dom.window.open.popup", 3);
   // user_pref("dom.window.open.popup.override", true);
```

**Comment by Thorin-Oakenpants** [comment]
actually ... I didn't think of that -> [SETTING] Privacy & Security>Permissions> Exceptions

you can also go ctrl-i when on the site, click permissions tag, and change the "open pop-up windows" option from use default to `Allow`

i.e instead of loosing new window protections universally
