### ISSUE TITLE
Changing Timezone

### ISSUE THREAD

**Issue by Loki-L1130** [arkenfox/user.js#1375]
How about a UserPref to make a default Timezone in Firefox which changes the Timezone from the system ones

**Comment by rusty-snake** [comment]
What do you even want? A new pref that overrides the timezone? Then go to bugzilla.mozilla.org.

**Comment by crssi** [comment]
Because is packed into
https://github.com/arkenfox/user.js/blob/ba052105de3c4be2e34cf103f08b2f28c6d5b496/user.js#L899-L903

and `privacy.resistFingerprinting` is all or nothing. Thorin said that numerous time and understandable will not say it again and again... I guess.

I also struggle with and I always need to calculate what time is, but it is as it is.
