### ISSUE TITLE
uBlock Origin Double CTRL (filterAuthorMode) not working after applying user.js

### ISSUE THREAD

**Issue by BwntyHntr** [arkenfox/user.js#1394]
🟪 REQUIRED INFO
  - Browser version & OS: V98 Arch Linux
  - Steps to Reproduce (STR): Double click CTRL to access allow(green option) in uBlock Origin.
  - Expected result: 3 options appear instead of two should appear.
  - Actual result: when clicking CTRL twice, nothing happens.
  - Console errors and warnings: No errors or warnings
  - Anything else you deem worth mentioning:
I've tested it on the unmodified profile, and it worked fine, perhaps it's a known issue and is fixable, but I'm not aware (I did read the troubleshooting and found nothing)
If I enable filterAuthorMode in advanced settings (set to true) it works as default.

**Comment by Thorin-Oakenpants** [comment]
[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI

---

you didn't check the box that says you read the troubleshooting guide, and did the checks

I do not understand
- Double click CTRL .. what does this mean? Are you talking about the keyboard?
- Expected result: 3 options appear instead of two should appear - where, what? huh?

It might be easier if you provide a screenshot or expected vs actual

**Comment by Thorin-Oakenpants** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules

> The only way to enable the ability to point-and-click to create allow rules is to either:
> 
> - Tap twice on the Ctrl key while in the popup panel
>    - This won't work in Firefox when privacy.resistFingerprinting is set to true
> - Set filterAuthorMode to true in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings)
