### ISSUE TITLE
Firefox Sync Not working

### ISSUE THREAD

**Issue by xsharex** [arkenfox/user.js#1400]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS:  FF 98.0.1
  - Steps to Reproduce (STR):  Install Arkenfox + User.js. 
  - Expected result:  I would expect Firefox Sync to work,
  - Actual result:  I am able to login. But the login page show only profile related information. No option to sync
  - Console errors and warnings:
  - Anything else you deem worth mentioning:
           What config settings disable sync?. How do I enable it?  Can a note be added to User.js indicating the setting that will disable it?

Thank you very much

---

**Comment by Thorin-Oakenpants** [comment]
works for other people - e.g. #1175 - just checking that you really did try this on a new profile with no other changes and no extensions

I don't use sync and don't know the exact ins and outs of how it works - I'm looking at the pics here: https://www.groovypost.com/howto/sync-firefox-across-all-devices/

we use session cookies (which blocks service workers) - you may need to add `accounts.firefox.com` as a site exception (as `Allow`) in manage cookies and site data so that nothing storage wise is blocked

**Comment by fxbrit** [comment]
I just tested on my Nightly install with stock AF user.js and it works perfectly.
