### ISSUE TITLE
Use updater and prefsCleaner via symlinks

### ISSUE THREAD

**Issue by sjoblomj** [arkenfox/user.js#1403]
Thanks for an awesome project!

I would like to put the files of this repo in one place, and then create symlinks to the scripts in my firefox profile, like this:
```
$ ls -la ~/.mozilla/firefox/q0bo75s1.default-release/*.sh
lrwxrwxrwx 1 jj users 45 Mar 22 17:28 /home/jj/.mozilla/firefox/q0bo75s1.default-release/prefsCleaner.sh -> /home/jj/bin/arkenfox/user.js/prefsCleaner.sh
lrwxrwxrwx 1 jj users 40 Mar 22 17:28 /home/jj/.mozilla/firefox/q0bo75s1.default-release/updater.sh -> /home/jj/bin/arkenfox/user.js/updater.sh
```

This approach won't work (as is pretty clearly stated in the scripts), because the scripts need to be placed in the profile directory, and a symlink doesn't seem to do it. With the following changes, however, it works on my Linux machine. It seems like the `readlink` / `greadlink` construction is there for a reason though, but I fail to see why.

So my question is, does the following have a downside that I don't see? If not, I'm happy to make a proper pull request of it, so that symlinks can be used which allows for more flexible placement of this repo on the users machines. Perhaps @overdodactyl or @earthlng can shed some light?

```
diff --git a/prefsCleaner.sh b/prefsCleaner.sh
index 7db9ef0..a5d1b4e 100644
--- a/prefsCleaner.sh
+++ b/prefsCleaner.sh
@@ -8,14 +8,8 @@
 
 currdir=$(pwd)
 
-## get the full path of this script (readlink for Linux, greadlink for Mac with coreutils installed)
-sfp=$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || greadlink -f "${BASH_SOURCE[0]}" 2>/dev/null)
-
-## fallback for Macs without coreutils
-if [ -z "$sfp" ]; then sfp=${BASH_SOURCE[0]}; fi
-
 ## change directory to the Firefox profile directory
-cd "$(dirname "${sfp}")"
+cd "$(dirname "$0")"
 
 fQuit() {
 	## change directory back to the original working directory
```

```
diff --git a/updater.sh b/updater.sh
index 74f378c..23c3af1 100755
--- a/updater.sh
+++ b/updater.sh
@@ -12,7 +12,7 @@ readonly CURRDIR=$(pwd)
 
 SCRIPT_FILE=$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || greadlink -f "${BASH_SOURCE[0]}" 2>/dev/null)
 [ -z "$SCRIPT_FILE" ] && SCRIPT_FILE=${BASH_SOURCE[0]}
-readonly SCRIPT_DIR=$(dirname "${SCRIPT_FILE}")
+readonly SCRIPT_DIR=$(dirname "$0")
 
 
 #########################
```

Related to #964 and #1150

**Comment by xfzv** [comment]
Linux user here: it seems to work just fine too on my end with these changes. I'm curious to know whether it would cause any issue.

**Comment by earthlng** [comment]
> It seems like the `readlink` / `greadlink` construction is there for a reason though, but I fail to see why.

The readlink stuff is there to make the script work with symlinks but the other way around from what you want to do, ie create a symlink fe on the desktop (fe named "update profile xyz") for an updater/prefscleaner in a particular profile.
It's like that because at the time we ported the script, this mimicked the code we already had in the Windows version.

It's probably more common on Windows (and perhaps Mac) to create shortcuts on the Desktop than on Linux and I think we decided that people who are more likely to have multiple profiles and may want to have the scripts in a central place, are also more likely to be able to change the scripts for their own purposes than someone (ie probably the majority) who just wants to have 1 or more links on the Desktop for easy updating.
Of course it'd be great if it could handle all the possible ways that people may want to use it but IDK if that's even possible.

> So my question is, does the following have a downside that I don't see?

I'm not really sure off the top of my head and I don't have time to extensively test it right now, but it may or may not work when the scripts try to update themselves and/or when those symlinks are called with a relative path. Maybe you can test it a bit yourself in weird ways and see if you can break it somehow.
I think `$0` is also more or less identical to `${BASH_SOURCE[0]}` (isn't it?) and we only use that as a last resort and I know for sure that there's definitely a reason for **that** even if I can't fully remember exactly what that reason(s) was, ATM :)

**Comment by remyabel2** [comment]
As an alternative to a symlink:

```
pushd "$HOME"/.mozilla/firefox/"$PROFILE"/
    ./updater.sh -s
    ./prefsCleaner.sh -s
popd
```

And this can easily loop over multiple profiles. No need to add additional logic to the script. I feel like the more workarounds/logic added for different use-cases may make the script more brittle overtime.

**Comment by xfzv** [comment]
> As an alternative to a symlink:
> 
> ```
> pushd "$HOME"/.mozilla/firefox/"$PROFILE"/
>     ./updater.sh -s
>     ./prefsCleaner.sh -s
> popd
> ```
> 
> And this can easily loop over multiple profiles. No need to add additional logic to the script. I feel like the more workarounds/logic added for different use-cases may make the script more brittle overtime.

I've never used `pushd` / `popd` before, and I don't understand how this is supposed to work as an alternative to symlinks.

Like OP, I have the user.js repository cloned locally on my machine and use symlinks for `updater.sh` and `prefsCleaner.sh`.

---

After removing symlinks:

```zsh
❯ pwd
/media/Data/repos/arkenfox-user-js

❯ ls updater.sh prefsCleaner.sh
prefsCleaner.sh  updater.sh

❯ pushd $HOME/.mozilla/firefox/my-profile
    ./updater.sh -su
    ./prefsCleaner.sh -su
popd
~/.mozilla/firefox/my-profile /media/Data/repos/arkenfox-user-js
zsh: no such file or directory: ./updater.sh
zsh: no such file or directory: ./prefsCleaner.sh
/media/Data/repos/arkenfox-user-js
```

How are `updater.sh` and `prefsCleaner.sh` supposed to be run since my Firefox profile directory is the first in the stack?

Also, could you please elaborate on how to make it loop over several profiles?
