### ISSUE TITLE
Help with overrides

### ISSUE THREAD

**Issue by EdwardLangdon** [arkenfox/user.js#1410]
So, I am currently trying to use `user.js` for the first time. I understand everything. Just writing my own `user-overrides.js` file. During that I found this bunch of prefs which seems overlapping. 

```js

\/* To keep cookies for Selected Sites via exceptions as Allow, see 2801 or this wiki entry ***/

/* override recipe: enable session restore ***/
  user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  user_pref("places.history.enabled", true); // 0862 required if you had it set as false
user_pref("browser.sessionstore.privacy_level", 0); // 1003 [to restore cookies/formdata if not sanitized]
  // user_pref("network.cookie.lifetimePolicy", 0); // 2801 [DON'T: add cookie + site data exceptions instead]
user_pref("privacy.clearOnShutdown.history", false); // 2811
  // user_pref("privacy.clearOnShutdown.cookies", false); // 2811 optional: default false arkenfox v94
  // user_pref("privacy.clearOnShutdown.formdata", false); // 2811 optional
user_pref("privacy.cpd.history", false); // 2812 to match when you use Ctrl-Shift-Del
  // user_pref("privacy.cpd.cookies", false); // 2812 optional: default false arkenfox v94
  // user_pref("privacy.cpd.formdata", false); // 2812 optional

/* - override recipe: keep some cookies + site data on exit ***/
    // user_pref("network.cookie.lifetimePolicy", 2); // 2801 [default 2 in user.js 94+]
    // user_pref("privacy.clearOnShutdown.cookies", false); // 2811 [default false in user.js 94+] 
    // user_pref("privacy.cpd.cookies", false); // 2812 Ctrl-Shift-Del [default false in user.js 94+]

// user_pref("privacy.clearOnShutdown.offlineApps", false); // 2811 [default false in user.js 95+]
// user_pref("privacy.cpd.offlineApps", false); // 2812 Ctrl-Shift-Del [default false in user.js 95+]

// user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
// user_pref("places.history.enabled", true); // 0862 required if you had it set as false
user_pref("privacy.clearOnShutdown.history", false); // 2803
// user_pref("privacy.clearOnShutdown.cookies", false); // 2803 optional
// user_pref("privacy.clearOnShutdown.formdata", false); // 2803 optional
user_pref("privacy.cpd.history", false); // 2804 to match when you use Ctrl-Shift-Del
// user_pref("privacy.cpd.cookies", false); // 2804 optional
// user_pref("privacy.cpd.formdata", false); // 2804 optional
```

What I want is AF can clear Cache on exit but should have Cache during session. Should not clear history because I will do that at the end of day using `Ctrl+Shift+Del` so, I can find things if I ever need it back. 

Cookies can be cleared except the ones listed in exceptions. I use ProtonMail in the Web AFAIK it uses local storage. So, clearing Site Data might break it.

So, Could you find what should I use from the above ?

I know this is not your Job. But I need some help in this regard. And don't close the issue faster.

**Comment by fxbrit** [comment]
from your description I'm under the impression that you only need:

```
user_pref("privacy.clearOnShutdown.history", false); // 2803
```

so that you can keep history and clear it manually on close.

> What I want is AF can clear Cache on exit but should have Cache during session.

> Cookies can be cleared except the ones listed in exceptions. I use ProtonMail in the Web AFAIK it uses local storage. So, clearing Site Data might break it.

this is all default behavior for this user.js.

**Comment by Thorin-Oakenpants** [comment]
too much noise - remove all the things that are now default in AF, and remove the duplicates and try again

> this is all default behavior for this user.js.

Exactly
- We already clear cache on close (not 100% sure if this includes other items like HSTS: I think they recently changed this) - but this is more of a fallback pref if users enable disk cache
   - > but should have Cache during session
   - what on earth makes you think cache is cleared during a session? We don't use disk cache, but it does exist in memory
- We already clear "cookies" on close (currently the lifetime pref) but allow for "cookie AND site data" exceptions (set "cookie" permission as `Allow`) ("cookies" here refers to cookies AND site data)
- We already do not clear "site data" on close
   - > `2811`: "offlineApps": Offline Website Data: localStorage, service worker cache, QuotaManager (IndexedDB, asm-cache)
   - this means that if you keep a cookie (as `Allow`) you also keep it's other data
   - this was done in https://github.com/arkenfox/user.js/commit/9d61992c8cc2a46fb58ea79866aced25e3574d9b (read the description) , also see #1291 

---

so everything you asked for is already the default .. except history, and that's up to you

`2811` - just override the clear history on close part
```
// keep my history
user_pref("privacy.clearOnShutdown.history", false);   // [DEFAULT: true]
```

`2812`- but don't change this one, because you said you wanted to do it manually (ctrl-shift-del)
```
user_pref("privacy.cpd.history", true);  // [DEFAULT: true]
```

**Comment by EdwardLangdon** [comment]
Thank You to @Thorin-Oakenpants , @fxbrit and @rusty-snake for helping me out.
