### ISSUE TITLE
Adding exceptions to RFP

### ISSUE THREAD

**Issue by EdwardLangdon** [arkenfox/user.js#1426]
From this [Reddit comment](https://reddit.com/r/PrivacyGuides/comments/t6ow6t/fixing_time_zone_with_resist_fingerprinting/hzn8rix/?context=3), I know that I can make exception while using RFP just for sites like Email.

```
user_pref("privacy.resistFingerprinting.exemptedDomains", "mail.protonmail.com"); (Example)
```

I think that this can be commented in user.js.

**Comment by rusty-snake** [comment]
Duplicated of #1279

**Comment by rusty-snake** [comment]
> I think that this can be commented in user.js.

https://github.com/arkenfox/user.js/blob/4ff931781a1bf012e0e7e2ec89dc5c2a9bedd890/user.js#L930-L934

**Comment by EdwardLangdon** [comment]
So, Waste of Time ?

**Comment by Thorin-Oakenpants** [comment]
my advice is to not use it, and wait for the final proper solution - because things may not work how they should - the answer is in the user.js and in the link to the bugzilla comment - how do you know the exemption works for you only on your exempted site, did you test?

you options
- can't use a secondary browser for your email
- use an extension
   - but only do it on a few whitelisted sites - IDK if an extension like that exists
   - extension spoofing will never be perfect but all it has to do is make your site work with your timezone, the fingerprinting leaks don't really matter, especially if you're logging in
   - i.e "lie" about your timezone as your real timezone, to counter the default RFP UTC0 bullshit one, because extensions have the last say

---

Tom Ritter, it is currently getting all the RFP checks parts everywhere to use fine grained checks, and he's got a summer school of code group or something where he can't do anything as he needs to let them do it as part of their assignments. And IIRC, timezone is a hacky one that probably needs a complete rewrite to use a different global/environment variable

But in an email, Tom said everything is otherwise pretty straight forward (or at least not as hard as he thought it would be) - but this is all on his own free time - since RFP is not currently on Mozilla's roadmap of priorities.

The prefs will probably get dumped in favor of a new pref and site exceptions and a ctl-i>permissions and the urlbar panel UI (like the canvas permssion)
