### ISSUE TITLE
[Not an issue] A question for using it with Burpsuite

### ISSUE THREAD

**Issue by behradJ** [arkenfox/user.js#1429]
Hi
at first, thanks for your awesome job for making this wonderful user.js file.
I was trying to set up a Firefox developer edition for just using it with burp suite for security testing, but I was wondering if using this user.js file will block some request that can be useful for me?
>The reason for using this file in this case is because Firefox makes a lot of requests, and it makes my burp suite proxy tab messy.

**Comment by Thorin-Oakenpants** [comment]
https://portswigger.net/burp

IDK. Try it.

I do not know all the things burpsuite does. Arkenfox tightens up privacy gaps in web protocols - so window.name (but this is now default), referers (by default we block em all), state partitioning is enabled (network partitioning is default, and total cookie protection is slated to become default very soon - not to mention other browsers like Brave have already started implementing more state partitioning - see https://privacytests.org/, but this is not all the items partitioned, and some of them are a bit ambiguous when claiming a green tick when in really they are blocking that in 3rd parties - e.g. brave blocks IDB in 3rd parties but Firefox doesn't and partitions them .. I think that's right for Brave - I haven't looked at arthur's tests in depth - so take some of those green ticks with a grain of salt), and so on. Also, for now, service workers will error out (because we enforce session-only "cookies" in order to sanitize site data on close, and this, in gecko at least, blocks service workers

Another big item is privacy.resistFingerprinting - this covers a lot and is probably going to throw up some strange behaviour. I would override this to false, since it's not useful to test FPing here. The timing mitigations alone will probably cause errors

Arkenfox doesn't really do much in terms of "security" on it's own.

So IDK what that means for you in terms of what you are actually testing, or if it will break tests. I have NFI what burpsuite entails :)

**Comment by Onfroygmx** [comment]
Burp tests the vulnerabilities of your website (client & server wise).
Arkenfox secures your browsers/browsing habits.

If you want to do pen tests use a profile without arkenfox, else you would be debugging your website and arkenfox interactions.

Onf.

**Comment by behradJ** [comment]
Thanks for your answers, I guess I should using it with default configs now.
