### ISSUE TITLE
Custom downloads dir reset to default after prefsCleaner but `browser.download.dir` value is correct? [solved: override browser.download.folderList]

### ISSUE THREAD

**Issue by xfzv** [arkenfox/user.js#1444]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

---

🟪 REQUIRED INFO
####  Browser version & OS
Firefox 100.0 / Arch Linux / arkenfox user.js 100

#### Steps to Reproduce (STR):
1. Create a new profile with `firefox -P`
2. Launch Firefox once using the new profile
3. Set a custom download directory in `Settings > General > Downloads`
4. Close Firefox
5. Re-open Firefox: the custom download directory is still used in `Settings > General`
6. In `about:config` - `browser.download.dir` value is correct:
![image](https://user-images.githubusercontent.com/78810647/167705839-83643bb6-3e71-495f-8bcf-009d88651403.png)
8. Close Firefox
9. Add the following in `user-overrides.js`:
    ```js
    user_pref("browser.download.useDownloadDir", true);
    ```
![image](https://user-images.githubusercontent.com/78810647/167705783-04dfc5c8-e8e5-4178-a0d6-693741e68b26.png)
10. Run `updater.sh` and `prefsCleaner.sh`
11. Open Firefox
12. In `Settings > General > Downloads`,  the download directory is reset to default (`~/Downloads`):
![image](https://user-images.githubusercontent.com/78810647/167706024-54ffa426-83fc-4850-83aa-d92cf8199574.png)
14. Yet, in `about:config`: `browser.download.dir` value is still using my custom directory:
![image](https://user-images.githubusercontent.com/78810647/167705839-83643bb6-3e71-495f-8bcf-009d88651403.png)

Note: Since I don't have any `~/Downloads` directory, when I click on "Browse...", the file picker starts in my `$HOME` directory.

If I manually change the download directory again and close Firefox, it's working as expected. But it's reset again after running `updater.sh` and `prefsCleaner.sh`.

#### Expected result:
My custom download directory is persistent after each `updater.sh` and `prefsCleaner.sh` run.

#### Actual result:
My custom download directory is reset to default after each `updater.sh` and `prefsCleaner.sh` run.

#### Anything else you deem worth mentioning:

This started to occur a few days ago with my main profile. My custom download directory was always used before, even after running `updater.sh` and `prefsCleaner.sh`.

I also tried different directories but it doesn't make any difference. FWIW, `browser.download.lastDir` value is also using my custom download directory, even after applying `updater.sh` and `prefsCleaner.sh`.

Did I miss any new override(s)?

Thanks.

**Comment by Thorin-Oakenpants** [comment]
Hmm, did some quick testing here in windows. toggling `browser.download.useDownloadDir` via about:config or the UI doesn't alter my dir pref here on windows. I'll try later with prefsCleaner just to be sure

> Did I miss any new override(s)?

no. It might be something to do with the whole new downloads improvements and sounds like a bug to me. You said it only just started happening this release (and you had the same setup in previous releases? right?). Do you have a bugzilla account?

> In Settings > General > Downloads, the download directory is reset to default `~/Downloads`:

I don't have linux here so I'm not sure of the intersection of all this. That sounds like a bug TBH. I see no reason why that pref should get reset

Does Arch not come with a downloads dir (sorry for my ignorance). What about other linux distros?

Does Arch's distro/package/flatpack/snappack come with a firefox cfg file? I've seen this before where shit got reset to weird defaults because they were set by the distro

**Comment by remyabel2** [comment]
I believe I identified the issue. I did a diff between prefs.js and the backup and found this preference: `browser.download.folderList` 
If this is set to `1`, it sets the directory preference to default, adding this to `0` in `users-override.js` fixes the issue.

**Comment by Thorin-Oakenpants** [comment]
> Hmm, did some quick testing here in windows. toggling `browser.download.useDownloadDir` via about:config or the UI doesn't alter my dir pref here on windows. I'll try later with prefsCleaner just to be sure

ugh, OP said
> Yet, in about:config: browser.download.dir value is still using my custom directory:

So that was a useless quick testing, my bad

**Comment by Thorin-Oakenpants** [comment]
```js
/* 5016: discourage downloading to desktop
 * 0=desktop, 1=downloads (default), 2=last used
 * [SETTING] To set your default "downloads": General>Downloads>Save files to ***/
   // user_pref("browser.download.folderList", 2);
```

is in the user.js so gets reset

**Comment by xfzv** [comment]
> I believe I identified the issue. I did a diff between prefs.js and the backup and found this preference: `browser.download.folderList` If this is set to `1`, it sets the directory preference to default, setting this to `0` in `users-override.js` fixes the issue.
> 
> Note: I don't fully understands how this preference works so take my comment with a grain of salt.
> 
> As far as the Linux perspective goes, I checked the PKGBUILD for Archlinux and they don't set any distro specific preferences, neither does Fedora.

> browser.download.folderList

Good catch!
https://github.com/arkenfox/user.js/blob/ea139e3ef8810149d90df8637984f2444282745e/user.js#L1036-L1039

Can confirm that setting `browser.download.folderList` to `2` fixes the issue.

**Comment by Thorin-Oakenpants** [comment]
don't close, I want to drink on this, I might be able to add something to the user.js

**Comment by remyabel2** [comment]
Good to hear it solved the issue..I misspoke and had to edit my comment like 5 times because I'm sleep deprived. Fedora does in fact set `browser.download.folderList` so I will be filing an issue for them. Thanks for opening this issue.

**Comment by Thorin-Oakenpants** [comment]
^ could have sworn arch also set cfg values - there was AF issue here if I can find it, something about default languages - maybe that changed

**Comment by remyabel2** [comment]
> ^ [#952 (comment)](https://github.com/arkenfox/user.js/issues/952#issuecomment-643322391)
> 
> > It turns out that (as shown in my previous comment) Arch Linux Firefox package contains a `vendor.js` file (located in `/usr/lib/firefox/browser/defaults/preferences/` with the following content ...

Indeed, I was misdirected because I was looking for a `.js` file similar to `firefox-redhat-default-prefs.js`, but they generate the `vendor.js` file inside the [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/7afcb70e094b6c77a46250bf8347e5c13ad7ac78/firefox/repos/extra-x86_64/PKGBUILD#L143). So the moral of the story is that on Archlinux `browser.download.folderList` should be the default value while on Fedora it is set to `1` in the default preferences. I had already bugged the RPM maintainer to remove some outdated preferences (that I tracked by following this repo) so I will open an issue about it later.

**Comment by Thorin-Oakenpants** [comment]
I wonder if we should add a troubleshooting step for Linux users, but IDK how to word it
- > linux users should also check blah blah

type it up for me and I can add it to https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-check

**Comment by Thorin-Oakenpants** [comment]
> type it up for me and I can add it to https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-check

no-one? OK

I was going to try and add something to the user.js, but I feel like this is edge case (for now). Unless I'm missing something, if you weren't overriding `browser.download.folderList` to start with then it was because you changed it manually via the UI. Not much I can do about that. The same argument can be made for any other inactive pref

**Comment by remyabel2** [comment]
It is edge case. I do not think the majority of people would be enabling `browser.download.useDownloadDir` (most of the threads I've seen were complaining about new download behavior). Otherwise the setting of `browser.download.folderList` does not pose a problem from what I can tell.

For troubleshooting, I would just say "check the source RPM/PKGBUILD/whatever of your distro to see if they set any vendor preferences".

**Comment by Thorin-Oakenpants** [comment]
> For troubleshooting, I would just say "check the source RPM/PKGBUILD/whatever of your distro to see if they set any vendor preferences".

thanks - not sure what "whatever" means :)
