### ISSUE TITLE
divested.dev times out

### ISSUE THREAD

**Issue by WeirDan76** [arkenfox/user.js#1455]
🟥  I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: FF 101
  - Steps to Reproduce (STR): open https://divested.dev
  - Expected result: it opens
  - Actual result: it does not open (connection has timed out)
  - Console errors and warnings: none
  - Anything else you deem worth mentioning: 

Maybe I'm missing something obvious, but that website opens on Safari (mac + phone), on TorBrowser, on FF 101 under a different profile, but not using FF with Arkenfox. Only relevant add-on is uBO which does not seem to block it and the time out still happens when the add-on is turned off.

Any ideas?

**Comment by Thorin-Oakenpants** [comment]
works for me

**Comment by WeirDan76** [comment]
Good point for the re-title. Thx.

**Comment by fxbrit** [comment]
it also works for me

**Comment by WeirDan76** [comment]
Ok, then let's close this, it has to come from somewhere else.

**Comment by Thorin-Oakenpants** [comment]
You didn't leave in, and tick, the checkbox that says you tried the checklist. All you left was the template. I was going to close as invalid and post a picture of a hamster at a tiny picnic table

You did say "Maybe I'm missing something obvious, but that website opens on Safari (mac + phone), on TorBrowser, on FF 101 under a different profile, but not using FF with Arkenfox. Only relevant add-on is uBO which does not seem to block it and the time out still happens when the add-on is turned off." - which means at least you tried :)

So at least we know it doesn't happen in standard FF, and thus we also know it's not a system/ISP network error/block e.g. DNS blocking. You didn't say you looked at the console, you didn't say you disabled all extensions (how do you know uBO is the only "relevant" one) and you didn't say you tried AF without any changes - maybe it was something you added as an override

The checklist is there for a reason.

That all said and done, this is not resolved, because it's clearly coming from your AF profile (and no others). And knowing what causes it is worthwhile. Reopen if you want to find the problem, or let us know when you find it

**Comment by Thorin-Oakenpants** [comment]
marking as invalid unless it is shown that a pref listed by AF causes it (I'm not saying your issue is invalid)

**Comment by WeirDan76** [comment]
Thanks for the feedback @Thorin-Oakenpants 

> You didn't say you looked at the console, you didn't say you disabled all extensions (how do you know uBO is the only "relevant" one) and you didn't say you tried AF without any changes - maybe it was something you added as an override

In the "required info", I did indicate that the console has no warnings or errors. There is the GET request and then nothing else, and it times out. The only warning being, after the timeout, "This error page has no error code in its security info." (and, on the right-hand side, it reads: "[aboutNetError.js:523:13](chrome://browser/content/certerror/aboutNetError.js)". Not sure this is very informative.

As for extensions, the reasons I say uBO is the only relevant one is just that it's the only one that deals with any kind of connections. My other ones are SkipRedirect (but there is no redirect here) and an add-on to expire history by days. At any rate, when I open the URL under the Arkenfox profile but in a private window with no add-ons, it still doesn't work. I also tried under a blank/empty profile and it opens properly. 

As for overrides, I do have a few:
1. to search from the address bar
2. to restore sessions
3. to ask for primary password at session open
4. to not ask to save passwords
5. to have compact mode
So nothing that should mess with a website, I would venture to guess.

**Comment by fxbrit** [comment]
IMO you should create a new profile, apply the user.js without any overrides, install uBO and see if the site breaks. that will tell you if it's one of your extensions or the overrides.

**Comment by WeirDan76** [comment]
Boy I don't get it. Created a new profile, added the user.js, added uBO, added all my rules/list, added other add-ons, eventually added user-overrides, etc., and the website opens in that profile, but not in my regular one. At this point, it's not Arkenfox, but boy what can it be?

**Comment by fxbrit** [comment]
maybe you changed some settings that you do not remember and you didn't change them through overrides? it's impossible to tell with so few details. you could try clearing all cookies and site data manually from the profile where it's broken to see if it actually fixes anything, or just use the new profile and don't waste your time :-)

**Comment by Thorin-Oakenpants** [comment]
> maybe you changed some settings that you do not remember 

compare the working profile prefs.js to the non-working profile's one. Do not modify them

**Comment by Thorin-Oakenpants** [comment]
^ https://www.diffchecker.com/ is nice, I use it all the time

**Comment by Thorin-Oakenpants** [comment]
also, true, my bad: you did modify the template: "Console errors and warnings: none" .. i knew that but when I posted I didn't see it again .. i am overworked, send ~~nudes~~ beersies

**Comment by WeirDan76** [comment]
Got it! The mullvad SOCKS5 proxy is blocking it. 

> ^ https://www.diffchecker.com/ is nice, I use it all the time

Good stuff, indeed!

> maybe you changed some settings that you do not remember 

Yup. Forgot about that...

Thanks a lot, guys!
