### ISSUE TITLE
query stripping

### ISSUE THREAD

**Issue by etotopuc** [arkenfox/user.js#1457]
From https://github.com/arkenfox/user.js/issues/1206#issue-937816628:
> ### ignore
> pref("privacy.query_stripping.enabled", false);
> pref("privacy.query_stripping.strip_list", "");

Are there any thoughts on using these settings as Librewolf does? Or is it considered redundant with corresponding lists in uBlock?

**Comment by rusty-snake** [comment]
1. uB can this (as you said).
2. uB list are easier to maintain than a string.
3. uB has a advanced syntax (e.g. per domain/url/..., regex support, match by param value, ...)
4. Will be great when development has hit the point when it's used by ETPstrict.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/pull/1443/commits/38c403d23b24337c256bbe171eb405cbf152c88a

do not ask about ETP custom (I get that this is not in ETP quite yet)

**Comment by Thorin-Oakenpants** [comment]
just FYI
- https://blog.nightly.mozilla.org/2022/06/02/these-weeks-in-firefox-issue-117/
   - > Query Parameter Stripping is starting to ride the Firefox 102 release train in ETP strict and Private Browsing Mode, this has been active in Nightly since Firefox 96. You can read more about it in our [intent-to-prototype](https://groups.google.com/a/mozilla.org/g/dev-platform/c/1vOSas0ptVQ/m/qpWv0SNDAAAJ).

MOAR FYI
[intent-to-prototype](https://groups.google.com/a/mozilla.org/g/dev-platform/c/1vOSas0ptVQ/m/qpWv0SNDAAAJ).
   - > Tim did say same-site navigation wouldn't be affected

PANTS is already onto it you guys, relax, I got this
- https://github.com/arkenfox/user.js/pull/1443/commits/38c403d23b24337c256bbe171eb405cbf152c88a

**Comment by Thorin-Oakenpants** [comment]
The pref is pretty lightweight ATM, we could add it juiced up as fallback - @fxbrit whadda think - what was yours? I think it was everything bar `mkt_tok`, right? But I'm also happy to not do anything with it - one less pref. But then having it documented is also kinda OK.

**Comment by fxbrit** [comment]
> what was yours?

I've used [Brave's list](https://github.com/brave/brave-core/blob/master/browser/net/brave_site_hacks_network_delegate_helper.cc#L31-L64) for a while now and I haven't seen any kind of breakage. I must say that when I followed the example URLs provided in the issues Legitimate URL Shortener was doing the job just fine, so there's surely redundancy if you use that list.

**Comment by Thorin-Oakenpants** [comment]
I know it's redundant for those who READ THE WIKI (and add those lists)

What I'm asking is should we add it, beefed up as a default fallback for non-READERS-of-the-almighty-WIKI, and it also means it's documented, and users can even add their own shit to it. It won't take affect until FF102 (because I'm not going to touch 7016)

So yay or nay? It would simply go under 2700s (ETP), not that it's restricted to ETP

**Comment by rusty-snake** [comment]
I used the global rules from AdGuard URL Tracking filter: https://codeberg.org/rusty-snake/firefox-config/src/commit/d6e4e47f09335df2f1b6212a3a7c2cdbae156371/assets/user-overrides.js#L131

Note that there are a few sites witch break even with parameters like `utm_source` removed.

**Comment by Thorin-Oakenpants** [comment]
does it actually requireETP?
- e.g. in 102 the default is true and stays that way even if you switch to ETP standard

**Comment by Thorin-Oakenpants** [comment]
> I think that's just a Nightly thing

yeah, you're right. In Beta 102 it changes with standard strict ... and if for example you are in standard, and flip it on, you are changed to custom

**Comment by Thorin-Oakenpants** [comment]
> I used the global rules from AdGuard URL Tracking filter

yup. not going to add that, but that's why adding the list pref is handy, users can tweak it

**Comment by Thorin-Oakenpants** [comment]
OK, so this pref is dead: https://bugzilla.mozilla.org/show_bug.cgi?id=1764291 - @fxbrit, you can remove it from LW if you want parity with the ALMIGHTY AF

**Comment by fxbrit** [comment]
thanks pants :-)

**Comment by Thorin-Oakenpants** [comment]
heh https://bugzilla.mozilla.org/show_bug.cgi?id=1775069

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1697982#c11 ... so apparently you can "add" to the list, but IDFC. IDK if "add" is a typo, IDK if this applies in PB mode - not adding it. Hopefully they just up the default to match Brave
