### ISSUE TITLE
[Question] What is the reason for keeping places.history.enabled true?

### ISSUE THREAD

**Issue by opusforlife2** [arkenfox/user.js#1471]
Is this a usability-based decision? Or does it have any privacy/security implications, such as related to sanitising on shutdown?

In other words, if a user flips this pref to false, does that impact their usage (other than convenience) at all?

Also, does clearing history on shutdown have privacy benefits other than preventing 'evil maid' kinds of problems?

**Comment by Thorin-Oakenpants** [comment]
Because it's optional opsec. Most people are not going to care that during a session on their PC, that history is written to disk. We already sanitize history on close as one measure of reducing disk leaks, but to neuter the back/forward buttons and history (and downloads info) itself is just being fucking mean - this is not Tor Browser and we don't need to go to extreme lengths (TB uses Private Browsing mode, so it behaves differently anyway - e.g. without testing off the top of my head, I think it has history but in memory)

All the stuff in `/*** [SECTION 5000]: OPTIONAL OPSEC` is just overkill for our target audience
