### ISSUE TITLE
Some comfort over safety? Possible solution: Settings.

### ISSUE THREAD

**Issue by NoNameISNoMan** [arkenfox/user.js#1483]
It would be nice to have some settings.

I understand that it is safer if the browser fully resets when closed, but I had 50+ tabs, was logged in into 20 different websites with 16-digit fully random passwords and I like it opening Firefox home screen instead of a blank page, and I don't want absolutely everything to wipe and reset every time Windows decides it's time to reset in the middle of the night. I am now forced to have a game open 24/7 so that my computer doesn't shut down and wipe my browser.

Is there any way to turn that off? Having an entirely different version with some safety exchanged for comfort would be nice, but I don't expect that from a free product, I am just hoping I can do something myself.

**Comment by Thorin-Oakenpants** [comment]
> I am just hoping I can do something myself.

READ THE WIKI and ADD OVERRIDES

**Comment by NoNameISNoMan** [comment]
I will try.

**Comment by NoNameISNoMan** [comment]
Problem: user-overrides.js doesn't exist.

**Comment by fxbrit** [comment]
just read the wiki...

https://github.com/arkenfox/user.js/wiki

**Comment by NoNameISNoMan** [comment]
I am and, GOD this is confusing. I have ZERO knowledge about how programs work, and it's Very difficult to follow. It assumes you  have a certain (although low) level of knowledge. One suggestion: Add the fact that something like Notepad++ or something similar is required. I tried using a normal Notepad at the beginning and... you Don't want to do that. Good thing I required it in the past.

**Comment by NoNameISNoMan** [comment]
Tried:
user_pref("privacy.sanitize.sanitizeOnShutdown", false);
Doesn't work.

**Comment by fxbrit** [comment]
are you sure the file is a .js and not a .js.txt or sum? is it named and located properly? posting some screenshots might help, otherwise it's hard for me to tell what's not working. also, how did you check if it's being applied or not?

if you're having trouble watch the techlore video at https://github.com/arkenfox/user.js/wiki/1.1-to-arkenfox-or-not, it should be visually easier than the wiki. if even then you feel like this is too challenging, I think you are going to hate a hardened browser anyway, so maybe consider something a bit more relaxed like https://www.privacyguides.org/browsers/#recommended-configuration (you don't have to flip them all, see what fits you)

**Comment by fxbrit** [comment]
[from the wiki](https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-common):

> `0102`: We disable session restore
> - If you rely on session restore, see our [override recipe](https://github.com/arkenfox/user.js/issues/1080)

also [from the wiki](https://github.com/arkenfox/user.js/wiki/3.1-Overrides):

> You do this by keeping them in a separate user-overrides.js file in your profile folder, so updating doesn't wipe them but instead appends them (when you run the updater).

the screenshot shows you are editing directly the user.js.
