### ISSUE TITLE
(Suggestion) Set OCSP soft-fail timeout to same value as the hard-fail pref

### ISSUE THREAD

**Issue by opusforlife2** [arkenfox/user.js#1486]
Ever since I switched to AF a few months ago, I've had frequent instances of OCSP checks failing (`SEC_ERROR_OCSP_SERVER_ERROR`), which then requires you to wait 5 minutes for the cache to clear, to be able to try to open the website again. Firefox itself does not have a way to clear the OCSP cache in session. They suggest reopening the browser as a solution.

My understanding of the problem is this:

- `1212` sets OSCP to hard-fail instead of soft-fail.
- Firefox waits for the soft-fail timeout, but then hard-fails because of the above pref.
- The actual hard-fail timeout value is never used.

Ideally, Firefox would automatically switch to using the hard-fail value when the `1212` pref is enabled, but I don't think that is happening. I'm following this line of reasoning because I never see the browser wait 10 seconds before showing this error. 2 seconds is more in line with my experience.

So I suggest adding `security.OCSP.timeoutMilliseconds.soft` with a value of 10000 to the user.js.

**Comment by opusforlife2** [comment]
<sub>In some sort of cosmic revenge, nearly all websites I'm opening right now are giving me this error after 2 seconds. My life is 5 minutes out of phase with the world.</sub>

**Comment by KOLANICH** [comment]
>then requires you to wait 5 minutes for the cache to clear, to be able to try to open the website again

Is there any deep reason for them to cache unsuccesful attempts instead of retrying on each new request until success?

**Comment by Thorin-Oakenpants** [comment]
> I've had frequent instances of OCSP checks failing

then override the pref and get on with your life

**Comment by opusforlife2** [comment]
I did, of course.

But isn't it logical to change this universally, since Mozilla deems 10 seconds as the appropriate value for hard-fail?

**Comment by Thorin-Oakenpants** [comment]
Not logical at all. Your info is anecodotal, whereas mozilla would have set that value for a reason. But the thing is, if you are getting so many OSCP hard fails, then the solution is to soft-fail, not mess with timers.

Look, I get that from what you have said, that a soft fail is 2s but a hard fail is also apparently 2s (not 10s) - so that's a bug? So, assuming there is an actual bug, we should raise soft to 10s .. but then people who override soft fail will now have long waits, so it means more overrides. Which is why there are two timer prefs, one for each: soft/hard. The solution here is to fix any upstream bug.

I am just not willing to go down this path of messing with timers.

**Comment by opusforlife2** [comment]
What I'm saying, broadly, is that OSCP.require makes Firefox _treat_ soft fails as hard fails, and yet Firefox seems to _use_ the soft-fail value when deciding to time out the request, like it normally would. Flipping the OCSP.require pref should make Firefox ignore the soft-fail pref completely, and always use the hard-fail pref when calculating timeouts.

^ This is assuming that I've correctly understood what's going on.

But you're right that this is an upstream issue as well, so I've opened [1776601](https://bugzilla.mozilla.org/show_bug.cgi?id=1776601).
