### ISSUE TITLE
Make sure PowerShell is allowed internet access.

### ISSUE THREAD

**Issue by starraiderx** [arkenfox/user.js#1506]
Please specify: 
  - the name of the file (i.e. updater.bat, updater.sh): updater.bat (v.4.15)
  - steps to reproduce the issue: Run updater.bat
  - actual result:  Update failed. Make sure PowerShell is allowed internet access.
  - expected result
  
  
Win_Version: 10.0.22622 Build 22622
Hard_Configurator: Recommended settings (tried without them as well, meaning SRP disabled, restrictions disabled, default Defender settings, and no extra firewall entries.) )

"Test-Connection -TargetName www.google.com -Traceroute" works, so I would assume PowerShell has internet access.

**Comment by starraiderx** [comment]
![image](https://user-images.githubusercontent.com/33199500/179510036-3b0a5c0d-22eb-4e59-8e1c-bc2713f88bf6.png)
It is not the call on line 66 but line 196. The Error message differs a bit

**Comment by Thorin-Oakenpants** [comment]
OK, sorry. I misunderstood. I thought you got an error because you were disconnected from the internet (or PS couldn't connect) or whatever, and got an error message, and I was thinking, well what did you expect, you got the error message.

I don't have anything to do with the updaters - this will have to be looked (both bat and sh) by someone else

**Comment by earthlng** [comment]
Hi @starraiderx 

can you please remove `>nul 2>&1` on line 225, then run the script again and report back with the output.

thanks

**Comment by starraiderx** [comment]
![image](https://user-images.githubusercontent.com/33199500/180604475-0619d20e-d0ab-4978-9905-5d8c975fc638.png)

**Comment by earthlng** [comment]
Your Powershell is in a restricted mode, see [Language Modes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes).

If you have Microsoft AppLocker configured, see [this](https://old.reddit.com/r/PowerShell/comments/nv3e58/getting_newobject_cannot_create_type_only_core/).

There's not much I can do about that, short of not using Powershell

**Comment by starraiderx** [comment]
I noticed that too but didn't have the time to reply yet. Powershell typically uses full language mode when running as administrator, so when doing that, my updater.bat works. Maybe there is a possibility to include language mode checks and then, request UAC if limited, once are found,?

**Comment by atomGit** [comment]
sort of off topic ... i understand if one *must* use windoze because of their job (i'd suggest getting a new job though) but arkenfox is centered around *privacy*

now can anyone make a case for using arkenfox along with a *proprietary* piece of shit OS which is absolutely anti-privacy by design?

sorry, but it just amazes me that anyone that gives a shit about privacy would be using fucking winBlows

**Comment by starraiderx** [comment]
There are multiple reasons for people to use windows not only job related reasons. Anyone that enjoys playing League or valorant can't do so on Linux, same goes for still a lot of multiplayer games. Also there is also the question of usability and if the privacy alternatives are worth the effort in some cases. 

Same goes for phones. Not everyone has or can afford a relatively new pixel to flash grapheneos. 

But this is not really the right place to discuss such a topic.

**Comment by Thorin-Oakenpants** [comment]
sorry starraiderx that I didn't get to that sooner, and I agree

---

@atomGit before you criticize someone, walk a mile in their shoes .. then criticize them, because 1. you'll be a mile way and 2. you'll have their shoes.

In all seriousness though, this is not the place to discuss why an individual has a particular OS, or their circumstances: for many it may be the _only_ computer they can get and flippant remarks like "get a new job" are not helpful.

**Comment by Thorin-Oakenpants** [comment]
> when running as administrator, so when doing that, my updater.bat works

you can also right click > prooperties > compat >  always run in admin mode (or something like that)

I will add this to the wiki. There is nothing we can do in the code that changes anything - you get the error message. But at least the wiki could me more helpful, now that we know - thanks for reporting

**Comment by starraiderx** [comment]
Ofc there is. You could check for the Langauge mode and the request UAC privileges. I am currently on holidays till end of August. But I can make a pull request then.

**Comment by Thorin-Oakenpants** [comment]
what would checking those achieve? Lets say you detect that (wrong language mode or UAC) .. then what? You already have a error message
