### ISSUE TITLE
Allowing a site access to my "HTML5 canvas image data"

### ISSUE THREAD

**Issue by zdat** [arkenfox/user.js#1513]
Sometimes I need to allow a site this permission in order to upload an image to it.

I've been flicking on CanvasBlocker when I allow this but I think RFP may protect me here given that the [Wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions) says CanvasBlocker is only good for non-RPF users?

Is it needed in this scenario or does RFP protect me? Thanks.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-rfp

> <sup>1</sup> Assuming it is even fingerprinting and widespread, this does not compromise your fingerprint - it is a single metric and only on those sites you exempt.

If you allow a canvas exception, then it is no longer randomized by RFP (and extensions like CB can then take over). The question is
- is the site actually FPing me?
- what are the chances a script runs due to uBO and ETP?
- what are the chances other sites can run the SAME canvas test and hook up with data brokers to LINK me on that ONE METRIC?
- does first-party matter?
   - if I am logged in they already have an id (real id or not), so allowing a _potential_ canvas FP really only means the data brokers get a canvas FP to _maybe help_ link traffic (if you allow an exception elsewhere and it's the SAME exact test)

does this answer the question? I wrote a wiki, I would hate to remove it because no one reads it
