### ISSUE TITLE
ocsp.require = true with Let's Encrypt Certificates

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [arkenfox/user.js#1528]
A few days ago every site (e.g. https://forum.rclone.org/) using Let's Encrypt Certificates started to return a SEC_ERROR_OCSP_SERVER_ERROR. I guess that this problem should be addressed in some other place but I'm curious whether I'm the only one who gets this error. Obviously, if I set ocsp.require to false, everything works again. So here is the question: if I do turn off ocsp, does firefox do any other revocation check or not? I've googled a bit and found out that there were plans to use some kind of CRL list. Is it implemented or I am basically not able to check the revocation status? 

  - Browser version & OS: 103.0.2 (64 bit)

**Comment by fxbrit** [comment]
CRLite is enabled by default in the user.js, see `1224`. more details on how it works and how it interacts with OCSP can be found at https://github.com/mozilla/crlite/wiki#faq.

also keep in mind that even if you set `ocsp.require` to false, checks will still be performed: the difference is that if a certain OCSP server is down or it cannot be reached, the check will be counted as passed instead of failed (aka soft fail, by design).

**Comment by Thorin-Oakenpants** [comment]
> but I'm curious whether I'm the only one who gets this error

works for me: AF default settings for crl + ocsp (I just used my main everyday FF, not a new profile with no crlite data - IDK if that makes a difference)
