### ISSUE TITLE
Best practice for updating Firefox when using Arkenfox?

### ISSUE THREAD

**Issue by noelsimbolon** [arkenfox/user.js#1531]
From the [wiki](https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain), a new version of Arkenfox should be available within a reasonable time after a new Firefox stable release. When such release happens, should I
1. immediately update Firefox to the latest version, wait and update Arkenfox when the appropriate version is released? Or,
2. delay updating Firefox until the appropriate Arkenfox version is released, update both Firefox and Arkenfox when a new Arkenfox version is released? Or,
3. do something else?

Thank you.

**Comment by rusty-snake** [comment]
1. Delaying security updates is the worst thing you can do. The ~5 prefs which get changed by a new arkenfox release do not matter there and are often minor fixes anyway.

**Comment by ExceptionGit** [comment]
Security updates should have a higher priority, but I still choose the second option.

Why? : No warranty.

- when updating ff, the old prefs may not work correctly or lead to unpredictable behavior, for example: I get this in the old ghacks-user.js version, now I don’t remember why exactly, here is a new example https://github.com/arkenfox/user.js/releases/tag/102.1 "Jul 18, 2022" and ff 102.1 released "6 jul, 12 days ago"
- in the new ff version, critical prefs for privacy can be added, for example: https://github.com/arkenfox/user.js/issues/1504
- when there is a big change in the prefs, it is safer to wait for a stable prefs version before ff updating, for example: https://github.com/arkenfox/user.js/issues/1281

As a result, it's easier for me to choose a policy of stable updates with waiting a few days after the release, this is a normal practice if there are no critical vulnerabilities (they can be fixed in other ways). In any case, you will not always have free time to update ff and addons. But this option can also have problems, for example: "if you use Linux - a dependency problem, especially for ArchLinux(you can't update the system, partial updates don't always work)" or "now youtube playback issue https://bugzilla.mozilla.org/show_bug.cgi?id=1787293".
