### ISSUE TITLE
Finally An Efficient Way To Spoof Fonts ?

### ISSUE THREAD

**Issue by Kraxys** [arkenfox/user.js#1535]
As said in the in the[ wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions), Fonts antifingerprint methods are generally disappointing. There is no API for that, and, as said in the wiki, there is at least a dozen of methods for fingerprint them.

So, in that case, why not act directly at the OS level?

It's precisely what is donne by the windows app [FluxFonts](https://github.com/da2x/fluxfonts). This app is on Github since 2017, I tested it several times 2 years ago (v1.2)  and on my system it never worked. But I recently realized that this app has got several update these last months, I tested several times the v2.2 on W10, using a non customized FF 104 Portable,  and it worked like a charm: The fonts fingerprints changed every 2 to 40mn, and the Creepjs tests nerver complained.

**Comment by Thorin-Oakenpants** [comment]
no. just no. waste of time and it does not cover font fingerprinting, only enumeration of what fonts are available

I will explain more another day

**Comment by KOLANICH** [comment]
>The fonts fingerprints changed every 2 to 40mn

The fingerprints are usually hashes, change 1 bit and whole fingerprint will change. A more sensible approach is to store the whole info as vectors of individual glyphs measurements, one measurement struct for each char, and compute the differences.

The software in question can be used as a tutorial on working with otf format. Unfortunately it is not cross-platform and also GPLed, so reuse of its code is not feasible.

Also it seems that app manipulates the FS instead of hooking the needed methods for needed processes. It has drawbacks making it unsuitable to be used anywhere but in a sandbox (like SandboxIE(Plus), that has been made Open Source), since Word and other apps use the same fonts and we don't want to interfere with their operation. It is not a production-ready tool.

Here is a related idea: https://bugzilla.mozilla.org/show_bug.cgi?id=1450564

@Thorin-Oakenpants, could you review it too?

**Comment by Thorin-Oakenpants** [comment]
LMFAO at [1469489](https://bugzilla.mozilla.org/show_bug.cgi?id=1469489) Webpages can show text - Security vulnerability

> Steps to reproduce:
> Create a website with a code like this `<html><span style="font-family:'Arial'">Hello</span></html>`
> 
> Actual results:
> The text Hello is displayed.
> 
> Expected results:
> The text Hello should not be displayed.

let me repeat that

> Expected results:
> The text Hello should not be displayed.

**Comment by Thorin-Oakenpants** [comment]
no explanation coming, sorry. - I don't have time to get into it

@KOLANICH re your bugzilla

I do not see the point. The way to unify fonts is for each platform to have the exact same fonts (and font versions). Recently Tor Browser moved a long way towards this (after years of neglect) by dramatically increasing the number of noto sans and noto serif fonts bundled. Linux is a bit different, but for mac and windows, the other fonts are (or should be) system stable. And of course fonts are restricted to an allowlist.

When TB moves to a single language installer (which saves massively on build sizes), then down the road I could actually see them bundling all fonts for linux.

some links
- https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/merge_requests/474
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30589 - for example
   - there was a lot of soul searching and testing and issues were labelled `Fonts` since it was such a big ~~mess~~ job/area
   - if you're interested (also the open ones) [quick link](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/?sort=updated_desc&state=closed&label_name[]=Fonts&first_page_size=20) - covers a heap of stuff like monospace was misconfigured on mac, bundled fonts were not included on mac, bundled fonts weren't included on linux, windows whitelist was based on win7 and no appropriate for win8/10/11, system fonts (open)

So this is the first step. Unify fonts including system-ui and looks and feel (e.g widgets). This means everyone has the same tofu, same script support, etc. And default fonts and sizes are dependent on the language = equivalency.

We could also enforce clear type on windows, for example - but I don't see the point right now.

After that, it comes down to external factors. And is not just about fonts. It comes down to subpixels, dpi, devicepixelratio, system scaling, layout.css.devPixelsPerPx, zoom, default zoom level, zooming text only, etc

And I think the only way to get around all of that is to add jitter/noise to methods such as textmetrics, clientrects, bbox, svg-stuff etc. Personally, I see fonts and subpixels (subpixels on anything, such as elements) as the biggest FP left: linux especially with fonts since there is no solid unifying base, and more and more devices (android of course, but also laptops etc) with devicePixelRatio's > 1. Mac for example only ships with 2 or 2.5 I think (1 if external monitor?), but then apple was always a tight bastard. The rest, not so much

So the font problem is not fonts (we could fix and unify that), it is measurements which affect more than just fonts

**Comment by KOLANICH** [comment]
>The way to unify fonts is for each platform to have the exact same fonts (and font versions).

The key point is that font rendering is affected by the software stack used to render them. We compensate not only for fonts themselves (which definitely can be shipped the same, but it is undesireable, TBH, because this means them be frozen ethernally and so users will never get new glyphs, which of corse not an option), but for the differences in measurements caused by software stack and environment differences. If we model text dimensions as `size_font(font, char) + delta_size_env(environment, char, font) = size_text(font, char, environment)`, where we can only automatically affect `size_font()`, then it is proposed to change `size_font` so that `size_text(font, char, environment) = const`. So it is proposed to transform the fonts into unique ones carrying the measurable info about the environment, but with minus sign, to make the overall rendereing less unique unique.

>And I think the only way to get around all of that is to add jitter/noise to methods such as textmetrics, clientrects, bbox, svg-stuff etc

Noise can be reduced by averaging. Tor Project has tried in 2010s, that protection was easily bypassed. CanvasBlocker does smarter, but still does not change the dimensions enough, if I remember right.

**Comment by KOLANICH** [comment]
Alternatively one can add knobs to all the rendering stack, but the rendering stack browser devs have to use is maintained by separate people and is affected by their political decisions. It is easier not to depend on those people and implement the solution on own side.

**Comment by Thorin-Oakenpants** [comment]
> because this means them be frozen ethernally

Not so. Fonts can be updated. Ideally on some major release.

> the rest

So ignoring all of the causes of entropy - how are you going to get them. You need to measure them (ignore webgl/canvas). So the solution is not to try and control all the rendering and all the other factors that determine change (subpixels, dpi, dPR, blah blah blah) .. it is to control the APIs that allow measuring

> Noise can be reduced by averaging

Not always, but yes, we know this. But it makes it very costly and once implemented, per method, it can be hardened, until it becomes impossible.

PS: your font solution does not solve any of the other subpixel or other element issues

**Comment by KOLANICH** [comment]
>Not so. Fonts can be updated. Ideally on some major release.

True.

>But it makes it very costly

It is costly for the user, not for the website owner. Website owner can allow itself to make the life of undesireable users (the ones that are not as unique as business interests of site owner require) as hard as it is necessary for him. 

>You need to measure them (ignore webgl/canvas).

Yes, both we and the fingerprinter. We - to get the deltas we need to apply to the fonts to make them actually fit the standardized dimensions. But for the potential fingerprinters it is proposed to always return the fixed data from the standardized table. They can even use these values for own rendering purposes - the fine-tuned fonts should actually fit those dimensions, at the cost of minor glyph shape distorsion.

**Comment by KOLANICH** [comment]
>subpixels (subpixels on anything, such as elements)

Where can I read more about this?

**Comment by Thorin-Oakenpants** [comment]
> Where can I read more about this?

what makes you think only text can be measured? Ignoring actual text measuring items such as textmetrics, fonts/glyphs are usually measuring a div and a span (sure, the text content influences that) - and not everything has text in it. What about lineheights, or getting decimal precision in borders to extract devicePixelRatio

text is a subset of a bigger issue. Why solve text (excluding unifying fonts + font versions) when we should solve subpixels

**Comment by KOLANICH** [comment]
>What about lineheights, or getting decimal precision in borders to extract devicePixelRatio

Thanks for the info.

>text is a subset of a bigger issue.

Aggree.

>Why solve text

Because all the issues should be solved. I guess the only practical way to solve the issue with subpixels is to bring a whole own software-rasterizing GUI stack and standardize it and prescribe all the browser vendors to use it, and just draw into a buffer using it, and draw a window that is just a rectangle showing the buffer. But it would look alien and users won't like it. Also software rasterization would be terribly slow. One of the ways to solve the issue with showness is to insert an FPGA into each PC and standardize the bitcode implementing GPU within the FPGA, and prescribe browser vendors to use that firmware-defined GPU, maybe specialized to drawing GUI. In the case a fingerprinting vector is found where the GPU is liable, the GPU bitcode can be updated to solve it.
