### ISSUE TITLE
[user.js suggestion] Do Not Track and Global Privacy Control signals

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1542]
Wouldn't it be good to enable them by default, or aren't they enabled because of fingerprinting?

<details><spoiler>

```
privacy.globalprivacycontrol.enabled
privacy.globalprivacycontrol.functionality.enabled
privacy.globalprivacycontrol.was_ever_enabled
privacy.donottrackheader.enabled
```

</spoiler></details>

**Comment by rusty-snake** [comment]
> privacy.globalprivacycontrol.was_ever_enabled

is a telemetry pref

> privacy.donottrackheader.enabled

DNT is enabled and the pref is in the user.js (DON'T BOTHER):

https://github.com/arkenfox/user.js/blob/3f09afdee07c5aea33f6dc4194e1425d6400a0d7/user.js#L1169-L1171

**Comment by rusty-snake** [comment]
> The signal is only sent to the trackers that the ETP module blocks, not all websites.

How is it send if they are blocked. 🤔

**Comment by fxbrit** [comment]
FYI: unlike DNT, the Global Privacy Control is legally binding, but from my understanding that applies exclusively to California and Colorado. GPC wouldn't mean anything for the rest of the world, at least not now. also see -> https://bugzilla.mozilla.org/show_bug.cgi?id=1670058#c1

**Comment by KOLANICH** [comment]
The proper reaction on a legally binding header is either `403 Forbidden` or `402 Payment Required`.

**Comment by Thorin-Oakenpants** [comment]
> also see -> https://bugzilla.mozilla.org/show_bug.cgi?id=1670058#c1

actually, that would be more like https://bugzilla.mozilla.org/show_bug.cgi?id=1670058#c6

in reality, No. One. Cares. The industry cannot self regulate or be trusted - this is why we had FPI and now dFPI. Track away because we never cared - we isolated this shit a long time ago. We will just use FF's defaults and be done with it.

**Comment by devingoodman** [comment]
I am hoping to convince you to reopen [[Issue #1542](https://github.com/arkenfox/user.js/issues/1542)](https://github.com/arkenfox/user.js/issues/1542). The GPC concept has made a lot of progress and it I think it is worth re-evaluating. Consider the following:

1. The GPC header is honored by a lot of highly ranked sites. These include news orgs like the [[NYTimes](https://www.nytimes.com/)](https://www.nytimes.com), [[Washington Post](https://washingtonpost.com/)](https://washingtonpost.com/) and the [[Financial Times](https://ft.com/)](https://ft.com/). Top visited sites like [[People Magazine](https://people.com/)](https://people.com/) which has 4.1 billion weekly media impressions, [[Entertainment Weekly](https://ew.com/)](https://ew.com/), [[Better Homes & Gardens](https://www.bhg.com/)](https://www.bhg.com/) (59 million monthly page views), [[Martha Stewart](https://www.marthastewart.com/)](https://www.marthastewart.com/) (13 million monthly page views) [[Travel + Leisure](https://www.travelandleisure.com/)](https://www.travelandleisure.com/) (33 million monthly page views) Health and Medical sites that consistently rank on the 1st page of search engines like [[Health](https://www.health.com/)](https://www.health.com), [[VeryWell](https://www.verywellhealth.com/)](https://www.verywellhealth.com/) and [[Parents](https://www.parents.com/)](https://www.parents.com) as well as major lifestyle outlets like [[InStyle](https://www.instyle.com/)](https://www.instyle.com/), [[Brides](https://www.brides.com/)](https://www.brides.com) and [[Shape](https://www.shape.com/)](https://www.shape.com).
2. In California, The GPC signal will be intended to communicate a Do Not Sell request from a global privacy control, as per [[CCPA-REGULATIONS §999.315](https://www.oag.ca.gov/sites/all/files/agweb/pdfs/privacy/oal-sub-final-text-of-regs.pdf)](https://www.oag.ca.gov/sites/all/files/agweb/pdfs/privacy/oal-sub-final-text-of-regs.pdf) for that browser, or, if known, the consumer. 
3. Under the GDPR, the intent of the GPC signal is to convey a general request that data controllers limit the sale or sharing of the user’s personal data to other data controllers ([[GDPR Articles 7 & 21](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679)](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679)).

And some counter examples to @arkenfox's earlier points from [[this comment](https://github.com/arkenfox/user.js/issues/1542#issuecomment-1250688292)](https://github.com/arkenfox/user.js/issues/1542#issuecomment-1250688292), 

> in reality, No. One. Cares. 

The California DOJ cares and the GPC header under the CCPA *is* being enforced(https://twitter.com/AGRobBonta/status/1562481606715006978). From the August 24, 2022 [[CA AG's Press Release](https://oag.ca.gov/news/press-releases/attorney-general-bonta-announces-settlement-sephora-part-ongoing-enforcement)](https://oag.ca.gov/news/press-releases/attorney-general-bonta-announces-settlement-sephora-part-ongoing-enforcement):

>Today's settlement is part of ongoing efforts by the Attorney General to enforce California's comprehensive consumer privacy law that allows consumers to tell businesses to stop selling their personal information to third parties, including those signaled by the Global  Privacy Control (GPC). 
>
>“Technologies like the Global Privacy Control are a game changer for consumers looking to exercise their data privacy rights. But these rights are meaningless if businesses hide how they are using their customer's data and ignore requests to opt-out of its sale,” said Attorney General Bonta.

I don't know off-hand if there are any GDPR enforcement actions, but I am sure the EU wouldn't hesitate to enforce if they felt it was appropriate.

Currently, GPC isn't included in your `user.js` I believe it would require the addition of two additional prefs:

```js
user_pref("privacy.globalprivacycontrol.functionality.enabled", true);
user_pref("privacy.globalprivacycontrol.enabled", true);
```

But you would know about this bit better than than I.

Anyway, I'll get off my soapbox. Here's hoping you reconsider!

**Comment by Thorin-Oakenpants** [comment]
I didn't mean that _literally_ no one cares. Obviously some do re enforcement and usage. But in terms of effectiveness it is statistically moot, and it is practically obsolete with dFPI + sanitizing - hence NO ONE CARES.

It will change when Mozilla changes it. Go ask them to do it, it's all set up.

**Comment by devingoodman** [comment]
> It will change when Mozilla changes it. Go ask them to do it, it's all set up.

It's okay. I'll just add it to my `user-overrides.js` and call it a day. Thanks for your time.

**Comment by xe-3** [comment]
@Thorin-Oakenpants It has been a couple years since this was last discussed, I'm here to pester you about this once more. (sorry..)

More US states have enacted privacy laws mandating the GPC signal be respected, and setting up a framework for penalties or lawsuits if it is not respected.

Additionally Firefox has now enabled by default in Private Browsing mode (as of version 120) and Brave has enabled it by default for all users.

In my eyes, there is no cost to enabling this by default

1. It communicates a privacy preference that is legally binding and enforceable in jurisdictions like California, Colorado, and Connecticut. (and more coming in '24 and '25.
2. It communicates a general pro-privacy, anti-tracking stance, that may or may not matter, but certainly doesn't hurt.
3. It can minimize or eliminate cookie pop-up notifications, and handles this automatically. So its also a QOL thing, not just Privacy.
4. I see technical solutions like dFPI and legal solutions like privacy legislation as the GPC as complementary. One doesn't preclude the usefulness of the other. At best it is an improvement to privacy, at worst it doesn't hurt to enable it, and users like me stop pestering you :)

But my strongest argument is simply _why not_? If the only argument against it is "nobody cares" and it becomes clear that many people do actually care, and enabling it wouldn't harm anything, then why not enable it, if it improves things for ~50 million, and doesn't negatively impact the rest?

**Comment by Thorin-Oakenpants** [comment]
once again

> in terms of effectiveness it is statistically moot, and it is practically obsolete with dFPI + sanitizing

even if statistically it went up, it doesn't really DO anything for us because dFPI. Tor Browser doesn't care and neither should we. Tor Browser doesn't even care about blocking trackers, because FPI. Capsice?

changing it is just another pref to add, another thing to read in the user.js, another thing to be asked about ... the answer is no - AND it will be an outlier in fingerprints **_INCLUDING_** headers (passive fingerprinting .. so no, just ... NO

**Comment by xe-3** [comment]
> even if statistically it went up, it doesn't really DO anything for us because dFPI

I still feel like you may not be appreciating that dFPI does one thing, GPC another. As I understand it, dFPI is an effective tool at preventing cross site tracking, through state partitioning (correct?). I accept that that is a better solution for 3rd party trackers and tracking cookies and the like. But I don't believe dFPI has any impact on first party abuse of your personal information. 

If you live in the EU, you enjoy stronger privacy rights than most. I believe GDPR mandates no business can sell or share your personal info without your consent. Most of the rest of the world does not have that right. In the states, we must manually opt-out, and even then, that opt-out is only legally required in a number of states. GPC is the most efficient method to perform that opt-out _From 1st parties (as well as 3rd parties) selling or sharing your personal information_ please correct me if I am wrong and dFPI can do something in that context?

**Comment by Thorin-Oakenpants** [comment]
answered at https://github.com/arkenfox/user.js/issues/1818#issuecomment-2013131325

> as I understand it dFPI does one thing, GPC another.

maybe know you will understand that what GPC does is irrelevant

**Comment by bmt613** [comment]
I'm not sure how much I trust a "privacy" extension that is being endorsed by Bezos owned Washington Post. We have already witnessed them manufacturing a narrative about the truly inconceivable amount of harm trump and the K'd out, Nazi, freak musk are wreaking on our country. 

Given the current hostile takeover of our government by billionaire, nazi fascist/oligarch "tech" bros, what real assurance do we have that Amazon and/or other elite sycophants won't use this to continue farming data and raking in a truly obscene and disgusting amount of wealth?

**Comment by bmt613** [comment]
Has your head been up your ass for the last month because even if you're not American, everyone is aware of what is happening to the American government, the byproduct being real human people suffering. 

No im not a bot I'm someone new to this space trying to be more cognizant of my digital footprint and how my data is being used and dick heads like you deter people from doing so. 

Have a day
