### ISSUE TITLE
consider dropping `browser.newtab.preload` + cleanup AS

### ISSUE THREAD

**Issue by fxbrit** [arkenfox/user.js#1556]
added way back in https://github.com/arkenfox/user.js/issues/426#issuecomment-402732183, I think preloading `about:newtab` is ok and it possibly brings a performance improvement.

- [implementation entry point](https://searchfox.org/mozilla-central/source/browser/modules/NewTabPagePreloading.jsm);
- AF uses `about:blank` as NTP. even if it didn't, [this support page](https://support.mozilla.org/en-US/questions/972251) indicates that the web pages in the NTP are not preloaded with `about:newtab`, when set to Firefox Home;

**Comment by Thorin-Oakenpants** [comment]
going to hijack this issue to also cleanup AS

current PR has the following

```js
/* 0105: disable some Activity Stream items
 * Activity Stream is the default homepage/newtab based on metadata and browsing behavior
 * [SETTING] Home>Firefox Home Content>...  to show/hide what you want ***/
   // user_pref("browser.newtabpage.activity-stream.feeds.topsites", false); // Shortcuts
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false); // Sponsored shortcuts [FF83+]
user_pref("browser.newtabpage.activity-stream.feeds.discoverystreamfeed", false); // [FF66+]
/* 0105: disable Pocket Activity Stream items ***/
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false); // Recommended by Pocket
user_pref("browser.newtabpage.activity-stream.showSponsored", false); // Sponsored Stories
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
```

We could expand on to cover all the UI checkboxes (I need to be careful because adding anything inactive means shit gets reset for users and forces more overrides), and we can move it all to `PERSONAL > ** AS OPTIONS **` .. but make some active default - e.g. sponsored shortcuts, sponsored stories

items like Recommended by Pocket, Shorcuts, etc are not a privacy issue. Not sure what `discoverystreamfeed` does. And not sure what `highlights.includePocket` does - e.g. `topstories` = `false` is a master switch for `showSponsored`. I've never used AS, don't even know what it looks like

---

as for the support page, that's 9 years old, so I wouldn't rely on. The question is, if users use AS, what exactly does preloading do on start and on newtabpage

**Comment by Thorin-Oakenpants** [comment]
OK, so current PR is

```js
/* 0105: disable sponsored content on Firefox Home (Activity Stream)
 * [SETTING] Home>Firefox Home Content ***/
user_pref("browser.newtabpage.activity-stream.showSponsored", false); // Pocket > Sponsored Stories
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false); // [FF83+] Sponsored shortcuts
user_pref("browser.newtabpage.activity-stream.feeds.discoverystreamfeed", false); // [FF66+] WTF does this do?

/*** [SECTION 9000]: PERSONAL ***/
/* FIREFOX HOME CONTENT ***/
   // user_pref("browser.newtabpage.activity-stream.showSearch", false); // Web Search
   // user_pref("browser.newtabpage.activity-stream.feeds.topsites", false); // Shortcuts
   // user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false); // Recommended by Pocket
   // user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false); // Recent Activity
   // user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
   // user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
   // user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
   // user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);

```

So two things
1. what the F does `discoverystreamfeed` do exactly
2. if a user overrides home/newtabpage to use FirefoxHome - what does preload do?
