### ISSUE TITLE
Animation smoothness with RFP enabled

### ISSUE THREAD

**Issue by RafeeDaBoy** [arkenfox/user.js#1568]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 106.0.1 and WIndows 10
  - Steps to Reproduce (STR): enable `privacy.resistFingerprinting`
- Anything else you deem worth mentioning: When `privacy.resistFingerprinting` is enabled, the animations in Firefox (opening new tabs, scrolling, etc) becomes more jittery/less smooth than default. Does enabling RFP change some other setting that can be changed back or is it just default behaviour of enabling RFP and can't be changed? Thanks.

---

**Comment by rusty-snake** [comment]
RFP does not flips other prefs.

RFP is all or nothing.

**Comment by RafeeDaBoy** [comment]
> jittery/less smooth is likely caused by timing mitigations.

I opened a new profile and tried enabling and disabling RFP and it only happens when it's enabled. So just to confirm, the timing mitigations or whatever change that makes the animations less smooth is because of RFP and cannot be changed?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L853

https://bugzilla.mozilla.org/show_bug.cgi?id=1774247

**Comment by ToxicSmurf** [comment]
I'm confused, is this a universal issue or does it only affect certain monitors?

**Comment by Thorin-Oakenpants** [comment]
It shouldn't affect users with a refresh rate of 60Hz, because that is exactly what the protection is doing = 60 FPS. This is an input speed. Input latency and response times are a hardware characteristic. And since 1000ms / 60 is a recurring decimal, the code need to account for that so as to not drop frames. I for one do not have any issues, but all my monitors are 60Hz (might need to check the mac and laptop, but pretty sure they are)

So ideally, you would get 60FPS on any monitor. But this does not line up nicely with monitors that are not 60Hz. 59Hz might be OK, IDK. But e.g. 144Hz would be out of sync. If you follow the upstream tickets you will find users reporting dropped frames in videos to differing degrees. But generally speaking general web pages are just fine.

So if you have issues with this then there are options
- use a separate browser for e.g. your netflix, youtube, HBO etc. I know it;s not ideal
- for now: don't use RFP and instead use CanvasBlocker (or not) - see the wiki
- in future: don't use RFP and instead use FPP (it is not ready yet) which will have subtle canvas randomizing
- in future: use RFP but turn off the timing mitigations (this is not ready yet)

It all depends on your use case and threat model
