### ISSUE TITLE
Need recipes pls, noob - user-overrides.js

### ISSUE THREAD

**Issue by valtoree** [arkenfox/user.js#1578]
Hello there,
Have looked around here couldn't find recipes for:

1.Uncheck - 'ask to save logins... Etc'
Always have to uncheck that everytime I use the update script.

2. under permissions tab, check 'block new requests asking access to ...'
For location, camera, microphone, notifications & virtual reality.

That's it. 
Thank you for reading.

**Comment by GlassGruber** [comment]
> 1.Uncheck - 'ask to save logins... Etc'
> Always have to uncheck that everytime I use the update script.

The updater scripts will reset the `prefs.js` file that contains _all_ settings in firefox, both from `user.js` and those set with the browser GUI. That's why you always have to recheck the password checkbox.

When looking for something you should try searching inside the `user.js` file. Looking for `password` will bring you to the following lines in _[SECTION 5000]: OPTIONAL OPSEC_.

https://github.com/arkenfox/user.js/blob/8a65c5a7bad0ec764d968b0941ebdf01bdcd2408/user.js#L917-L920

> 2\. under permissions tab, check 'block new requests asking access to ...'
>         For location, camera, microphone, notifications & virtual reality.

Same as above, searching for `permissions` will get you to below
https://github.com/arkenfox/user.js/blob/8a65c5a7bad0ec764d968b0941ebdf01bdcd2408/user.js#L1070-L1081

Place the above lines with the `user_pref` uncommented with options as you like in an [override file](https://github.com/arkenfox/user.js/wiki/3.1-Overrides).

**Comment by valtoree** [comment]
Your a legend. Ty ty 👍🙏 I will digest your info.

**Comment by Thorin-Oakenpants** [comment]
recipes require more than one ingredient
