### ISSUE TITLE
User-Overrides not being committed in about:config

### ISSUE THREAD

**Issue by DanitiKain** [arkenfox/user.js#1607]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 108.0.1
  - Steps to Reproduce (STR): add network.trr.mode 3
  - Expected result: about:config shows network.trr.mode as 3
  - Actual result: still stuck at original 2. 
  - Console errors and warnings: none
  - Anything else you deem worth mentioning: not really

---
This is example that I can reproduce on each profile. There are other settings that I noticed now aren't being applied in from what I placed in my user-overrides file as well. Such as  network.cookie.cookieBehavior.

**Comment by Thorin-Oakenpants** [comment]
> Such as network.cookie.cookieBehavior

https://github.com/arkenfox/user.js/blob/7135907b2fe13fa55eb8ebf162603037f83e353c/user.js#L1135-L1136

**Comment by DanitiKain** [comment]
What about the the trr.mode?

**Comment by Thorin-Oakenpants** [comment]
Make sure you check the checkbox that says you read the wiki and took all the steps
  > _unchecked issues ~~may~~ will be closed as invalid_

---

My [previous comment](https://github.com/arkenfox/user.js/issues/1607#issuecomment-1366694773) shows you didn't even heed the warning about DON'T TOUCH in the user.js (which says leave cookieBehavior alone and even says `[WHY]`) - and see #1334 - there is no point in changing cookieBehavior when both standard and strict ETP have dFPI.

> What about the the trr.mode?

Secondly I just tested by adding `network.trr.mode` = `2` to the end of my user.js and restarting .. and it was applied. I'm not using DoH so that _may_ be a factor (e.g. it may be that other DoH settings are causing it to revert back)

Given these two results so far, I am closing as invalid. Should you bother to troubleshoot (READ THE WIKI - there's even a link provided for you in the issue template [1] ) and the problem persists, then feel free to reply. I'm not a mind reader, and am not going to bother making educated guesses and asking dozens of questions

[1] e.g. did you check your parrot, did you try it in a new profile, did you test **_without extensions_**  .. in your current profile are other overrides being applied, is the override in your user.js (user-overrides.js should be applied to user.js when the updater is run - read the wiki) - i.e how/where are you adding the override pref ... the list goes on

sorry if this sounds a bit short - but as basically the sole maintainer for the last 3 years, and moving on other things, I am time constrained  - so I don't tolerate people wasting my time and not reading the wiki (not saying you _didn't_ but it looks that way)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues?q=is%3Aissue+author%3ADanitiKain ... this is the 4th invalid
