### ISSUE TITLE
Mitigating conflicts between ETP Strict and uBlock, Redirector, etc. via fine-tuning `browser.safebrowsing.provider.mozilla.lists`

### ISSUE THREAD

**Issue by msoxzw** [arkenfox/user.js#1620]
Currently, Firefox downloads lists of data for blocking content according to `browser.safebrowsing.provider.mozilla.lists`:

> base-track-digest256,mozstd-trackwhite-digest256,google-trackwhite-digest256,content-track-digest256,mozplugin-block-digest256,mozplugin2-block-digest256,ads-track-digest256,social-track-digest256,analytics-track-digest256,base-fingerprinting-track-digest256,content-fingerprinting-track-digest256,base-cryptomining-track-digest256,content-cryptomining-track-digest256,fanboyannoyance-ads-digest256,fanboysocial-ads-digest256,easylist-ads-digest256,easyprivacy-ads-digest256,adguard-ads-digest256,social-tracking-protection-digest256,social-tracking-protection-facebook-digest256,social-tracking-protection-linkedin-digest256,social-tracking-protection-twitter-digest256,base-email-track-digest256,content-email-track-digest256

Some of these lists have repeated functionality, or even conflicts with uBlock, Redirector, etc. Hence, fine-tuning this preference could hopefully mitigate this issue.

**Comment by Thorin-Oakenpants** [comment]
Thanks, and I don't mean to sound snarky, but this out of scope: lemme explain

> Some of these lists have repeated functionality

don't care: unless I'm missing something, AFAIK there should be no issues as per some gorhill post at some stage (I can't find it), due to the way extensions work in gecko: at worst you enable something in uBO to make a site work but it still breaks due to ETP - all that means is you need to relax ETP on that site. At least I think that's how it works. The real problem comes when you have multiple extensions which we do not recommend, in fact we explicitly warn against many of them

if anyone can find gorhill's post that would be cool - probably in the uBO wiki

> or even conflicts with uBlock, Redirector, etc

examples?

> Hence, fine-tuning this preference could hopefully mitigate this issue

Only hopefully? So you don't know? 

There is no way I am going to dig into those lists, learn all about them, or even suggest changing them from default. If there are issues, take them up with Mozilla: they're not going to care about repeated lists/functionality as not everyone has uBO, but there may well be bugs. Also see #1334 - I am not interesting in messing with **any** ETP Strict settings, and that includes what ETP sets/uses e.g. those lists

You always have the option of disabling ETP strict per site via the shield in the urlbar or in settings or allowing some items (IDK exactly since I never have to fiddle with anything)

Closing as invalid unless proven otherwise
