### ISSUE TITLE
There is still a problem with notifications

### ISSUE THREAD

**Issue by mvk-foo** [arkenfox/user.js#1622]
https://bugzilla.mozilla.org/show_bug.cgi?id=1095073

1. Go to website: https://www.bennish.net/web-notifications.html
2. Сlick the **Show** button
3. Open the file in the profile:  `notificationstore.json`

**Comment by Thorin-Oakenpants** [comment]
You have to authorize notifications. The site knows what it sent you - they could log that forever. You know what you received, at most, this is a disk level threat model. Lock your device, encrypt your drives, don't grant any notifications permissions

I tested in nightly and there is no such json file, instead there is a `notificationstore` dir with an mdb and it is password protected

I tested in beta, and there is a json file - after closing the browser this was all that was left in it
```
{"https://www.bennish.net":{}}
```

my beta is set to sanitize everything on close, but I _suspect_ that has nothing to do with it and it is cleared anyway because the messages have been notified to the end user, and the session has close. Strange it keeps the url, but given Nightly's storage method, not going to waste any more time on it

**Comment by Thorin-Oakenpants** [comment]
in fact I went to 3 sites in beta, and once the messages had been delivered, without closing Firefox, the json file was modified

```
{"https://www.bennish.net":{},"https://cleverpush.com":{},"https://webpushdemo.azurewebsites.net":{}}
```

so that bugzilla looks like it's been resolved anyway

**Comment by Thorin-Oakenpants** [comment]
note: invalid = invalid **_for AF_**, not saying there aren't issues

There is a move upstream to protect more disk items - e.g. in PB mode encrypt storage with a session key so even a crash still protects any left over data (and to be tidy it would also cleanup files on each PB mode session start). This then allows IDB and SWers in PB mode. There are other areas that are slated to use encryption as well.

But I as I don't actually know enough about this, i.e notifications + storage + sanitizing + encryption, .... and because I don't want it to be misleading, I've removed the invalid label

---

I'm digging a little more, mostly for my own info: not to be confused with sanitizing

STR :)
- search: https://searchfox.org/mozilla-central/search?q=notificationstore&path=&case=false&regexp=false
    - there's a `\new\` and an `\old\` NotificationDB.jsm
- https://searchfox.org/mozilla-central/source/dom/notification/new/NotificationDB.jsm#144-146
    - [1515096](leads to https://bugzilla.mozilla.org/show_bug.cgi?id=1515096) 

I can't seem to find where nightly uses new (IDK if it's kvstore exactly, but it uses the mdb) and other channels use old (json). That would probably give me some sort of meta or rollout indication.

**Comment by fxbrit** [comment]
> I can't seem to find where nightly uses new

wym, in the code? [it's a build time thing](https://searchfox.org/mozilla-central/source/dom/notification/moz.build#41-48) but it looks like it's been in early beta [for 3 years now](https://bugzilla.mozilla.org/show_bug.cgi?id=1538541#c25) which doesn't sound promising.

**Comment by Thorin-Oakenpants** [comment]
the whole encrypted IDB + SWs in PB mode has been going on for 5+ years
