### ISSUE TITLE
Disabling webgl anti-aliasing

### ISSUE THREAD

**Issue by mik0l** [arkenfox/user.js#1645]
Set `webgl.default-antialias` to false

Also recommended by tor-browser:
https://bugzilla.mozilla.org/show_bug.cgi?id=1485249#c8

I was wondering if anyone could test it?

**Comment by Thorin-Oakenpants** [comment]
FYI
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30531
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/26198
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/22333
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/15825
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30537
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40117

not going to scan thru them, read them all before - but in a nutshell - this currently makes no sense on FF where we don't have webgl behind a click to play like Tor Browser - instead we disabled it in arkenfox - and due to how few sites use webgl, recommend opening those sites in a secondary browser. webgl on it's own has so many parameters and values based on the graphics card/ gpu, and rendering diffs (along with equivalency of e.g. fonts, clear type etc in the render), that it's super high entropy - hence we nix it. Long term the idea would be to randomize the rendering and limit the other information and stick it behind a click to play

it also makes no sense for FF as 1) there is no crowd and 2) all we can really do is fool naive scripts (which we do with canvas) and 3) this ignores the IP data

Anyway, for Tor Browser, low priority, the idea is ... https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30537#note_2868528

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42239
