### ISSUE TITLE
Consider the removal (or activation) of 0710 (network.trr.mode) from user.js

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1649]
Recently, updates to the file have prevented resetting of users' personal preferences, and I believe this fits in as one of them.

The [video](https://youtu.be/F7-bW2y6lcI?t=96) quoted on the user.js wiki made by the YouTuber Techlore recommends enabling DNS over HTTPS.

I'm not sure if this is a bad option to be enabled by default (since arkenfox's user.js doesn't explicitly set it), and also considering it isn't enabled by default in Firefox.

**Comment by Thorin-Oakenpants** [comment]
not going to make it active - DoH is a user decision and there is no generic right or wrong answer

not going to remove it, as it is informative to those who don't want to be enrolled (4 countries so far) - you still get a prompt, and without double checking it yet again, I believe it is opt-out

if you, as an end user, decide you want DoH then you need to add an override, so prefsCleaner does not reset anything or affect any personal settings (because the default is off)
