### ISSUE TITLE
Anti-FP for NON-RFP

### ISSUE THREAD

**Issue by git70** [arkenfox/user.js#1657]
I support the emphasis on using RFP in AF, but can someone help me if I can't (although I would love to) enable RFP due to UTC0 time zone issues.

I feel lost after the liquidation of sections 4600 and 8000 NON-RFP because it probably means no support for NON-RFP prefs?

What are the current Anti-FP prefs if I'm not using RFP?

**Comment by Thorin-Oakenpants** [comment]
> What are the current Anti-FP prefs if I'm not using RFP?

NONE. Read the wiki - https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-rfp - all you can do is fool naive scripts, and you cannot do that with prefs (except RFP), so if RFP is not your thing, then use CB

> Otherwise, if you think the threat fits your wheelhouse, use CanvasBlocker with canvas and audio randomizing (the rest is not really needed and will add perf costs). Note that extensions lack APIs to fully protect metrics, but naive scripts are likely not that sophisticated.

**Comment by Thorin-Oakenpants** [comment]
from #1080 

add to your `user-overrides.js` file - https://github.com/arkenfox/user.js/wiki/3.1-Overrides
- and you run the updater to update _AND_ append your overrides each time
```js
/* override recipe: RFP is not for me ***/
user_pref("privacy.resistFingerprinting", false); // 4501
user_pref("privacy.resistFingerprinting.letterboxing", false); // 4504 [pointless if not using RFP]
user_pref("webgl.disabled", false); // 4520 [mostly pointless if not using RFP]
```

**Comment by Thorin-Oakenpants** [comment]
the other items in 4500 also affect fingerprints, but some are default, and some aren't used without RFP and none of them cause breakage, so the simplest easiest way is just those above 3 prefs :)

**Comment by Thorin-Oakenpants** [comment]
As for CB's config, that's up to you. Audio is very low entropy. I believe all you really need at your threat model is canvas. Maybe webgl is also a good fit. These two can high entropy on their own. Be aware of perf issues, but you can add site exceptions in CB.

But you do you, choose whatever you want in CB

**Comment by Thorin-Oakenpants** [comment]
For the record, in future, you will be able to exempt each specific RFP protection as your default - e.g. by adding every protection except the one(s) you don't want

Obviously this means updating if new RFP's are added. But that's not difficult if you keep up to date with section 4500's info. I will likely have to add a new info block about the numbering / examples

I agree that the timezone protection is a real usage issue - it annoys me when I want to look up the time of a sports event or something (it depends on how the site formats the date: in your TZ or the place it's at). And perhaps the timing being at 60 FPS, but I don't experience any issues with that myself.

Items like prefers dark-theme = "cry baby ... call me a wambulance 🚑 " material - this is not about accessibility - prefers-dark theme is not universal (i.e it is up to the website to provide it) - if you have usability issues you should use the right accessibility changes (not sure how RFP impacts some of those). Dark theme is mostly shit anyway.

Anyway, there are a lot of changes coming to make RFP more user friendly - such as the header OS spoof in mac/linux will be dropped in FF, adding site exceptions for RFP (i.e the whole thing), being able to tweak your own RFP set (not recommended at this point, but lets see where it goes first - there are pros and cons to this, and that's a story for another day: I could do either if I can justify that it doesn't affect your FP protection) - but it's also going to get confusing because there is another FP protection coming from Mozilla - called FPP which is for PB mode, which is much more relaxed and will be taken slowly in small steps so as to have no breakage

AF (and TB for sure) are going to stick with RFP which will override anything FPP does, but we will/can benefit from what FPP brings. It's very hard to know the overall plan and what is going on, as this is all inhouse at Mozilla and very tight lipped. This is from from public bugzillas, and while I asked for some more info (confidentially), for the moment it's all inhouse and lips are sealed. If/when I do learn more, I too can't say anything not public, so there ya go!

FPP (which remember is PB mode and will be tied to ETP) milestone 1 looks like adding font vis level 2, subtlely randomizing canvas, and incorporating audio protections (which is for RFP as well - by hooking up the same math lib for all platforms). I would expect them to add some basics like UA simplification and window positions as well - quite a bit of RFP is non-breaking and extensively tested and would suit, but they will take it slow.

**Comment by Thorin-Oakenpants** [comment]
^ @jonaharagon - there ... FPP

**Comment by Thorin-Oakenpants** [comment]
> but they don't work fully properly

dates are hard man, I mean hard. Extensions basically need to fully implement their own Intl API and that's like massive work, plus they can't protect your in service workers

> I tried

All that stuff is temp. It is or was basically one person in his own time - Tom Ritter. RFP is not front facing and not part of Mozilla per se. That said, and I don't know all the ins and outs - it now seems like a few more devs are working on it, because maybe they overlap. And it hasn't been six years :) RFP was good enough for TB and that's what it was for. Tom and other upstream added and tweaked a few things over time, that was all they could do - as it wasn't Mozilla's problem and they are volunteering their free time. But I hear ya, canvas is more widespread, other issues could be improved. At least it's coming :) Relax and chill bro 🍺 

So for example, exempted domains will (most likely) become a site exception. testGranularity is already removed in FF114. And not everything is/was hooked up. Some of them were/are tricky. TZ was problematic and had to be reworked completely (something to do with using TZ env I think, so it would never have worked anyway). Starting in FF113 I think it switches to the new method `privacy.resistFingerprinting.testing.setTZtoUTC` (at true it uses the old method, at false the new method which can or will be controlled via the RFP exceptions). Math is/was tricky to pass shouldRFP to, etc. So I'm not surprised you couldn't get TZ to work (it couldn't), let alone some of the others.

> An additional problem is that when this pref finally goes to FF, when will it go to ESR

I don't think or know if the bits we want will make it to ESR. Some will, if they pertain to Tor Browser. So if TB don't want to add site exceptions (i.e turn off all RFP on a per site basis, per session), then I doubt they will backport it, and IDK if it will make it in time for ESR115 or backported to the few ones out before ESR102's EOL.

Yeah, that bug you linked is the setting up RFP sets. Like I said, the pref would be all RFP numbers minus the ones you don't want. Only time will tell if it makes it to ESR115

**Comment by rusty-snake** [comment]
> for example geolocation

You said "want to increase security". What's the security threat here?

> Example prefs:

Breakage: +50
Security: +2
Conclusion: is it worth?

**Comment by Thorin-Oakenpants** [comment]
even TB could only find five or six things to add between standard and safer in .. wait for it ... their SECURITY SLIDER

**Comment by Thorin-Oakenpants** [comment]
> TZ ... Math

https://spidermonkey.dev/blog/2023/04/14/newsletter-firefox-112-113.html
> - We improved mitigations for fingerprinting based on [time zones](https://bugzilla.mozilla.org/show_bug.cgi?id=1709867) and [math functions](https://bugzilla.mozilla.org/show_bug.cgi?id=1823880).

**Comment by Thorin-Oakenpants** [comment]
> Why the +50 corruption?

[Why not](https://news.ycombinator.com/item?id=35539595)? Complete your side quest to gain +10 stamina and the Light Glass Boots of Speedy Fuckery

**Comment by Thorin-Oakenpants** [comment]
> timezone problem will be solved in FF113

And math. No. We're a long way from that. The old code/method couldn't be used differently per site, it was global - there was no engineering in place to do it. The new code will now start to allow them to do this, but it's not all hooked up.
