### ISSUE TITLE
Disabling Favicons?

### ISSUE THREAD

**Issue by 0pLuS0** [arkenfox/user.js#1673]
Hello,

I'm using FF 113.0 in Linux.

I've actually been using the settings guide I found on your site;

https://arkenfox.github.io/gui/

I haven't been to every site I have bookmarked, but for some reason the few I have visited, at this moment, Proton's site Favicon keeps appearing. https://proton.me/

There's only two settings listed on your site to change;

browser.chrome.site_icons
browser.shell.shortcutFavicons

What favicons settings am I missing, to fix this?

THANKS

**Comment by 0pLuS0** [comment]
I aplogize, after posting this, I thought I had browser.shell.shortcutFavicons on false.

Now I'm not seeing the favicon for Proton, and if these two settings are all I need to enable fasle, please let me know?

THANKS

**Comment by Thorin-Oakenpants** [comment]
read the items' descriptions

`browser.shell.shortcutFavicons` is, according to documentation, only for `shortcuts` .. not `bookmarks` - i.e you drag and drop the padlock to a folder, the system will use the site's icon stored in profile/shortcutCache directory. It works that way for me in windows, IDK about linux.

`browser.chrome.site_icons` is the icons used in Firefox, i.e the `chrome`. As it says these are stored in favicons.sqlite. Using this is very OPSEC - e.g. you are not retaining history and care about someone seeing a favicon over your shoulder - which TBH is very far fetched, at this level, you should be under a sheet like Edward Snowdon.

At this point, I don't really care about favicons. I no longer know what `[NOTE] favicons.sqlite is sanitized on Firefox close` refers to now. Maybe you just needed to do a restart. And the whole thing is a mess, to the point where even the mozilla devs couldn't even work out what was happening with them (bookmark icons, favicons for websites as you browse, sanitizing etc) when looking at this - https://github.com/jonasstrehle/supercookie - they were surprised to find FF was already protected due to a bug or something

You should be able to set just the chrome pref (using an override), close FF and delete favicons,sqlite.

**Comment by 0pLuS0** [comment]
Deleting favicons.sqlite worked.

THANKS

**Comment by Thorin-Oakenpants** [comment]
it's a labyrinth and nobody knows anything :)  the `[NOTE] favicons.sqlite is sanitized on Firefox close` from memory was me checking what was in it after a session (and IDK if that was with our sanitizing prefs or by default - I think it's by default) - and I'm 99% sure this was about website icons, not bookmark icons. But bookmark icons may be in there (who knows). Because the last thing you want is having all your bookmark icons missing on startup.

Hence the suggestion to try deleting that sqlite file to remove anything persistent from before your pref tweak. Seems to have worked and I for one am glad to never bring this up again :)  ... :cocaine_bear:
