### ISSUE TITLE
Can't change user agent via general.user.override

### ISSUE THREAD

**Issue by Palome-a-guy** [arkenfox/user.js#1683]
general.user.override does nothing when an arkenfox.js is used, i just keep my real useragent

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/c34531b67e0b9d162331fa92dc0eae2548d13fc7/user.js#L1149-L1152

For starters, you cannot hide your browser engine or version or OS or platform architecture - i.e all the things that makes up the userAgent, so it is pointless to lie about them. RFP already reduces the entropy in them (e.g reporting all android the same as mobile 10, or windows as windows 10 etc. So there is ZERO to be gained by fucking around with this

secondly, they leak - i.,e they do not work in all instances, such as via service workers, maybe iframes etc

Thirdly, by design, RFP blocks these being used, because they are useless

Lastly, some useragent overrides are used for compat reasons - see about:compat - because websites can be poorly coded. If you have an issue with a website, then report it to bugzilla

**Comment by atomGit** [comment]
> So there is ZERO to be gained by fucking around with this

though not strictly related to the focus of arkenfox, that's not quite true - for instance there are mainstream "news" websites which, although they allow google to index the full articles, only show a portion of them to a non-google UA and in such cases simply changing the UA to the google crawler may reveal the whole content

**Comment by Thorin-Oakenpants** [comment]
> that's not quite true

It is true. I already said "some useragent overrides are used for compat reasons" ... compat being either incompetent website code or malicious fuckery - hence see examples in about:compat where they _literally_ have a section called `User Agent Overrides`.

using the pref overrides is global, so there is still ZERO to be gained by fucking around with them
