### ISSUE TITLE
Disable Pocket

### ISSUE THREAD

**Issue by Rathmox** [arkenfox/user.js#1684]
I found that Pocket is still enabled and I feel like it can be good to disable it

```
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.showHome", false);
user_pref("extensions.pocket.onSaveRecs", false);
```

**Comment by Rathmox** [comment]
Pocket is an extension in the firefox installed by default. So I wanted to know if you were ok to disable it in the user.js

**Comment by rusty-snake** [comment]
Any argument why it should be disabled?

>  So I wanted to know if you were ok to disable it in the user.js

I guess no because it was there in the past and got removed. But I'm not the person how decides this.

https://github.com/arkenfox/user.js/issues/853
https://github.com/arkenfox/user.js/pull/1558/commits/934bd24ac1f7901a141d577b7ed688d4329ce382

**Comment by Rathmox** [comment]
Ok, maybe it's not the goal of this project, Thanks for the answer

**Comment by Thorin-Oakenpants** [comment]
the pocket extension does nothing unless you sign up for it, in which case you wanted it. It is not up to AF to arbitrarily decide to block this service from users should they want it. There is no need to include it in the user.js, except for those who want it removed for cosmetic purposes, which is not what this repo is about.

Also, for the record, all you need is `extensions.pocket.enabled` = false to disable the extension, that's it. Blindly and wastefully just listing and flipping prefs because of false assumptions about the name is not how we (or anyone should) do things
