### ISSUE TITLE
[Question] Should I use this with Firefox Developer Edition?

### ISSUE THREAD

**Issue by abceleung** [arkenfox/user.js#1692]
From README:

`Also be aware that the arkenfox user.js is made specifically for desktop Firefox. Using it as-is in other Gecko-based browsers can be counterproductive, especially in the Tor Browser.`

I want to daily drive FF Developer Edition. Will there be any problem if I use arkenfox with it?

**Comment by Thorin-Oakenpants** [comment]
nope, go ahead. fuck all happens these days - in the last 12 releases we've flipped two prefs and one of those is a fallback only for linux - you'll be fine, just be aware that of course you're one release ahead, but seriously, nothing is going to happen that can hurt you

**Comment by Thorin-Oakenpants** [comment]
@abceleung because I tend to add things only when we need to rather than when the prefs come out, you may get annoyed by a few things in the future

```js
// for abceleung
// added in FF108+
user_pref("browser.urlbar.weather.featureGate", false);
// added in FF115
user_pref("browser.urlbar.addons.featureGate", false);
```

they are currently default false as of nightly 117, but they will get flipped at some stage. I'm not sure how they get the weather (direct or proxied) and it makes no sense if behind a VPN (there's a pref for that as well), but anyway, we don't want to leak our location - i'm not even sure how FF would provide it

addons .. bah humbug (not a privacy concern, just annoying)

here's a picture of what they look like
![ugh](https://github.com/arkenfox/user.js/assets/16656956/622d86dc-904d-4c56-8e2e-a63b1f15672a)

**Comment by fxbrit** [comment]
just wanted to add that weather suggestions come from Merino, and I think the location detection is IP-based given that there's the pref that automatically disables suggestions when the browsers detects you're using a VPN (see [here](https://searchfox.org/mozilla-central/source/browser/components/urlbar/private/Weather.sys.mjs#246-247))

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41576 - uses `regionalPrefsLocales`

**Comment by fxbrit** [comment]
you mean to determine how it should display information right (locale + unit of measurement) right? I was talking about IP-based geolocation to show you the weather for the right town/area

**Comment by Thorin-Oakenpants** [comment]
yeah, IDK anymore, it was 6 months ago

**Comment by Thorin-Oakenpants** [comment]
> and I think the location detection is IP-based

yeah, of course, and makes sense as the only way to do it - also explains why they needed the VPN pref... my bad (too much happening to focus on this)
