### ISSUE TITLE
Disable a pref

### ISSUE THREAD

**Issue by arkuser** [arkenfox/user.js#1697]
Hello,

I hope I'm posting in the right place...

I'm using Linux.
I would like to know how to make Windows and Mac specific prefs not apply.
Indeed, in the user-overrides.js, you can add or modify a pref, it seems to me, but not make a pref never apply.

Thanks

**Comment by iam-py-test** [comment]
You need to run the updater: https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain
Thanks

**Comment by arkuser** [comment]
> Write your own script that comments/removes those lines.

Not easy for me. Any advice ?

**Comment by iam-py-test** [comment]
You need to run the updater to apply the user-overrides

**Comment by rusty-snake** [comment]
@iam-py-test I think arkuser did that. The behaviour they want is that the pref does not show up as change in about:config resp. is never created.

**Comment by rusty-snake** [comment]
> Not easy for me. Any advice ?

1. Create a list of all prefs you want to remove. There is no easy way to scrap the list with a script because of different syntax (where is `[WINDOWS]`, behind the pref or behind the description; what is with `[NON-LINUX]`; ...)
2. This is an updater script that can uncomment lines https://codeberg.org/rusty-snake/firefox-config/src/branch/main/assets/updater2.sh so you `//just: have^ to\" flip/` <sub>never use "just" when you talk about regex :laughing: </sub> the logic.

**Comment by arkuser** [comment]
> a pref that is OS specific will have no impact on an OS that doesn't apply, for example

This solves my problem.

Thank you all for your help.
