### ISSUE TITLE
Do not disable WebGL - RFP is now better. No real benefit. More breakage. More Uniqueness.

### ISSUE THREAD

**Issue by monsieuremre** [arkenfox/user.js#1700]
user.js recommends enabling WebGL only if it is necessary by overriding it. It is true that the randomization provided by RFP was limited to naive scripts until recently. I have found, however, that sites using more sophisticated techniques are also unable to fingerprint WebGL once it is enabled, even though they were able to this previously. So the resistance does not seem limited to naive scripts anymore. amiunique.org is one of these sites. Enabling WebGL allows no real surface to fingerprintability. Considering it is one of the more common reasons for breakage, and many projects, including even the TP Browser Bundle, already enable this by default, it seems only logical that user.js does not disable this. It causes more breakage and makes the browser significantly more unique. A modern engine with no WebGL support stands out, whilst providing no real benefit, as the protections by disabling it are in no way superior to those already provided by RFP.

**Comment by Thorin-Oakenpants** [comment]
you have no idea what you are talking about, including how TB handles webgl. Every sentence of your contains factually incorrect statements

**Comment by monsieuremre** [comment]
TB enables it by default in standard mode. It is disabled only in the safer modes. My assertions are just observations and not factual statements. If they are incorrect, which they might be, correcting them would be more helpful.

**Comment by KOLANICH** [comment]
If one got fully hacked through hacking GPU or its drivers, all browser-based fingerprinting vectors become completely insignificant, if one can read serials of the hardware and run native applications doing fingerprinting directly on hardware.

>breakage

If you care about breakage, you should use Googlag Chrome. It will finish implementing https://github.com/RupertBenWiser/Web-Environment-Integrity somewhen. Don't forget to buy a CPU with SGX/TrustZone or the websites will be broken.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-summary

> This is a very simple generalized short summary about non Tor Browser browsers that assumes worst case scenarios, ultimate outcomes, and real solutions - I am not interested in debating issues with non-experts.
> 
> > “One of the major difficulties Thorin experienced in her relationship with the Peacock was learning to distinguish between him pretending to be stupid just to get people off their guard, pretending to be stupid because he couldn't be bothered to think and wanted someone else to do it for him, pretending to be outrageously stupid to hide the fact that he actually didn’t understand what was going on, and really being genuinely stupid." - _Douglas Adams_


----

against my better judgement, and you have now officially wasted my time

> It is true that the randomization provided by RFP was limited to naive scripts until recently.

nonsense. read the wiki

I'm not even sure how to parse this nonsense. randomizing has ONLY ever added "additional" protection with naive scripts, it still does, the logic will never change. I say "additional" because protecting the real value (static/random) is still the goal. **_In other words, the only reason to randomize (outside technical reasons) is because of naive scripts_ and this will never change**

**_randomizing still and always has protected the real value, so also protects against advanced scripts, and this will never change_**

protection methodology doesn't change with just because firefox tweaks something or not (I have no idea why you think this has changed). Are you confusing webgl with canvas?

> I have found, however, that sites using more sophisticated techniques are also unable to fingerprint WebGL once it is enabled, even though they were able to this previously.

nonsense

If webgl is enabled, it can be fingerprinted - with a very large number of metrics, including equivalency from other metrics, and indeed from other metrics that have been patched, but not in webgl (e.g. math). webgl is extremely high entropy
If webgl is disabled, it gives one data point - look up what a `surprisal` is

> So the resistance does not seem limited to naive scripts anymore. amiunique.org is one of these sites. Enabling WebGL allows no real surface to fingerprintability. 

> Considering it is one of the more common reasons for breakage

webgl is niche. 99% of the web doesn't use it (figure pulled out my shiny yellow ass, because that's what you're doing). YMMV but I haven't had a single breakage from not having the API

> and many projects

other projects can get F'd - they are NOT arkenfox with AF's default threat model/settings (or with my expertise in this matter). If you are so upset by it, add an override - as per the wiki. Also, just quietly, a lot of other projects are fucking idiots especially when they undermine security

> including even the TP Browser Bundle, already enable this by default,

it's `TB` not `TP`. TB in standard mode limits it (although as a Tor Project member, not employee, I think we can do better here), as well as putting readPixels behind a Click-to-Play in safer.

RFP does nothing here except change a couple of parameters. RFP is not fit to properly protect webgl. This is why we disable it. In FPing terms: super high entropy and the surprisal far outweighs a single data point (not that it really matters since objectively we can't do better without a crowd, but there are degrees of advanced scripts, so it does help). It's also a security point (not that I think this is an issue for most users, and I'm not really following webgl CVEs etc) as in less surface area to attack

> makes the browser significantly more unique.

nonsense. you're already unique. read the wiki

> A modern engine with no WebGL support stands out

nonsense. you're already unique. read the wiki

/end of ... not even going to proof read it

**Comment by MagicalDrizzle** [comment]
> webgl is niche. 99% of the web doesn't use it (figure pulled out my shiny yellow ass, because that's what you're doing). YMMV but I haven't had a single breakage from not having the API

I just want to say it's kind of indispensable for bioinformatics ^^
Especially to render proteins, mostly because [Molstar](https://github.com/molstar/molstar) (webgl) has superseded [NGL](https://github.com/nglviewer/ngl) (webgl) and [JSmol](https://wiki.jmol.org/index.php/JSmol) (javascript) 
try browsing [Protein](https://www.rcsb.org/3d-view/1FIQ/1) [Data](https://www.ebi.ac.uk/pdbe/entry/view3D/1fiq/?view=entry_index&viewer=litemol&assembly=1) [Bank](https://pdbj.org/molmil2/#fetch%201fiq;%20repr%20au;%20style-if%20structure;) or [UniProt](https://www.uniprot.org/uniprotkb/P05067/entry#structure) without webgl, you won't get very far if you want to look at proteins

**Comment by Thorin-Oakenpants** [comment]
sure :) And like canvas, it will gain in popularity. I mean, a lot of sites now you need canvas to even upload an image, or for online apps - e.g.math, or look at google where you need canvas just to enter text (https://bugzilla.mozilla.org/show_bug.cgi?id=1848493 google sheets example -> https://bugzilla.mozilla.org/show_bug.cgi?id=1845828 ) 

OT: I hope one day RFP moves to subtle canvas randomizing. I planted to seed at tor project back in costa rica: standard mode use FPP's peristent perELTD+1 subtle canvas, safer use totally fubared per execution

**Comment by Thorin-Oakenpants** [comment]
sure, but part of the reason I do that is so AF doesn't "become the nazi bar"
- https://www.techdirt.com/tag/nazi-bar/
- https://old.reddit.com/r/TalesFromYourServer/comments/hsiisw/kicking_a_nazi_out_as_soon_as_they_walk_in/

not calling anyone an actual nazi :)

So the thing is, we flip 110+ prefs, of which around 10 are common issues (everyone's mileage differs), and I'm trying to get that down. Users are expected to override to suit (and I'll never please everyone). I have two options: reasonably-hard (like now) or way-more-friendly (move 7 or 8 prefs into optional hardening). Anything inbetween doesn't make sense to me. If we're going to do RFP, then we do referers and webgl and LBing and DRM etc

That said, when FFP is ready and when RFP targets are hooked up and working as expected then we have some more options

And depending on the trajectory of Mullvad Browser (we're thinking it stays in PB mode, but we add a New Normal Window option, which can keep logins/cookies - it's just an idea, don't get too excited) there are even more options
- relax AF by switching to FFP, allowing referers/DRM/webgl/keywords/etc (move them to optional hardening) and recommend MB for everything with AF as a fallback for broken stuff
   - which I like because as you said, webgl is behind ma1's click to play
   - this also means MB is the "do FPing right" approach and AF would be compat friendly FFP - i.e is we say USE MB
   - and RFP is going to become a free for all with RFP targets, so I'm not interested in that either. I appreciate that targets allow webcompat rules to unbreak things, but for RFP itself, it's global. And because users can toggle each individually, it just removes the whole point of it (ultimately lowering entropy). I get that FF is not a FPing crowd, but it could have been. Disappointed to be honest. I would have preferred three levels like Brave: off, standard, agressive
- discontinue AF

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/TalesFromYourServer/comments/hsiisw/kicking_a_nazi_out_as_soon_as_they_walk_in/
> and he said "yeah, you have to ignore their reasonable arguments because their end goal is to be terrible, awful people."

Just to be clear, not saying your aim was to be terrible, but some people are. They're like rabid misinformed full-tinfoiled rabbits chasing a car. fxbrit the 🐟  can attest with Librewolf - the non stop BS over outgoing connections. Or the reddit/HN etc posts/comments about Mozilla etc, usually twisted out of recognition, cherry picked, etc. I don't want to become the home of the deeper/neocities/snakeoil whatever those sites are with their nonsense

The same has gone for fingerprinting discussions the last few years. So not that FPing related questions or ideas are terrible, I'm just sick of typing about it. It gets very time consuming, because I have to add riders/conditions/assumptions to each statement and explain extra stuff, because I have to assume the readers will be fully ignorant. Or I have to ask what exactly the poster means because they are imprecise. Whereas talking about it amongst e.g. tor browser devs, it's 1000x faster because we understand the assumptions, equivalency, APIs, etc (very rare we get wires crossed) - although to be fair, they don't always fully understand me at first sometimes, and I need to work on screaming at them louder .. no wait, making myself clearer.

The same goes for not reading the wiki/user.js, or not filling in issue templates - insta-invalid, don't waste my time. It's also why I rewrote the wiki and added answer labels, etc. There's very little people should be asking about. I want this repo to be set and forget from my perspective, and these days it largely is

thanks for reading, I'm shit at writing
