### ISSUE TITLE
RFP site exceptions [A: you don't]

### ISSUE THREAD

**Issue by izar3** [arkenfox/user.js#1711]
How do you set a site exception for RFP on the URLbar?

Documentation is very vague:

```
user.js:
25:  6. Override Recipes: https://github.com/arkenfox/user.js/issues/1080

771: /* 4501: enable privacy.resistFingerprinting
772: / * [SETUP-WEB] RFP can cause some website breakage: mainly canvas, use a site exception via the urlbar
773: / * RFP also has a few side effects: mainly timezone is UTC0, and websites will prefer light theme

https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D#-rfp
```

Searching other issues brings up CTRL+I and enabling canvas? but site is still broken

Site what is not working RFP on is twitch d0t tv. Go into any category and scroll and new channels fail to load

Browser version & OS:
Firefox v116.0.2 on Arch linux

ty

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

**Comment by Thorin-Oakenpants** [comment]
the site exception is for canvas, not RFP itself

**Comment by Thorin-Oakenpants** [comment]
oh, I should also mention that in the future we will be able to have two different mode of FP protection, and RFP will be able to have some protections disabled

So the first is we will be able to use RFP in normal windows, and FFP in private windows. FFP is a work in progress (and almost ready). Initially (more will be added) will subtly randomize canvas, audio has been normalized for all users in FF118+, it returns 0 for window/screen positions (I think) and it will use font vis level 2. So in effect, if something is totally fucked in normal mode, you can just flick it open in a PB window. FFP will also have compat rules - so they can ship an unbreak per site (i.e not apply e.g. canvas on site A) - but these are very basic protections so far and shouldn't break anything

No, we cannot have FFP in normal windows and RFP in PB mode - it's not engineered to do that

---

For RFP itself, we can create our own set of what to apply globally - using RFPTargets. Since the main emphasis of RFP for us is fooling naive scripts, then relaxing some of the others is not as much of a concern. Personally I think it's a bit silly - RFP is an all-in or nothing approach, at best it could have three levels (like brave's FPing shield levels - off, standard, aggressive) and per site. But I get the engineering side of it, where all those RFPTargets allow crafting compat rules, and these FPing protections will slowly start to creep into FFP

So AF moving forward has some options with defaults and override recipes
- `a` we could use FFP mode in all windows
- `b` we could use RFP in normal windows and FFP in PB windows
- `c` we could relax some RFP protections

So for example, if you have a monitor where the FPS !== 60 and it causes videos/animations etc dropping frames, you could modify the pref to apply all _but_ timing protections.

https://searchfox.org/mozilla-central/source/toolkit/components/resistfingerprinting/RFPTargets.inc

I _think_ I will go with option `a` down the track. While I do think RFP (no exceptions to targets) is best (the more metrics protected, the better the chances, plus it has timing mitigations), this really is best suited for a crowd and a different threat model - use Mullvad Browser, Tor Browser

**Comment by Thorin-Oakenpants** [comment]
actually ... you can try this but you will probably get wonky results: i.e some RFP still applies - it's not something upstream has time for, and might even get deprecated

```js
/* 4505: experimental RFP [FF91+]
 * [WARNING] DO NOT USE unless testing, see [1] comment 12
 * [1] https://bugzilla.mozilla.org/1635603 ***/
   // user_pref("privacy.resistFingerprinting.exemptedDomains", "*.example.invalid");
```
