### ISSUE TITLE
Use Firefox's native translate feature with arkenfox?

### ISSUE THREAD

**Issue by Dupond** [arkenfox/user.js#1721]
Hello!

My native language is not english. I use Firefox 117.0 with Arch Linux.

Starting in Firefox 117 Stable, Firefox includes a translate feature (behind a pref: `browser.translations.enable`); when using arkenfox, Firefox does not offer English-to-French page translation due to the [0210] preference:

```
user_pref("intl.accept_languages", "en-US, en");
```

I assume it has privacy implications (I think you're simply less unique using the en-US locale - especially when using a VPN, which I do.)

So, my questions would be:

- is there another pref that could be changed to be able to use the translate feature safely (from english internet pages) for the non-english language speakers?
- if not, I suppose I'll have no choice but to modify `intl.accept_languages`; but in this case, are there other prefs that should be edited at the same time so that my arkenfox preferences remain consistent? In other words: is it possible to safely change your Firefox language using arkenfox?

Thanks in advance for any advice you could give me!

**Comment by rusty-snake** [comment]
> if not, I suppose I'll have no choice but to modify intl.accept_languages; but in this case, are there other prefs that should be edited at the same time so that my arkenfox preferences remain consistent? In other words: is it possible to safely change your Firefox language using arkenfox?

I do not try to hide my language, using these overrides:

https://codeberg.org/rusty-snake/firefox-config/src/commit/46bf810d43d4c7ecc56d36ca0dbb4ef95cd3cd88/assets/user-overrides.js#L5-L10

also see

https://codeberg.org/rusty-snake/firefox-config/issues/2#issuecomment-401542

> change your Firefox language

There are two things, the language of the Firefox UI (menus, ...) and the language you request from websites. They do not have to be the same.

> I assume it has privacy implications

TBH, don't bother if it interrupts you in your daily work. If your threat model *requires* hiding your language/region you should use the Tor Browser. Otherwise, if you use Firefox+Arkenfox, there are other more unique things then being from France.

**Comment by rusty-snake** [comment]
> I've tried to restart the profile several times to see if the new language pack would be applied, but it isn't: so I have to go to Settings > General > Language and manually select "Français" in the drop-down menu. Is this expected?

It's because of `extensions.enabledScopes`. The hardening arkenfox applies here does not work with well with the way the most Linux distros install/update language packs. Setting by hand works (until an updated).

To (hopefully) solve try the following

https://codeberg.org/rusty-snake/firefox-config/src/commit/46bf810d43d4c7ecc56d36ca0dbb4ef95cd3cd88/assets/user-overrides.js#L48-L49

> But I guess that I have no other choice if I want to be able to to use the Firefox translation feature

ATM likely yes.

> Also, is the loss of privacy really significant, or is it minor?

:jeans: can say more.

**Comment by Dupond** [comment]
> It's because of `extensions.enabledScopes`.
Right. Thanks for the clue!

> 'unique' is not a spectrum. 'unique' is binary.
Well... "more unique" is a common (but wrong, you're absolutely right about that) way of saying that there's a better chance of being unique ;)

Many thanks for all your help!

**Comment by Thorin-Oakenpants** [comment]
fyi: `javascript.use_us_english_locale` is deprecated in FF119+
