### ISSUE TITLE
Still compared periodically to Pyllyukko's updates?

### ISSUE THREAD

**Issue by e-t-l** [arkenfox/user.js#1726]
To avoid resurrecting #10: Just curious if you ever still cross-compare with [pyllyukko](https://github.com/pyllyukko/user.js)? That user.js still gets updated from time to time, and it would be good to know if there have been any major divergences between the two since... 2017?

**Comment by Thorin-Oakenpants** [comment]
no, because they do not keep anything up to date, plus IMO they make some really dubious/dumb/weird decisions, for whatever reason. Last time I checked about 3 or 4 years ago, almost half (from memory) of their prefs were deprecated - it'd be way higher now. And a heap of what's left are just "silly" (e.g. disabling all the crypto and protocol handlers etc) - it's basically abandoned AFAIConcerned
