### ISSUE TITLE
Does disabling WASM affect WebExtensions?

### ISSUE THREAD

**Issue by nihil-admirari** [arkenfox/user.js#1727]
WASM seems to be rather rich in CVEs. It's being used by e.g. uBO though. So the question is: does disabling `javascript.options.wasm` affect only web pages or uBO won't be able to use it too?

**Comment by Thorin-Oakenpants** [comment]
the 5000 section is not recommended and considering billions of people use them (wasm, svg, ion/jit etc), the threat model here is overrated. FWIW, TB flips wasm off in safer mode, not standard - and TB ships in standard mode.

It's already noted in the user js that this section tends to break things - wasm is no different, e.g. it is used for some logins now, and it's only going to get worse (breakage). I'm basically not supporting section 5500 - it's there to tell people not to use those prefs and to get them reset by prefsCleaner

as for "does it affect extensions" - I vaguely recall an issue where it did (bitwarden or something), but this may have changed upstream (e.g. just like how RFP no longer applies to extensions - because of the principal). Mullvad Browser and Tails-TB both ship with uBO but I haven't heard of any issues with uBO in safer mode - that's not to say there aren't any, or that they can't happen in the future

**Comment by nihil-admirari** [comment]
> haven't heard of any issues with uBO in safer mode

Issues may be absent because uBO can fallback to non-WASM, not because WASM continues to be available for extensions.

**Comment by Thorin-Oakenpants** [comment]
so if it falls back, is that because of 1. legacy browser releases or 2. because the API is disabled. I mean it's not hard to feature check, but not all ext devs think of these things, or if they did it was only because it wasn't fully supported at the time

anyway, it made me open https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42119 .. so feel free to keep an eye on that

**Comment by Thorin-Oakenpants** [comment]
Normally those get added so users know a fix is coming in the next ESR. After a while the info becomes obsolete, because no one should ever get an error and have to troubleshoot it

**Comment by KOLANICH** [comment]
>TB flips wasm off in safer mode, not standard - and TB ships in standard mode.

IMHO: the only mode for TB should be the `Safest`.
