### ISSUE TITLE
WebGL is no longer disabled completely on BrowserLeaks (on my end)

### ISSUE THREAD

**Issue by Dmaker13** [arkenfox/user.js#1784]
My WebGL image is being read on browserleaks until I turn "webgl.forbid-hardware" to "true". Then the fingerprinting resistance works.  I didn't see anybody else talk about this, so I thought to post. Is it a bad idea to set  "webgl.forbid-hardware" to "true" for any reason? I am a newbie, so its prob me. 

Oh yea, I noticed the webgl.diabled setting is off and locked.  When I try to reverse it in my user overrides, it doesn't work.

**Comment by Thorin-Oakenpants** [comment]
there is no RFP for webgl except for
- [1217290](https://bugzilla.mozilla.org/show_bug.cgi?id=1217290) + [1409677](https://bugzilla.mozilla.org/show_bug.cgi?id=1409677)
   - without digging, among other things it sets Minimal-Capabilities mode - see https://bugzilla.mozilla.org/show_bug.cgi?id=1684230#c8 and thus controls some parameters and values
- [1337157](https://bugzilla.mozilla.org/show_bug.cgi?id=1337157) - disable WebGL debug renderer info
   - this is AFAIK the `VENDOR`, `RENDERER`, `UNMASKED_VENDOR_WEBGL` + `UNMASKED_RENDERER_WEBGL`
   - see https://canvasblocker.kkapsner.de/test/webGL-Test.html

RFP does not protect against fingerprinting via readPixels(), which is why as a default, we disable webgl altogether
```js
/* 4520: disable WebGL (Web Graphics Library)
 * [SETUP-WEB] If you need it then override it. RFP still randomizes canvas for naive scripts ***/
user_pref("webgl.disabled", true);
```

excluding the entropy from parameters, their values, and other values (which is not insignificant), the actual rending itslef is liek canvas - i.e you can draw shapes, add colors, blend, stroke, add test, transform, use math .. and so on - as well as exploit the GPU - to get entropy

IDK what it is the browserleaks test is doing and what makes you think forbid-hardware makes your webgl FP safe

**Comment by Thorin-Oakenpants** [comment]
FWIW - default arkenfox and my browserleaks webgl FP is .. "it's all disabled"

**Comment by Dmaker13** [comment]
I reinstalled firefox instead of just refreshing and troubleshooting , and it worked! Sorry, next time ill try more troubleshooting before commenting. I was experimenting, setting up my vpn's proxies through the browser and must of did something. Or must of changed some default GPU setting. Thanks for being the developer that you are! I really like this configuration
