### ISSUE TITLE
Some prefs

### ISSUE THREAD

**Issue by pehkaher** [arkenfox/user.js#1792]
Hi, I found some preferences that I didn't see in arkenfox. (Source: https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/ ) :
user_pref("network.protocol-handler.external.shell",false); // SV-16710 - DTBF105
user_pref("dom.disable_window_open_feature.status", true); // SV-16717 - DTBF180
user_pref("security.enable_tls", true); // SV-16925 - DTBF030
user_pref("dom.disable_window_flip", true); // SV-16727 - DTBF182
user_pref("browser.newtabpage.activity-stream.enabled", false); // SV-111849 - DTBF230
user_pref("security.ssl3.rsa_des_ede3_sha", false); // SV-111851 - DTBF235
user_pref("extensions.update.enabled", true);
user_pref("xpinstall.enabled", true);
user_pref("devtools.policy.disabled", false);
user_pref("browser.disableResetPrompt", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.urlbar.groupLabels.enabled", false);
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("device.sensors.ambientLight.enabled", false);
user_pref("device.sensors.motion.enabled", false);
user_pref("device.sensors.orientation.enabled", false);
user_pref("device.sensors.proximity.enabled", false);
user_pref("extensions.CanvasBlocker@kkapsner.de.whiteList", "");
user_pref("extensions.ClearURLs@kevinr.whiteList", "");
user_pref("extensions.FirefoxMulti-AccountContainers@mozilla.whiteList", "");
user_pref("extensions.TemporaryContainers@stoically.whiteList", "");
user_pref("extensions.greasemonkey.stats.optedin", false);
user_pref("extensions.greasemonkey.stats.url", "");
user_pref("general.warnOnAboutConfig", false);
user_pref("media.autoplay.enabled", false);
user_pref("privacy.donottrackheader.value", 1);
user_pref("privacy.usercontext.about_newtab_segregation.enabled", true);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite", false);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", false);

**Comment by Thorin-Oakenpants** [comment]
please don't post lists of prefs at me - especially when they're out of date and ignorant

FFS
- `general.warnOnAboutConfig` is deprecated and has been basically dead since FF71 .. `XHTML` was discontinued
- `security.ssl3.rsa_des_ede3_sha` was deprecated in [FF73](https://bugzilla.mozilla.org/1724072)
- `extensions.extensionsname....` - extensions haven't used prefs since IDK, FF68'ish - they have to use locale storage
- `device.sensors` - are not a thing in WINDOWS, your source is aimed at windows

i'll just stop there, to save wasting my time (donottrack pref is useless, newtab into is useless, firstrun is useless ... ) ... it's like a bad joke
