### ISSUE TITLE
VPN leaking DNS. Throubleshooting advise needed!

### ISSUE THREAD

**Issue by HighOnBuffs** [arkenfox/user.js#1794]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ✔ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 121.0.1 Windows 11
  - Steps to Reproduce (STR): ipleak.net
  - Expected result: No DNS leak
  - Actual result: DNS leak
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

Im using a VPN and while Librewolf doesnt leak DNS, Firefox + Arkenfox user.jss (which i prefer) does and i cant figure out why.
Which settings could likely cause this? I search everything for DNS but it didnt change anything.

**Comment by Thorin-Oakenpants** [comment]
so I closed this because it's not actionable
- what VPN?
- is it a system wide one, or an extension
- where does ipleak say you leak?
- does it happen with a vanilla Firefox profile
- what did you change in about:preferences#general > Network > Settings (which AF does not touch or set) - do any of these differ from LW

basically, AFAICT, this is not an AF issue - but feel free to continue the discussion and maybe someone else can help
