### ISSUE TITLE
Youtube is not displaying HDR content.

### ISSUE THREAD

**Issue by RenePunch** [arkenfox/user.js#1796]
So I recently installed arkenfox and I figured out most of the settings however I then realized that youtube wasn't playing hdr content anymore. Is there a fix for this?

**Comment by Thorin-Oakenpants** [comment]
I don't use YT at all, so I have no idea about `HDR` or what is meant by that - perhaps others can chime in, otherwise you [bisect](https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-manual) the prefs in a new profile to find the culprit(s)

**Comment by RenePunch** [comment]
Never mind I figured it out. I had to edit the RFP settings in the User.js.

**Comment by Thorin-Oakenpants** [comment]
what part of RFP causes this can be tested with RFPTargets - my first guess would be the mismatched HTTP userAgent header in linux/mac (although what that has to do with serving video I am not sure - either the client says it supports it or not - but strange things happen with this setup, see twitch, netflix, various webrtc - it's like websites get their knickers in a twist for no good reason)

**Comment by RenePunch** [comment]
So I disabled 4501. Which is the enable RFP setting. Anytime I renabled it would cause websites like youtube to not display hdr content or sites like overleaf having blurred PDF images when I'm typing a LaTeX file. It kinda sucked that I had to disable resist fingerprinting to get the sites to work like normal again. So I installed the canvas blocker extension to kinda compensate for that. I don't know if this a bug or just something that was overlooked.

**Comment by RenePunch** [comment]
this was the setting. I switched it to false. 
user_pref("privacy.resistFingerprinting", false);

**Comment by Thorin-Oakenpants** [comment]
>  or sites like overleaf having blurred PDF images

that's fixed when Firefox changes the devicePixelRatio spoof to `2` (from `1`) - they should be good to go - see https://bugzilla.mozilla.org/show_bug.cgi?id=1554751 - we've done it in Tor Browser for about 4 releases and no complaints

> So I installed the canvas blocker extension to kinda compensate for that

uninstall it. If you're not using RFP you will fall back to FPP (fingerprint protection) which randomizes canvas subtly (almost zero breakage, none that I know of - of course websites can still be assholes and detect that and misbehave but that's not breakage, it's assholery)

I say fall back to, because we are using ETP Strict and FPP is used in that mode and in private windows by default now (if RFP is not enabled), so don't change from ETP Strict. FPP also protects your fonts, it's ~~more lax than RFP (which is `kBaseFonts` only) as it also adds `kLangPackFonts`~~ - see https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts-macos.inc .. seems as if it's all one list now

CB, depending on what you use, e.g. you no longer need audio (entropy was low to start and now all users regardless of settings are in two buckets - excluding some extra RFP protections such as hrtz which show up in context keys and oscillator - oscillator is perf heavy) .. e.g. canvas can be, and textmetrics, clientRect/domRect etc can all affect perfomance - I find testing with CB is very slow

t;dr: do not ever use any FPing extensions - they have signatures in proxy lies etc and can't cover everything (e.g. leaks via service workers etc)
