### ISSUE TITLE
Exceptions get cleared with shutdown?

### ISSUE THREAD

**Issue by Tripp1e** [arkenfox/user.js#1800]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: ESR + Windows 11
  - Steps to Reproduce (STR): Clean install of firefox. Use non modified Arkenfox. Add Exception for Cookie Clear on shutdown. Close and open firefox. Exception list is empty.
  - Expected result: Exception List does not get cleared.
  - Actual result: Exception List gets cleared.
  - Console errors and warnings: None
  - Anything else you deem worth mentioning: No

---

I also did a little digging, however everything that google showed me was either outdated or did not work (Like disabling RPF)

The wiki states that I dont need to change any prefs, just add an exception, but this does not work, as explained.

**Comment by Thorin-Oakenpants** [comment]
> Add Exception for Cookie Clear

please explain what this is?

**Comment by Tripp1e** [comment]
Settings>Privacy & Security>Delete Cookies and site data when Firefox is closed>Manage Exceptions...

**Comment by Thorin-Oakenpants** [comment]
I'll try again .. what did you add?

**Comment by 2glops** [comment]
Your exceptions are visible on
Settings>Privacy & Security>Delete Cookies and site data when Firefox is closed>Manage data after closing / on re-start

and not anymore on ... Manage Exceptions

**Comment by Thorin-Oakenpants** [comment]
So the reason I asked what you were putting in was to check if you were doing it right - e.g. adding the scheme and choosing Allow - here's mine

![me1](https://github.com/arkenfox/user.js/assets/16656956/5ff72a68-3dcc-4ba3-93a9-e2fa9fe01af1)

These are `site exceptions` - e.g. zoom levels, permissions such as blocking notifications/geo etc. Arkenfox does not clear those. Here are MY settings - note, `site exceptions` is not checked and has NEVER EVER been set to clear by arkenfox

![me2](https://github.com/arkenfox/user.js/assets/16656956/e0e41693-ed4d-4a93-9f1d-f367c695c55e)

I haven't actually had time to test in a new profile, but will do so if you can't figure it out - but 99.9% sure I'm not going to be able to replicate. I have no issue with retaining logins that I want, and no one else has ever had this issue, over IDK, a dozen+ releases

**Comment by Tripp1e** [comment]
https://github.com/arkenfox/user.js/assets/102437240/fbc3b1dc-f911-4c3a-9142-4cbf65e573da


This is a completly fresh profile, nothing installed on it.

**Comment by Thorin-Oakenpants** [comment]
Oh, you're on ESR115 - that shit doesn't work on ESR - read the docs - pretty sure I made it all clear in the docs

**Comment by Tripp1e** [comment]
So is there a fix?

Also I cant find, where you 'made it clear'

**Comment by Thorin-Oakenpants** [comment]
> Also I cant find, where you 'made it clear'

I don't understand? If you mean the settings to decide what to clear on close, the UI is a little messy due to legacy/PBmode stuff. The exceptions are at the top under `Cookies and Site Data` (and this only affects cookies and site data), but what to clear is down nearer the bottom under `History > ... > Clear history when Firefox closes > Settings `

---

So I just tested on ESR115, brand new profile, and cannot replicate. And to clarify, this has been the AF setup since FF103 and no-one else has had this issue - so 19 releases

lets check some basics
- do you have any other modifications, pref changes (e.g. site settings in memory only)
   - yes, I know you said it was a new profile, but you also added CanvasBlocker so who knows
- did you run prefsCleaner?
   - yes, I know you said it was a new profile, so it can't hurt can it! :) just in case
- do you have any software such as CCleaner or Bleachbit (you should never let these touch browsers)
   -  this seems unlikely given your video which was like 2 seconds between close and open
- did arkenfox apply cleanly: open about:config and type in `parrot`
   - this also seems like a red herring given the site settings shouldn't be affected by AF anyway
- open about:profiles - did you use the right profile
   - also unlikely
- is it the same profile each time?
   - why not check, I've seen some weird shit in my time

let's at least check this
- when you add `https://github.com` and click `Allow` and click `Save`, open it again and see if it's still in there

**Comment by Thorin-Oakenpants** [comment]
for anyone following along at home - the sanitize on shutdown prefs get changed at some point: https://bugzilla.mozilla.org/show_bug.cgi?id=1876097

**Comment by Thorin-Oakenpants** [comment]
> From the video it looks like this is a heavily modified Firefox

not necessarily, some quick adjustments in a new profile doesn't have to have an impact (such as cleaning up the tabstrip, adding search, removing spaces etc)

but you're right. OP hasn't shown what they have for History. If PB mode, or clear site exceptions is enabled, then that would explain it. Would also explain why OP can't find "where to clear" if IIUIC.

**Comment by Thorin-Oakenpants** [comment]
> or permanent private mode is used.

if started in PBM the UI looks like this (tested in ESR115), so it's no in PBMode

![PBM](https://github.com/arkenfox/user.js/assets/16656956/48288b0e-32f7-4b90-a869-40a103851717)

**Comment by Thorin-Oakenpants** [comment]
going to close this as invalid and treat it as a user issue - 19 releases and no-one else has this issue, plus OP (so far) hasn't shown/used the right steps (e.g. new profile, no other changes)

**Comment by Tripp1e** [comment]
In the End I completly uninstall firefox, deleted all APPDATA folders and wiped the registry then reinstalled and now everythings working fine, even after using extensions

**Comment by Thorin-Oakenpants** [comment]
glad you got it sorted :)

**Comment by Thorin-Oakenpants** [comment]
FYI as mentioned before about new prefs (and new UI) - https://bugzilla.mozilla.org/show_bug.cgi?id=1854680- looks a lot cleaner for sure (and thank fuck that "active logins" is gone, people always thought that meant cookie logins)

![oooh](https://github.com/arkenfox/user.js/assets/16656956/46824590-7b96-4301-9281-62e42a6646c5)
