### ISSUE TITLE
track sanitizing migration slated for FF127/8

### ISSUE THREAD

**Issue by MagicalDrizzle** [arkenfox/user.js#1837]
https://www.mozilla.org/en-US/firefox/126.0beta/releasenotes/
> A simpler and more unified dialog for clearing user data is now available.
> In addition to streamlining data categories, the new dialog also provides insights into the site data size corresponding to the selected time range.

```js
pref("privacy.clearOnShutdown_v2.cache", true);
pref("privacy.clearOnShutdown_v2.cookiesAndStorage", true);
pref("privacy.clearOnShutdown_v2.historyFormDataAndDownloads", true);
pref("privacy.clearOnShutdown_v2.siteSettings", false);
pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs", false);
pref("privacy.sanitize.cpd.hasMigratedToNewPrefs", false);
```
Maybe we should enforce the bottom two prefs as false to prevent data loss while this new thing is figured out?

**Comment by Thorin-Oakenpants** [comment]
we have diffs issues, and I am aware of the new [Data Sanitation](https://firefox-source-docs.mozilla.org/toolkit/components/antitracking/anti-tracking/data-sanitization/index.html) and rollout - it's currently nightly only

sorry, just saw your last sentence after I labelled `invalid` .. still .. anyway, there will be no data loss - I mean it was just rolled back from beta due to exactly that (history was wiped when it shouldn't have)

also, pretty sure the migrated prefs will be changed at runtime, and setting them to false won't be effective, otherwise I _think_ the migration will match exactly what you have in your overrides (super early nightly migration was hit and miss)

**Comment by Thorin-Oakenpants** [comment]
^ in other words, 99% sure there's nothing for me to do until AFTER the rollout

**Comment by Thorin-Oakenpants** [comment]
here's the meta - https://bugzilla.mozilla.org/show_bug.cgi?id=1853996

and here's the new rollout - https://bugzilla.mozilla.org/show_bug.cgi?id=1895612

hope this lands in 128 so the next ESR is on the same playing field

Also, FYI, putting migrate prefs in the user.js is fraught, because prefsCleaner would reset them and cause another migration (IIUIC)

**Comment by MagicalDrizzle** [comment]
The new sanitation thing is more than "just" the GUI change right? because FF126 definitely has the new dialog thingy

**Comment by Thorin-Oakenpants** [comment]
nah, they rolled it back, as I said. If they haven't hooked up the new prefs, they can't really hook up the new UI .. and if they hook up the new UI they'll need the new prefs - so it's all about the migration .. but who knows, maybe they can toggle each on individually but there's no point in doing that

![okie-dokie](https://github.com/arkenfox/user.js/assets/16656956/aede8b9a-3e61-4a24-91bb-1750b2d41a2d)

but I've reopened so we have a issue to track it (but I doubt we'll need it)

**Comment by Thorin-Oakenpants** [comment]
it's already tee'd up for 128: https://bugzilla.mozilla.org/show_bug.cgi?id=1895612#c1 (won't be pushed since we're in RC week)

**Comment by MagicalDrizzle** [comment]
aah, I see
beta channel has release candidate shipped while dev edition does not
yeah that's probably some super common knowledge that today I just learned lol, my apologies for bothering

**Comment by Thorin-Oakenpants** [comment]
I have beta here as well, but I almost never use it because it hates running concurrently with any other firefox.exe

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1895612#c5

> pref migrations:
> 
> `privacy.clearOnShutdown.history` --> `privacy.clearOnShutdown_v2.historyFormDataAndDownloads` (only the history value matters, downloads and formdata are ignored in this migration `privacy.clearOnShutdown.downloads`, `privacy.clearOnShutdown.formdata` )
> 
> `privacy.clearOnShutdown.cookies` --> `privacy.clearOnShutdown_v2.cookiesAndStorage` (only cookie value matters, active logins and offline website data are ignored in this migration)
> 
> `privacy.clearOnShutdown.cache` --> `privacy.clearOnShutdown_v2.cache`
>
> `privacy.clearOnShutdown.siteSettings` --> `privacy.clearOnShutdown_v2.siteSettings`

**Comment by Thorin-Oakenpants** [comment]
so this means e.g. `v2.historyFormDataAndDownloads` is all in one and you can't choose history separate to forms+downloads (which were linked in the past) .. and `vs2.cookiesAndStorage` is a catchall for offline website data (IDB, localStorage etc) and active logins (which is old timey crap not logins per se)

nice, four options instead of 7- I think I can add this ahead of time without too messy

**Comment by Thorin-Oakenpants** [comment]
and that should just leave cpd which I think is all the new prefs in 125

**Comment by Thorin-Oakenpants** [comment]
closing - this wasn't as messy as I thought - the 4 _v2 prefs slotted in nicely - thanks @MagicalDrizzle , this did need it's own special issue since the prefs are from old timey diffs and stuff

PS: adding the migrated prefs would mean they would get reset with prefsCleaner and cause repeat migrations which can get messy for users since it would happen after user.js (I think)

**Comment by Thorin-Oakenpants** [comment]
there's also a `privacy.clearOnShutdown_v2.downloads` pref but it's hidden pref and legacy nonsense from the migration - since downloads was always controlled by `history` in v1, and is now tied into `historyFormDataAndDownloads` in v2, so I'm going to ignore it

**Comment by theltalpha** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1895612#c5
> 
> > pref migrations:
> > `privacy.clearOnShutdown.history` --> `privacy.clearOnShutdown_v2.historyFormDataAndDownloads` (only the history value matters, downloads and formdata are ignored in this migration `privacy.clearOnShutdown.downloads`, `privacy.clearOnShutdown.formdata` )
> > `privacy.clearOnShutdown.cookies` --> `privacy.clearOnShutdown_v2.cookiesAndStorage` (only cookie value matters, active logins and offline website data are ignored in this migration)
> > `privacy.clearOnShutdown.cache` --> `privacy.clearOnShutdown_v2.cache`
> > `privacy.clearOnShutdown.siteSettings` --> `privacy.clearOnShutdown_v2.siteSettings`

What I have not understand: Are the legacy sanitizing prefs literally deprecated as of FF128 (ESR)? That means, as soon as we have the "v2" sanitizing prefs present in our user.js, may we at the same time remove the legacy sanitizing prefs? Or still in other words, what is the purpose of having both the legacy and the "v2" prefs in our user.js?

**Comment by Thorin-Oakenpants** [comment]
There's a migration pref, so I would assume that once the migration is done, the old prefs are no longer used to set the new prefs

We have all the prefs in the user.js for legacy users - and they all match (i.e the legacy prefs match the new prefs). I'm not sure when the migration itself happens - before or after user.js kicks in. Worst case scenario it takes another FF start. But as I said, the user.js contains all of them and they match.

There is no reason to modify the user.js - when they are deprecated then they will be moved to the deprecated section for prefsCleaner and eventually removed

As for any overrides, personally, I would just keep them there until they are actually deprecated - but if you want, remove the old legacy overrides and try it out :) You should be fine
