### ISSUE TITLE
`incoming.telemetry.mozilla.org`

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1845]
I use Pi-Hole and I noticed that the `incoming.telemetry.mozilla.org` URL is being blocked:
![image](https://github.com/arkenfox/user.js/assets/13978119/41deca16-3adf-4893-949a-6235afe10d6d)

This raises the question - why it's there in the first place?
I already use arkenfox and on top of that - in `about:telemetry#raw-payload-tab` there's nothing.
So now I'm even more confused, while there's no telemetry in `about:telemetry`, my Pi-Hole says my IP (this PC) is trying to contact `incoming.telemetry.mozilla.org`.

Clarification 1: This is a fresh install of Windows with only Mozilla Firefox + arkenfox.
Clarification 2: My DNS is Pi-Hole.

Any ideas?

**Comment by rusty-snake** [comment]
Everytime or just once? If it is just once it could be the installer.

Anyway, requesting the DNS record is not a privacy issue. Maybe it just does the DNS query unconditionally, IDK.

**Comment by silverwings15** [comment]
i'd also like a technical answer if possible, instead of the usual handwaving and outright dismissal we tend to see

**Comment by Thorin-Oakenpants** [comment]
> instead of the usual handwaving and outright dismissal

this ties into #1660 . Please don't describe _my_ contributions and time on this as handwaving and outright dismissal, thank you. That really kinda offends me.

I _get_ that some users want a "quiet" fox ... but I am concerned here with _actual_ privacy issues, and a AFAIK (but will always check) is that there really are none (more discussion can be held on the other issue). That said the current state of arkenfox, using the master switch for telemetry and some extras, should cover anything of "concern" for those who want peace of mind.

---

Obegg .. on a new profile, _before_ arkenfox has been added and applied, some telemetry can be collected. I tend to use portable windows versions and after setting up I remove everything manually - e.g. `about:telemetry` should have nothing, and with FF closed you can empty `profile\datareporting`, `profile\crashes`
- that said we do block sending backdated telemetry
- and you already checked :) 👍 

There is also pingsender, which is a scheduled task on windows. From memory it uses the last setting read, so multiple profiles can affect it (it's all a bit hazy TBH) - https://docs.telemetry.mozilla.org/datasets/pings - not even sure what the endpoint is

If all it is doing is a DNS lookup, then there is nothing to even look at here - as @rusty-snake says ... "Maybe it just does the DNS query unconditionally, IDK". I wonder if Librewolf exhibits this, since they build with the disable telemetry flag.

Leaving open for now, but I honestly don't see anything for me to do here

**Comment by Thorin-Oakenpants** [comment]
maybe don't block it and inspect the payload if there is anything sent?

**Comment by Thorin-Oakenpants** [comment]
> maybe you will find a way to stop incoming.telemetry.mozilla.org for the rest of the users

since I don't consider this a privacy issue, I'm not going to do anything else

`profile\datareporting` will rebuild itself, but of course contain nothing to send and not collect anything once AF is applied. then again, if it did have something I would have expected it to show something in about:telemetry - IDK, not really interested in the engineering - maybe the "ping" folder is treated differently :)

**Comment by Thorin-Oakenpants** [comment]
PS: let us know it it returns :)
