### ISSUE TITLE
How to enable click to copy?

### ISSUE THREAD

**Issue by alexkwa** [arkenfox/user.js#1865]
I've got 
`user_pref("dom.event.clipboardevents.enabled", true); // 7013 enable cut/copy/paste`
but can't use any click to copy function on websites.

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 127.0.2 on MacOS 14.5
  - Steps to Reproduce (STR): Go to any click to copy function like [this one](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp) and click to copy
  - Expected result: Text is copied
  - Actual result: Nothing is copied (clipboard remains with old value)
  - Console errors and warnings:
  - Anything else you deem worth mentioning:
My overrides.js

```
user_pref("media.gmp-widevinecdm.enabled", true); // 2021 enable winevine for Netflix
user_pref("media.eme.enabled", true); // 2022

user_pref("browser.startup.page", 3); // 0102: override recipe: enable session restore

user_pref("keyword.enabled", true); // 0801: disable location bar using search

user_pref("privacy.clearOnShutdown.history", false); // 2811

user_pref("dom.event.clipboardevents.enabled", true); // 7013 enable cut/copy/paste

user_pref("javascript.options.wasm", true); // 5506: enable WebAssembly [FF52+] for Bitwarden Argon2id

```
---

**Comment by Thorin-Oakenpants** [comment]
sidenote

7013 is already commented out in the user.js, so you shouldn't need to add it as an override
- https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#2475
- and it's default enabled on all platforms

`javascript.options.wasm` is also default true in FF and commented out in the user.js

while it won't hurt to have then added as overrides, it's not recommended because it blocks upstream changes (not that I think they would change these ones) and adds noise to your setup

---

Worksforme on windows. Make sure you're not blocking something with an extension

**Comment by Thorin-Oakenpants** [comment]
closing as invalid - arkenfox does not change any clipboard settings
