### ISSUE TITLE
Noob (likely invalid) question about TZP'ing vanilla AF (also vanilla FF + RFP)

### ISSUE THREAD

**Issue by BingoBongoLad** [arkenfox/user.js#1868]
This is probably just dumbness on my part and obvious to many of you but since I can't come up with a valid answer by myself despite kinda trying, I'm asking here.
When I run the [TZP test suite](https://arkenfox.github.io/TZP/tzp.html) while on Firefox 127.0.2 clean profile + vanilla AF user.js v126-1 and no overrides the only 2 values that prevents me from getting a nice green "score" (definitely not what that is but please bear with me here) like I do with TB and MB are always <html><body>
<span translate="no">
inner window | 1600 x 900 				 [✓ LB] 				 [✗ RFP newwin]
-- | --

</span>
</body>
</html>

and <html><body>
<span translate="no">
[offset] timezone | 2024-07-01 17:09:56 \| 2024-07-01 19:09:56 [-120] [✗ RFP]
-- | --

</span>
</body>
</html>

On Firefox 127.0.2 clean profile + `privacy.resistFingerprinting` set to `true` just the [offset] timezone value.
Now as for the RFP newwin I think `4502` is the cause, and as to why TB and MB are not effected is I believe because the newwin sizes are coded directly inside the browsers (sorry for the lack of proper terminology lol)?
But the [offset] timezone value bugs me because I thought RFP was a big whole package pretty much similar across all the FF derivatives but that's not the case?
TB and MB give me<html><body>
<span translate="no">
[offset] timezone | +00:00 [✓ RFP]
-- | --

</span>
</body>
</html>
by the way.

My question(s) is, why is that the case, why is it not the same result on Firefox as it is on TB and MB? Also can Firefox achieve the same result as TB and MB?
I know this is not the place to ask, did not want to post on the TZP repo because I saw only technical issues over there but maybe here I'll get an answer.

**Comment by Thorin-Oakenpants** [comment]
so there's about 2 years worth of letterboxing and betterboxing improvements from Tor Project that we want to uplift to FF, including
- using css grid instead of setting a viewport size directly
   - for example, this means the findbar/docked-console on one tab no longer affects all the other tabs in the same window
- improved handling of floating points (to help stop all the slight 1px off sizes - e.g. having a 99px vertical matte)
   - this still needs work, but it's a big improvement, including logging to troubleshooting
- improved handling with boomark toolbar status
- all the "betterboxing" stuff - https://blog.torproject.org/new-release-tor-browser-135/
- improved default max sizes
- maybe tying it to RFP

So FF's settings are `1000 x 1000` max, with stepping - if you're not in that, you fail the `RFP newwin`. But MB and TB have `1400 x 900`, with stepping, so they don't live by the same rules (e.g. resize it to 1000 x 1000 and it will fail, but FF won't). AF uses 1600 x 900 max because we are not a crowd and we want shit to be usable

PS: I was the instigator in getting the sizes increased - https://blog.torproject.org/new-release-tor-browser-130/ Bigger New Windows

**Comment by Thorin-Oakenpants** [comment]
also, check out the new metrics view (when I update to the new TZP version)
- this is TB14 (based on FF128) and using `file://` scheme, hence a few failures: canvas doesn't work on file:// and I am waiting for a new release to update some expected values
- the header is sticky
- you can ctrl-c to copy
- you can esc to close (this has always been there)
- you can download the JSON and it's named for you with the platform + brand + version + description and hash
- you can toggle different views
   - these views depend on what you're looking at, e.g. section data, overall fingerprint, health, etc

![okie dokie](https://github.com/arkenfox/user.js/assets/16656956/4d940536-1118-44fa-a275-f85769fdd2d8)

**Comment by Thorin-Oakenpants** [comment]
> TB and MB are not effected is I believe because the newwin sizes are coded directly inside the browsers

no, they just use the prefs like we do :)

**Comment by BingoBongoLad** [comment]
Yo my man, thank you so much for answering me in such an exhaustive way! I admit that I don't have a 100%, total, complete understanding of everything but I got quite a fair amount of it, surprisingly. Thank you again!

**Comment by Thorin-Oakenpants** [comment]
it's quite cathartic to type it out actually :)
