### ISSUE TITLE
UBO w/ Arkenfox question

### ISSUE THREAD

**Issue by dude4fox** [arkenfox/user.js#1883]
Since the "before times", I've had the following rules in my UBO dashboard:
>no-large-media: behind-the-scene true
>behind-the-scene * 1p-script block
>behind-the-scene * 3p block
>behind-the-scene * 3p-frame block
>behind-the-scene * 3p-script block
>behind-the-scene * image block
>behind-the-scene * inline-script block

Is any of this still necessary (if ever) today, post advancement of isolated state data on FF/Arkenfox? 
Again, apologies if this is out of scope. 
Thank you. 
 

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: n/a
  - Steps to Reproduce (STR): n/a
  - Expected result: n/a
  - Actual result: n/a
  - Console errors and warnings: n/a
  - Anything else you deem worth mentioning: updated knowledge/insight on ublock origin settings with modern FF/Arkenfox user.js.

---

**Comment by Thorin-Oakenpants** [comment]
It's not _necessary_ per se - each domain (eTLD+1 per scheme and per window type [1]) are isolated. That said, the fastest code is no code (and no trackers and adverts and crap) - it's entirely up to you how you use uBO. Also note #1448 - so blocking 3rd party by default helps here

personally, I use these
```
* * 3p block
* * 3p-frame block
* * 3p-script block
```

Then I unbreak some regular sites with selective rules. This suits me for the 150 odd sites I use regularly. Many one-off sites are readable (e.g hackernews items etc), if not, using reader mode usually suffices - otherwise I can flick it open in nightly (which is sanitized fully on close with default uBO).

[1] normal, private, containers
