### ISSUE TITLE
Additions and/or changes to "7003: disable non-modern cipher suites"

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1899]
In Tor Browser, they disable all ciphers that use SHA-1.

https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/001-base-profile.js#L131-140

Should we do this in Arkenfox too to improve security? (Of course, in a separate section instead of 7000.)

And also, what about adding all `security.ssl3.*` prefs to the user.js (to force clean-up)?
Tor Browser has "dhe" prefs, not present in `7003`.

**Comment by Thorin-Oakenpants** [comment]
We are NOT tor browser. The entries at TB were added on my recommendation. TB is a captive audience, we can do what we want.

These are already in the user.js for prefsCleaner - clearly in section 7000 DO NOT USE with a WHY. There is nowhere else for them to go, or any other reason to have them listed (top educate and reset). These are ciphers that misguided users might _disable_. The dhe ciphers have been disabled by default [since FF78](https://bugzilla.mozilla.org/show_bug.cgi?id=1496639) and at some subsequent stage were removed from the user.js as dead wood

https://github.com/arkenfox/user.js/blob/f906f7f3b41fe3f6aaa744980431f4fdcd086379/user.js#L1080-L1090
