### ISSUE TITLE
[Questions] Effects on changing network.trr.default_provider_uri + Inner window size, bookmarks toolbar and letterboxing wrt to different platforms

### ISSUE THREAD

**Issue by itsordinaryperson** [arkenfox/user.js#1901]
**Effects on changing network.trr.default_provider_uri**

Any reason to not change default fallback DNS? This can found at about:config and about:networking#dns. I've set network.trr.mode to 5 and using system DNS as default resolver.

**Inner window size, bookmarks toolbar and letterboxing wrt to different platforms:**

1. RFP, Letterboxing: Enabled
2. Platform(Version): Linux mint wilma(FF 130.0) & Windows 10 VM (FF 130.0.1)
3. Width x height: 1600 x 900
4. Steps to reproduce: Open FF. Toggle bookmarks toolbar to always show/never show based on your existing setup. Close session and open FF.

Expected result:
Linux mint: Inner window size fixed at 1600 x 900. With toolbar 100/200 difference in height and letterboxing present. Without toolbar its 1600x900 and no letterboxing.
Windows 10: Fixed at 1600x900 and no letterboxing after reopening FF and it doesn't mind toolbar.

**Override from new user for neat fox**
`user_pref("extensions.pocket.enabled", false); // Disable Pocket extension`

**Comment by Thorin-Oakenpants** [comment]
`network.trr.default_provider_uri` - what does this have to do with arkenfox? what are you trying to achieve? if you're not using DNS over HTTPS then you're already using "system DNS" (e.g. system or VPN or whatever). IANANetworkingExpert but this all seems like nonsense, unless I'm missing something

`extensions.pocket.enabled` - where are the privacy concerns. Hint: there are none. Also users can remove any UI manually if they want (pocket button). And arkenfox doesn't use activity stream by default, but if users enable that they can also hide the pocket stuff on there.

---

show/hide toolbar

LB
- letterboxing doesn't require RFP
- letterboxing being enabled has nothing to do with the bookmarks toolbar
   - so I will assume when you say "no LBing" you mean the new window size is a perfect fit and no LBing is showing
- letterboxing has exceptions, some carved out but basically it comes down to the [principal](https://blog.mozilla.org/attack-and-defense/2020/06/10/understanding-web-security-checks-in-firefox-part-1/)

new window sizes
- RFP is required for newwin sizes

toolbar
- so if the toolbar is always on or always off then the chrome is static and we have no issues
- if the toolbar is shown when newwin kicks in, then the height of the toolbar eats screen real estate and reduces what is available for the inner window
- if the toolbar is `only show on new tabs` then we can easily get into a mess (too tall or too short)
   - because the state of the toolbar is not consistent on new win creation!! capisce?!!?
   - https://bugzilla.mozilla.org/show_bug.cgi?id=1677733 especially comment 20
   - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42192

There's about 2+ years worth of LBing and newwin patches/fixes/improvements from TB that we want to upstream to Firefox, but it's a bit involved. Additionally, there are _still_ newwin size issues where I believe we just need to do a second newwin check to adjust (as easily seen in TB's double-click the LBing area to snap to size)

Meanwhile, LBing protects you by still rounding the inner window. I'd rather not rely on this, as it can still affects your entropy (because the metric changed) hence in TB I want to do a "double newwin"
