### ISSUE TITLE
arkenfox has evolved into great piece of trash

### ISSUE THREAD

**Issue by panty-sniffer** [arkenfox/user.js#1906]
normies don't use arkenfox. they don't even use firefox. and they certainly do not read wiki. there is zero reason firefox sync, firefox pocket, firefox labs, firefox lockwise (or built-in password manager), more from mozilla, ~~google~~ e-corp safe browsing needs to be enabled by default. at least provide a separate user.js for users with hardened privacy demands who are now having to monitor and flip arkenfox settings every release or migrate to forks like librewolf to preserve the privacy they signed up for when downloading arkenfox.

**Comment by rusty-snake** [comment]
> firefox sync, firefox pocket, firefox labs, firefox lockwise (or built-in password manager), more from mozilla,

> with hardened privacy demands 

What privacy violations are caused by not turning them off?

> monitor and flip arkenfox settings every release

1. For the most releases nothing changes.
2. You need to monitor and adjust your overrides anyway because if things like clearInShutdown_v2.

**Comment by 9ao9ai9ar** [comment]
What exactly is the question or problem here? LibreWolf does not auto-update, Mullvad is a better option. If you want more stability, use ESR and don't run the arkenfox updater.

**Comment by Thorin-Oakenpants** [comment]
it's a ~~trap!~~ troll

**Comment by Thorin-Oakenpants** [comment]
commits in the last year - half of these are non-user.js, e.g. scratchpad, updater

![commits](https://github.com/user-attachments/assets/af94061d-3fc9-4e30-b926-da5d7083ad33)

code frequency ... stable as fuck since jan 2022

![code](https://github.com/user-attachments/assets/edac7813-1251-44c3-a590-75de1b3abcc6)

https://github.com/arkenfox/user.js/releases
- at one stage, from memory but I did analyze and discuss it in a comment somewhere at the time, over 9 months there was only 1 meaningful pref change

In terms of hardening ... if you need your hand held to change three prefs to enable RFP + LBing and disable webGL, then arkenfox is not for you. All the other "hardening" is pretty much snake oil and useless

Also, side note: LW since fxbrit left/died/who-knows has gone to shit - I worked with him behind the scenes to make the right choices and while he would do his own analysis, we always agreed, and his voice influenced them. Now they don't know what they are doing, and in fact have compromised security and make really stupid decisions. Same goes for all the other forks - really dubious shit going

**Comment by threadpanic** [comment]
Hey all, I'm on the LibreWolf team, and it's true that since the departure of @fxbrit the project has taken a total nosedive when it comes to keeping up to date with Arkenfox and settings in general. We're still making releases, but settings did not get updated. 
There are also a bunch of useful tickets that also take my time, I've not been able to take the LW settings to the last AF release.

I'm mostly a c/rust/vulkan hobby person, not at all good with Browser Security. My first impression is that it's a total mine field :)

**Comment by Thorin-Oakenpants** [comment]
> when it comes to keeping up to date with Arkenfox

count the changes :) we're talking sesame street numbers here
![count](https://github.com/user-attachments/assets/812919d4-9918-43b2-9208-8742ed66602d)

I'm sorry you guys/gals can't keep up - it's not a few arkenfox pref changes, it goes way deeper than that

**Comment by Thorin-Oakenpants** [comment]
@threadpanic I'm super swamped right now, and I don't mind giving free advise. fxbrit had access to a private repo just used to discuss stuff - there are 2 others there as well as myself. What is said in there stays in there, and it's pretty blunt at times :)

What I liked about it was a few times I could leverage fxbrit's networking knowledge, otherwise he would do his own thing and check with me about something - and I am more than happy to explain _why_ we did something, and sometimes it would lead to a reveiw and a change. But mostly it was fxbrit listening and doing his own due diligence and coming to the same conclusion.

Since fxbrit's demise/vanishing/alien-abduction it's been mostly quiet - but if you have someone thick-skinned in mind, then I will consider adding them so they can ask me things (which is good because it also makes me look at things I may have missed)

**Comment by threadpanic** [comment]
@Thorin-Oakenpants Hey THorin, it sounds great to be able to work with you on this, but within the LW team there are two other people who have frankly, better credentials, one being Malte a driving force for LibreWolf, another being Sertonix who helped me out a ton with settings regarding DNS over HTTPS. I've spoken to Malte about it and he's interested (and smart) Let's wait until they make clear what they want..

**Comment by maltejur** [comment]
As @threadpanic said, since fxbrit left we have been in a kind of "maintenance" mode in terms of settings. Mainly because we are really only three people left, who all only have varying time to put into the project. We have been only doing basic pref changes, reacting to upstream changes (like the PPA stuff, and the weather widget on the new tab page for example). I so far have been working more on the infrastructure side of things. But we have had some discussion in our build chat the last days, and decided on new and more clear responsibilities. I will now take care of maintaining the settings, and will generally put in a bit more time, hopefully doing a similarly good job at some point as fxbrit once did. That also means I will probably be somewhat active in the arkenfox repo in the future. And if you are willing to add me to the private repo, I would also be happy to join.

> Since fxbrit's demise/vanishing/alien-abduction

I don't remember the specifics, but from what I remember, they are doing fine and just have other things in life going on now :)

**Comment by Thorin-Oakenpants** [comment]
So first I need to _really_ think about this, now I have a little more info and you replied

First, I need to check the other two perps in the repo are OK with it - there's a lot of info in that repo, and _nothing_ is for the general public - I need their signoff - so I may have jumped the gun a little.

Second, I am _really_ pushed for time/resources, although TBH, answering a _few_ questions here and there is a good way to take a (micro) break now and then.

I'm also starting to doubt now if it's worth it considering you're down to 3 part time people and I don't see any improvement in issues - it's escalating. Do I really want to spend my time flogging a dead horse?

I'm also not really into supporting your fork per se (to help you guys) [1], if I did do anything it would be to help arkenfox (i.e stop LW giving me a bad name - everywhere I look I see people saying LW is AF pre setup = not true)

I supported fxbrit because _he_ reached out to me, not the other way round, and he won me over in a flash .. he is one sexy and smart fish - and I had to do something, since your fork was giving AF a bad name (at the time - remember all those 600 or so prefs difference? man, that was so long ago)

[1] as it's completely not needed IMO (a ton of reasons) - also it's "slow" AF (at least on windows and I suspect all of them) because it lacks build optimizations (IANAE) - consistently 30% slower in speedometer (I disable uBO and RFP to get accurate timings to compare).

> like the PPA stuff, and the weather widget

there was nothing to do - a classic example of time wasting which is indicative of a lot of decisions

anyway, let's see what happens

**Comment by maltejur** [comment]
> Do I really want to spend my time flogging a dead horse?

> Second, I am really pushed for time/resources

If you don't want to add me right now, that is totally understandable and fine by me. As I said, I just took over responsibility of the settings. So if you want to, you can also wait a few months to see if the situation improves.

> there was nothing to do - a classic example of time wasting which is indicative of a lot of decisions

I mentioned that exactly to point out that we only did very basic changes since fxbrit left

**Comment by threadpanic** [comment]
@Thorin-Oakenpants Yes, I agree with all your points of criticism on LW. 

When I first starting building LW for windows (on windows!) it was just me doing my first Open Source thing ever. 

I could not make the Mozilla AutoUpdate stuff to work, so I just created a temporary nsi... it started to live it's own life and I just ran away from windows as fast as I could. 

I created a build system in the meanwhile: bsys5, a bunch of ugly scripts and Makefiles. This lead to bsys6, a complete rewrite by Malte, and *I consider this bsys6 a nice candidate for a separation away from LW*, and just be 'a tool that allows you to easily build FF/LW/Nightly/whatever for different platforms. It feels as a valid spin-off that provides tangible value.

The idea to brand LW as having three upstreams: (FF release, uBlock Origin, and user.js) was (probably, i dont remember) to blame on me: I just wanted to make it *simple for people to understand* what LW is about. And that worked when we had @fxbrit, it provided value. It doesn't anymore, so I want to apologize for that to you, and I'll see how we can fix this. I'm sorry.
