### ISSUE TITLE
Update advice on Cookie extensions in your wiki

### ISSUE THREAD

**Issue by tenzap** [arkenfox/user.js#1913]
On your wiki page https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-dont-bother, you mention:

- Cookie extensions
  - ❗️Cookie extensions can lack APIs or implementation of them to properly sanitize
        e.g. at the time of writing: [Cookie Auto Delete](https://addons.mozilla.org/firefox/addon/cookie-autodelete/)
    - As of Firefox 86, strict mode is not supported at this time due to missing APIs to handle the Total Cookie Protection

On the https://addons.mozilla.org/fr/firefox/addon/cookie-autodelete/ page there is now written:
> As of Firefox 86, strict mode is not supported at this time due to missing APIs to handle the Total Cookie Protection. Also as of Firefox 103, standard mode has also enabled Total Cookie Protection. Use 'strict' mode if using pre-86, use standard mode for versions 86-102, or from version 103+ use the custom configuration and set cookie to 'cross site tracking cookies' option (not the cross-site cookies).

So I suppose this means the extension is able to work properly with present versions of firefox.

Can you review your comment on that extension please and tell if that changes something to your analysis?

BTW, is the [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) enabled also when using "custom configuration" for ETP (enhanced tracking protection), or only when using strict ETP ?
EDIT: apparently, it is, according to https://github.com/orgs/privacyguides/discussions/420

**Comment by Thorin-Oakenpants** [comment]
It doesn't change anything. What they are instructing users to do is how to disable dFPI / TCP - and that's **_f*cking disgusting_** 

cookie extensions are a giant pile of shit and about 10 years past their use by date - do not touch with a barge pole, or even your worst enemy's bean pole

**Comment by Thorin-Oakenpants** [comment]
> * Cookie extensions
>   - ❗️Sanitizing in-session is a false sense of privacy. [They do nothing for IP tracking](https://educatedguesswork.org/posts/traffic-relaying/). Even Tor Browser does not sanitize in-session e.g. when you request a new circuit. A new ID requires _both_ full sanitizing _and_ a new IP. The same applies to Firefox

**Comment by Thorin-Oakenpants** [comment]
cc @rusty-snake clean up in aisle 5

**Comment by rusty-snake** [comment]
The PG Discussion repo is archived (they use their own forum now). The information there will stay there forever with the state as of 2021.

**Comment by Thorin-Oakenpants** [comment]
nothing wrong with it .. I just wanted to say aisle `5` :D

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/4.1-Extensions/904c0b4f59674063ee39d40562f59f6f5fa246d3

done, edited the wiki .. CAD needs to go die in a fire

@tenzap sorry if I sound angry or something (I'm not) ... thanks for asking .. enjoy the show .. what could go wrong they said :)

**Comment by Thorin-Oakenpants** [comment]
the privacyguides discussion is over three years old - it doesn't matter if it's correct or things (cosmetic/major) have changed in the meantime - don't ever use old information

like I said, of the five things in custom, only one could possibly interest a user - cookies (which means cookies and site dat: cookies, localStorage, sessionStorage, IDB, service worker cache, asm cache .. etc)

but even then, none of the cookie options should be appealing to anyone because if you change from default you lose TCP.
- "dFPI" = everything (all those partitioning tests on privacytests) = it was the name given to rolling out the whole thing (a successor to tor browser's FPI)
   - TCP is the cookies and site data part of "dFPI" - this is the dynamic part, some of it - e.g. to allow you to use google to sign into youtube
   - network partitioning is the rest of "dFPI" - this isn't dynamic (or shouldn't be)

So the entire "custom" can go and get bent and fuck off and I will not support it :)  Because as soon as you lose TCP you lose all that partitioning, regardless of if you delete site data afterwards.

The easiest way to know if TCP is on it to check `network.cookie.cookieBehavior` = `5`
