### ISSUE TITLE
webgl.disabled breaks github.com homepage

### ISSUE THREAD

**Issue by dimon222** [arkenfox/user.js#1916]
... I know it will sound very ironic, but homepage of Github.com when **you're not logged in** is now using Webgl for some logic. Disabling WebGL renders page not loadable with potentially infinite leak for Firefox leading to "page is not responding". I suppose when you're logged in, this weird mechanics is skipped, that's why I'm able to write this message right now.

While I understand the benefits its meant to provide, I think its counter-intuitive to enable it by default now that it will effectively deem being unable to reach the even this repository to get the solution. It wasn't even straightforward that its exactly user.js modification issue until I was able to open web inspector prior loading homepage of github.com to see all the stacks of WebGL errors that eventually lead to page freeze.

**Comment by Thorin-Oakenpants** [comment]
worksforme - not logged in - flipped `webgl.disabled` to `true` in nightly and can access things just fine

**Comment by dimon222** [comment]
Hm, strange, perhaps something else on top of it worsens the issue. I'm seeing exactly opposite - leak disappears with fast page loading when I flip webgl.disabled to false. I'm using the same user.js of "date: 26 August 2024" in master branch.

**Comment by 9ao9ai9ar** [comment]
It only affects the homepage, and only on the latest non-ESR versions. You can read, for example, this issues page without logging in just fine.

**Comment by Thorin-Oakenpants** [comment]
I also know that at least back in 2019, hackerone also required basic webgl functionality just for logging in. This kinda seems arbitrary unlike wasm being required in some login flows

**Comment by Thorin-Oakenpants** [comment]
So since v128 ... arkenfox default is RFP off, letterboxing off, webgl on .. because we can use FPP which will get better over time, and removes all the weird quirks of using RFP (which in turn are being addressed, although some are never going to have a solution)

If users change that then they need to live with the consequences - I don't even mention it as something to change in the wiki [common overrides](https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]) - and I currently only have a setup-web tag on RFP. That said, we can tweak the user.js to add this info

**Comment by 9ao9ai9ar** [comment]
Somehow the problem is fixed now. Not sure whether it's due to the upgrade to Firefox 133 or GitHub's own bug squashing.

**Comment by Thorin-Oakenpants** [comment]
[okie dokie](https://en.wikipedia.org/wiki/Fallout_(American_TV_series)) ... reverted
